-- Migração: coleção Legends (80 figurinhas: 20 atletas × Lilás, Bronze, Prata, Ouro)
-- Rode depois das migrações anteriores. Idempotente.
--
-- Códigos: LIL1–20, BRO1–20, PRA1–20, OUR1–20 — o número é o atleta, em ordem alfabética
-- (1 Achraf Hakimi … 13 Lionel Messi … 20 Vinícius Júnior; lista completa em album.json → labels).

alter table public.stickers drop constraint if exists stickers_block_type_check;
alter table public.stickers
  add constraint stickers_block_type_check check (block_type in ('TEAM','FWC','CC','LEG'));

insert into public.stickers (code, block_id, block_name, block_type, group_key, position) values
('LIL1','LIL','Legends Lilás','LEG','LEG',1),
('LIL2','LIL','Legends Lilás','LEG','LEG',2),
('LIL3','LIL','Legends Lilás','LEG','LEG',3),
('LIL4','LIL','Legends Lilás','LEG','LEG',4),
('LIL5','LIL','Legends Lilás','LEG','LEG',5),
('LIL6','LIL','Legends Lilás','LEG','LEG',6),
('LIL7','LIL','Legends Lilás','LEG','LEG',7),
('LIL8','LIL','Legends Lilás','LEG','LEG',8),
('LIL9','LIL','Legends Lilás','LEG','LEG',9),
('LIL10','LIL','Legends Lilás','LEG','LEG',10),
('LIL11','LIL','Legends Lilás','LEG','LEG',11),
('LIL12','LIL','Legends Lilás','LEG','LEG',12),
('LIL13','LIL','Legends Lilás','LEG','LEG',13),
('LIL14','LIL','Legends Lilás','LEG','LEG',14),
('LIL15','LIL','Legends Lilás','LEG','LEG',15),
('LIL16','LIL','Legends Lilás','LEG','LEG',16),
('LIL17','LIL','Legends Lilás','LEG','LEG',17),
('LIL18','LIL','Legends Lilás','LEG','LEG',18),
('LIL19','LIL','Legends Lilás','LEG','LEG',19),
('LIL20','LIL','Legends Lilás','LEG','LEG',20),
('BRO1','BRO','Legends Bronze','LEG','LEG',1),
('BRO2','BRO','Legends Bronze','LEG','LEG',2),
('BRO3','BRO','Legends Bronze','LEG','LEG',3),
('BRO4','BRO','Legends Bronze','LEG','LEG',4),
('BRO5','BRO','Legends Bronze','LEG','LEG',5),
('BRO6','BRO','Legends Bronze','LEG','LEG',6),
('BRO7','BRO','Legends Bronze','LEG','LEG',7),
('BRO8','BRO','Legends Bronze','LEG','LEG',8),
('BRO9','BRO','Legends Bronze','LEG','LEG',9),
('BRO10','BRO','Legends Bronze','LEG','LEG',10),
('BRO11','BRO','Legends Bronze','LEG','LEG',11),
('BRO12','BRO','Legends Bronze','LEG','LEG',12),
('BRO13','BRO','Legends Bronze','LEG','LEG',13),
('BRO14','BRO','Legends Bronze','LEG','LEG',14),
('BRO15','BRO','Legends Bronze','LEG','LEG',15),
('BRO16','BRO','Legends Bronze','LEG','LEG',16),
('BRO17','BRO','Legends Bronze','LEG','LEG',17),
('BRO18','BRO','Legends Bronze','LEG','LEG',18),
('BRO19','BRO','Legends Bronze','LEG','LEG',19),
('BRO20','BRO','Legends Bronze','LEG','LEG',20),
('PRA1','PRA','Legends Prata','LEG','LEG',1),
('PRA2','PRA','Legends Prata','LEG','LEG',2),
('PRA3','PRA','Legends Prata','LEG','LEG',3),
('PRA4','PRA','Legends Prata','LEG','LEG',4),
('PRA5','PRA','Legends Prata','LEG','LEG',5),
('PRA6','PRA','Legends Prata','LEG','LEG',6),
('PRA7','PRA','Legends Prata','LEG','LEG',7),
('PRA8','PRA','Legends Prata','LEG','LEG',8),
('PRA9','PRA','Legends Prata','LEG','LEG',9),
('PRA10','PRA','Legends Prata','LEG','LEG',10),
('PRA11','PRA','Legends Prata','LEG','LEG',11),
('PRA12','PRA','Legends Prata','LEG','LEG',12),
('PRA13','PRA','Legends Prata','LEG','LEG',13),
('PRA14','PRA','Legends Prata','LEG','LEG',14),
('PRA15','PRA','Legends Prata','LEG','LEG',15),
('PRA16','PRA','Legends Prata','LEG','LEG',16),
('PRA17','PRA','Legends Prata','LEG','LEG',17),
('PRA18','PRA','Legends Prata','LEG','LEG',18),
('PRA19','PRA','Legends Prata','LEG','LEG',19),
('PRA20','PRA','Legends Prata','LEG','LEG',20),
('OUR1','OUR','Legends Ouro','LEG','LEG',1),
('OUR2','OUR','Legends Ouro','LEG','LEG',2),
('OUR3','OUR','Legends Ouro','LEG','LEG',3),
('OUR4','OUR','Legends Ouro','LEG','LEG',4),
('OUR5','OUR','Legends Ouro','LEG','LEG',5),
('OUR6','OUR','Legends Ouro','LEG','LEG',6),
('OUR7','OUR','Legends Ouro','LEG','LEG',7),
('OUR8','OUR','Legends Ouro','LEG','LEG',8),
('OUR9','OUR','Legends Ouro','LEG','LEG',9),
('OUR10','OUR','Legends Ouro','LEG','LEG',10),
('OUR11','OUR','Legends Ouro','LEG','LEG',11),
('OUR12','OUR','Legends Ouro','LEG','LEG',12),
('OUR13','OUR','Legends Ouro','LEG','LEG',13),
('OUR14','OUR','Legends Ouro','LEG','LEG',14),
('OUR15','OUR','Legends Ouro','LEG','LEG',15),
('OUR16','OUR','Legends Ouro','LEG','LEG',16),
('OUR17','OUR','Legends Ouro','LEG','LEG',17),
('OUR18','OUR','Legends Ouro','LEG','LEG',18),
('OUR19','OUR','Legends Ouro','LEG','LEG',19),
('OUR20','OUR','Legends Ouro','LEG','LEG',20)
on conflict (code) do nothing;

-- Preço de grupo das Legends na loja (null = sem preço).
alter table public.shops
  add column if not exists price_leg_cents int check (price_leg_cents >= 0);
