-- Migração: Limited Editions da Adrenalyn XL (187 cards, sem número oficial). Idempotente.
-- Rode depois de supabase_migration_collections_phase3.sql.
--
-- Fonte: data/adrenalyn-xl-limited.csv (lista de colecionadores — Collectosk). Códigos próprios:
-- AXLLE (Limited Edition, 90), AXLLH (Holo, 25), AXLPR (Premium, 12), AXLPG (Premium Gold, 6),
-- AXLXL (XXL, 36), AXLXH (XXL Holo, 18). Ficam fora do total de 630 da coleção.

alter table public.stickers drop constraint if exists stickers_block_type_check;
alter table public.stickers
  add constraint stickers_block_type_check
  check (block_type in ('TEAM','FWC','CC','LEG','SPECIAL','CONTENDER','LIMITED'));

insert into public.stickers
  (code, album_id, block_id, block_name, block_type, group_key, position, number, name, team_code, card_type, player_position)
values
('AXLLE1','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1001,null,'Abdukodir Khusanov','UZB','LIMITED',null),
('AXLLE2','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1002,null,'Achraf Hakimi','MAR','LIMITED',null),
('AXLLE3','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1003,null,'Alphonso Davies','CAN','LIMITED',null),
('AXLLE4','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1004,null,'Amad Diallo','CIV','LIMITED',null),
('AXLLE5','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1005,null,'Antonio Nusa','NOR','LIMITED',null),
('AXLLE6','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1006,null,'Antonio Rüdiger','GER','LIMITED',null),
('AXLLE7','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1007,null,'Arda Güler','TUR','LIMITED',null),
('AXLLE8','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1008,null,'Aurélien Tchouaméni','FRA','LIMITED',null),
('AXLLE9','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1009,null,'Brahim Díaz','MAR','LIMITED',null),
('AXLLE10','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1010,null,'Bukayo Saka','ENG','LIMITED',null),
('AXLLE11','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1011,null,'Chris Wood','NZL','LIMITED',null),
('AXLLE12','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1012,null,'Christian Pulisic','USA','LIMITED',null),
('AXLLE13','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1013,null,'Cole Palmer','ENG','LIMITED',null),
('AXLLE14','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1014,null,'Cristiano Ronaldo','POR','LIMITED',null),
('AXLLE15','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1015,null,'Darwin Núñez','URU','LIMITED',null),
('AXLLE16','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1016,null,'David Alaba','AUT','LIMITED',null),
('AXLLE17','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1017,null,'Dean Huijsen','ESP','LIMITED',null),
('AXLLE18','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1018,null,'Declan Rice','ENG','LIMITED',null),
('AXLLE19','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1019,null,'Denzel Dumfries','NED','LIMITED',null),
('AXLLE20','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1020,null,'Désiré Doué','FRA','LIMITED',null),
('AXLLE21','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1021,null,'Eberechi Eze','ENG','LIMITED',null),
('AXLLE22','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1022,null,'Erling Haaland','NOR','LIMITED',null),
('AXLLE23','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1023,null,'Estêvão','BRA','LIMITED',null),
('AXLLE24','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1024,null,'Federico Valverde','URU','LIMITED',null),
('AXLLE25','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1025,null,'Florian Wirtz','GER','LIMITED',null),
('AXLLE26','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1026,null,'Gilberto Mora','MEX','LIMITED',null),
('AXLLE27','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1027,null,'Giuliano Simeone','ARG','LIMITED',null),
('AXLLE28','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1028,null,'Granit Xhaka','SUI','LIMITED',null),
('AXLLE29','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1029,null,'Harry Kane','ENG','LIMITED',null),
('AXLLE30','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1030,null,'Heungmin Son','KOR','LIMITED',null),
('AXLLE31','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1031,null,'Jamal Musiala','GER','LIMITED',null),
('AXLLE32','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1032,null,'Jérémy Doku','BEL','LIMITED',null),
('AXLLE33','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1033,null,'João Neves','POR','LIMITED',null),
('AXLLE34','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1034,null,'Jonathan David','CAN','LIMITED',null),
('AXLLE35','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1035,null,'Jonathan Tah','GER','LIMITED',null),
('AXLLE36','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1036,null,'Joshua Kimmich','GER','LIMITED',null),
('AXLLE37','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1037,null,'Joško Gvardiol','CRO','LIMITED',null),
('AXLLE38','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1038,null,'Jude Bellingham','ENG','LIMITED',null),
('AXLLE39','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1039,null,'Jules Koundé','FRA','LIMITED',null),
('AXLLE40','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1040,null,'Julián Alvarez','ARG','LIMITED',null),
('AXLLE41','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1041,null,'Kai Havertz','GER','LIMITED',null),
('AXLLE42','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1042,null,'Kevin De Bruyne','BEL','LIMITED',null),
('AXLLE43','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1043,null,'Kylian Mbappé','FRA','LIMITED',null),
('AXLLE44','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1044,null,'Lamine Yamal','ESP','LIMITED',null),
('AXLLE45','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1045,null,'Lautaro Martínez','ARG','LIMITED',null),
('AXLLE46','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1046,null,'Leon Goretzka','GER','LIMITED',null),
('AXLLE47','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1047,null,'Leroy Sané','GER','LIMITED',null),
('AXLLE48','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1048,null,'Lionel Messi','ARG','LIMITED',null),
('AXLLE49','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1049,null,'Luis Díaz','COL','LIMITED',null),
('AXLLE50','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1050,null,'Luka Modrić','CRO','LIMITED',null),
('AXLLE51','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1051,null,'Marc-André ter Stegen','GER','LIMITED',null),
('AXLLE52','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1052,null,'Marc Cucurella','ESP','LIMITED',null),
('AXLLE53','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1053,null,'Marcus Thuram','FRA','LIMITED',null),
('AXLLE54','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1054,null,'Marquinhos','BRA','LIMITED',null),
('AXLLE55','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1055,null,'Martin Ødegaard','NOR','LIMITED',null),
('AXLLE56','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1056,null,'Mathew Ryan','AUS','LIMITED',null),
('AXLLE57','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1057,null,'Michael Olise','FRA','LIMITED',null),
('AXLLE58','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1058,null,'Minjae Kim','KOR','LIMITED',null),
('AXLLE59','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1059,null,'Mohamed Salah','EGY','LIMITED',null),
('AXLLE60','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1060,null,'Moisés Caicedo','ECU','LIMITED',null),
('AXLLE61','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1061,null,'Nick Woltemade','GER','LIMITED',null),
('AXLLE62','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1062,null,'Nico Paz','ARG','LIMITED',null),
('AXLLE63','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1063,null,'Nico Williams','ESP','LIMITED',null),
('AXLLE64','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1064,null,'Nuno Mendes','POR','LIMITED',null),
('AXLLE65','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1065,null,'Omar Marmoush','EGY','LIMITED',null),
('AXLLE66','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1066,null,'Oscar Bobb','NOR','LIMITED',null),
('AXLLE67','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1067,null,'Ousmane Dembélé','FRA','LIMITED',null),
('AXLLE68','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1068,null,'Pau Cubarsí','ESP','LIMITED',null),
('AXLLE69','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1069,null,'Pedri','ESP','LIMITED',null),
('AXLLE70','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1070,null,'Rafael Leão','POR','LIMITED',null),
('AXLLE71','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1071,null,'Raphinha','BRA','LIMITED',null),
('AXLLE72','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1072,null,'Rodri','ESP','LIMITED',null),
('AXLLE73','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1073,null,'Rodrygo','BRA','LIMITED',null),
('AXLLE74','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1074,null,'Romelu Lukaku','BEL','LIMITED',null),
('AXLLE75','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1075,null,'Ryan Gravenberch','NED','LIMITED',null),
('AXLLE76','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1076,null,'Sadio Mané','SEN','LIMITED',null),
('AXLLE77','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1077,null,'Santiago Giménez','MEX','LIMITED',null),
('AXLLE78','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1078,null,'Scott McTominay','SCO','LIMITED',null),
('AXLLE79','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1079,null,'Takefusa Kubo','JPN','LIMITED',null),
('AXLLE80','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1080,null,'Thibaut Courtois','BEL','LIMITED',null),
('AXLLE81','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1081,null,'Tijjani Reijnders','NED','LIMITED',null),
('AXLLE82','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1082,null,'Viktor Gyökeres','SWE','LIMITED',null),
('AXLLE83','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1083,null,'Vinícius Júnior','BRA','LIMITED',null),
('AXLLE84','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1084,null,'Virgil van Dijk','NED','LIMITED',null),
('AXLLE85','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1085,null,'Vitinha','POR','LIMITED',null),
('AXLLE86','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1086,null,'Weston McKennie','USA','LIMITED',null),
('AXLLE87','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1087,null,'Willian Pacho','ECU','LIMITED',null),
('AXLLE88','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1088,null,'Xavi Simons','NED','LIMITED',null),
('AXLLE89','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1089,null,'150 Coins',null,'LIMITED',null),
('AXLLE90','wc2026-adrenalyn','axl-limited','Limited Edition','LIMITED','LIMITED',1090,null,'350 Coins',null,'LIMITED',null),
('AXLLH1','wc2026-adrenalyn','axl-limited-holo','Limited Edition Holo','LIMITED','LIMITED',1091,null,'Abdukodir Khusanov','UZB','LIMITED_HOLO',null),
('AXLLH2','wc2026-adrenalyn','axl-limited-holo','Limited Edition Holo','LIMITED','LIMITED',1092,null,'Achraf Hakimi','MAR','LIMITED_HOLO',null),
('AXLLH3','wc2026-adrenalyn','axl-limited-holo','Limited Edition Holo','LIMITED','LIMITED',1093,null,'Antonio Nusa','NOR','LIMITED_HOLO',null),
('AXLLH4','wc2026-adrenalyn','axl-limited-holo','Limited Edition Holo','LIMITED','LIMITED',1094,null,'Cole Palmer','ENG','LIMITED_HOLO',null),
('AXLLH5','wc2026-adrenalyn','axl-limited-holo','Limited Edition Holo','LIMITED','LIMITED',1095,null,'Cristiano Ronaldo','POR','LIMITED_HOLO',null),
('AXLLH6','wc2026-adrenalyn','axl-limited-holo','Limited Edition Holo','LIMITED','LIMITED',1096,null,'Erling Haaland','NOR','LIMITED_HOLO',null),
('AXLLH7','wc2026-adrenalyn','axl-limited-holo','Limited Edition Holo','LIMITED','LIMITED',1097,null,'Harry Kane','ENG','LIMITED_HOLO',null),
('AXLLH8','wc2026-adrenalyn','axl-limited-holo','Limited Edition Holo','LIMITED','LIMITED',1098,null,'Heungmin Son','KOR','LIMITED_HOLO',null),
('AXLLH9','wc2026-adrenalyn','axl-limited-holo','Limited Edition Holo','LIMITED','LIMITED',1099,null,'Jamal Musiala','GER','LIMITED_HOLO',null),
('AXLLH10','wc2026-adrenalyn','axl-limited-holo','Limited Edition Holo','LIMITED','LIMITED',1100,null,'Jérémy Doku','BEL','LIMITED_HOLO',null),
('AXLLH11','wc2026-adrenalyn','axl-limited-holo','Limited Edition Holo','LIMITED','LIMITED',1101,null,'Jude Bellingham','ENG','LIMITED_HOLO',null),
('AXLLH12','wc2026-adrenalyn','axl-limited-holo','Limited Edition Holo','LIMITED','LIMITED',1102,null,'Julián Alvarez','ARG','LIMITED_HOLO',null),
('AXLLH13','wc2026-adrenalyn','axl-limited-holo','Limited Edition Holo','LIMITED','LIMITED',1103,null,'Kevin De Bruyne','BEL','LIMITED_HOLO',null),
('AXLLH14','wc2026-adrenalyn','axl-limited-holo','Limited Edition Holo','LIMITED','LIMITED',1104,null,'Kylian Mbappé','FRA','LIMITED_HOLO',null),
('AXLLH15','wc2026-adrenalyn','axl-limited-holo','Limited Edition Holo','LIMITED','LIMITED',1105,null,'Lamine Yamal','ESP','LIMITED_HOLO',null),
('AXLLH16','wc2026-adrenalyn','axl-limited-holo','Limited Edition Holo','LIMITED','LIMITED',1106,null,'Lionel Messi','ARG','LIMITED_HOLO',null),
('AXLLH17','wc2026-adrenalyn','axl-limited-holo','Limited Edition Holo','LIMITED','LIMITED',1107,null,'Luis Díaz','COL','LIMITED_HOLO',null),
('AXLLH18','wc2026-adrenalyn','axl-limited-holo','Limited Edition Holo','LIMITED','LIMITED',1108,null,'Mohamed Salah','EGY','LIMITED_HOLO',null),
('AXLLH19','wc2026-adrenalyn','axl-limited-holo','Limited Edition Holo','LIMITED','LIMITED',1109,null,'Ousmane Dembélé','FRA','LIMITED_HOLO',null),
('AXLLH20','wc2026-adrenalyn','axl-limited-holo','Limited Edition Holo','LIMITED','LIMITED',1110,null,'Pedri','ESP','LIMITED_HOLO',null),
('AXLLH21','wc2026-adrenalyn','axl-limited-holo','Limited Edition Holo','LIMITED','LIMITED',1111,null,'Raphinha','BRA','LIMITED_HOLO',null),
('AXLLH22','wc2026-adrenalyn','axl-limited-holo','Limited Edition Holo','LIMITED','LIMITED',1112,null,'Tijjani Reijnders','NED','LIMITED_HOLO',null),
('AXLLH23','wc2026-adrenalyn','axl-limited-holo','Limited Edition Holo','LIMITED','LIMITED',1113,null,'Vinícius Júnior','BRA','LIMITED_HOLO',null),
('AXLLH24','wc2026-adrenalyn','axl-limited-holo','Limited Edition Holo','LIMITED','LIMITED',1114,null,'Virgil van Dijk','NED','LIMITED_HOLO',null),
('AXLLH25','wc2026-adrenalyn','axl-limited-holo','Limited Edition Holo','LIMITED','LIMITED',1115,null,'Vitinha','POR','LIMITED_HOLO',null),
('AXLPR1','wc2026-adrenalyn','axl-premium','Premium Limited','LIMITED','LIMITED',1116,null,'Eduardo Camavinga','FRA','PREMIUM',null),
('AXLPR2','wc2026-adrenalyn','axl-premium','Premium Limited','LIMITED','LIMITED',1117,null,'Erling Haaland','NOR','PREMIUM',null),
('AXLPR3','wc2026-adrenalyn','axl-premium','Premium Limited','LIMITED','LIMITED',1118,null,'Folarin Balogun','USA','PREMIUM',null),
('AXLPR4','wc2026-adrenalyn','axl-premium','Premium Limited','LIMITED','LIMITED',1119,null,'Kalidou Koulibaly','SEN','PREMIUM',null),
('AXLPR5','wc2026-adrenalyn','axl-premium','Premium Limited','LIMITED','LIMITED',1120,null,'Leroy Sané','GER','PREMIUM',null),
('AXLPR6','wc2026-adrenalyn','axl-premium','Premium Limited','LIMITED','LIMITED',1121,null,'Manuel Akanji','SUI','PREMIUM',null),
('AXLPR7','wc2026-adrenalyn','axl-premium','Premium Limited','LIMITED','LIMITED',1122,null,'Phil Foden','ENG','PREMIUM',null),
('AXLPR8','wc2026-adrenalyn','axl-premium','Premium Limited','LIMITED','LIMITED',1123,null,'Raúl Jiménez','MEX','PREMIUM',null),
('AXLPR9','wc2026-adrenalyn','axl-premium','Premium Limited','LIMITED','LIMITED',1124,null,'Sofyan Amrabat','MAR','PREMIUM',null),
('AXLPR10','wc2026-adrenalyn','axl-premium','Premium Limited','LIMITED','LIMITED',1125,null,'Takumi Minamino','JPN','PREMIUM',null),
('AXLPR11','wc2026-adrenalyn','axl-premium','Premium Limited','LIMITED','LIMITED',1126,null,'Vinícius Júnior','BRA','PREMIUM',null),
('AXLPR12','wc2026-adrenalyn','axl-premium','Premium Limited','LIMITED','LIMITED',1127,null,'Youri Tielemans','BEL','PREMIUM',null),
('AXLPG1','wc2026-adrenalyn','axl-premium-gold','Premium Gold Limited','LIMITED','LIMITED',1128,null,'James Rodríguez','COL','PREMIUM_GOLD',null),
('AXLPG2','wc2026-adrenalyn','axl-premium-gold','Premium Gold Limited','LIMITED','LIMITED',1129,null,'Lamine Yamal','ESP','PREMIUM_GOLD',null),
('AXLPG3','wc2026-adrenalyn','axl-premium-gold','Premium Gold Limited','LIMITED','LIMITED',1130,null,'Lionel Messi','ARG','PREMIUM_GOLD',null),
('AXLPG4','wc2026-adrenalyn','axl-premium-gold','Premium Gold Limited','LIMITED','LIMITED',1131,null,'Marcus Rashford','ENG','PREMIUM_GOLD',null),
('AXLPG5','wc2026-adrenalyn','axl-premium-gold','Premium Gold Limited','LIMITED','LIMITED',1132,null,'Memphis Depay','NED','PREMIUM_GOLD',null),
('AXLPG6','wc2026-adrenalyn','axl-premium-gold','Premium Gold Limited','LIMITED','LIMITED',1133,null,'Mike Maignan','FRA','PREMIUM_GOLD',null),
('AXLXL1','wc2026-adrenalyn','axl-xxl','XXL Limited','LIMITED','LIMITED',1134,null,'Achraf Hakimi','MAR','XXL',null),
('AXLXL2','wc2026-adrenalyn','axl-xxl','XXL Limited','LIMITED','LIMITED',1135,null,'Antonio Nusa','NOR','XXL',null),
('AXLXL3','wc2026-adrenalyn','axl-xxl','XXL Limited','LIMITED','LIMITED',1136,null,'Christian Pulisic','USA','XXL',null),
('AXLXL4','wc2026-adrenalyn','axl-xxl','XXL Limited','LIMITED','LIMITED',1137,null,'Cole Palmer','ENG','XXL',null),
('AXLXL5','wc2026-adrenalyn','axl-xxl','XXL Limited','LIMITED','LIMITED',1138,null,'Cristiano Ronaldo','POR','XXL',null),
('AXLXL6','wc2026-adrenalyn','axl-xxl','XXL Limited','LIMITED','LIMITED',1139,null,'Désiré Doué','FRA','XXL',null),
('AXLXL7','wc2026-adrenalyn','axl-xxl','XXL Limited','LIMITED','LIMITED',1140,null,'Erling Haaland','NOR','XXL',null),
('AXLXL8','wc2026-adrenalyn','axl-xxl','XXL Limited','LIMITED','LIMITED',1141,null,'Estêvão','BRA','XXL',null),
('AXLXL9','wc2026-adrenalyn','axl-xxl','XXL Limited','LIMITED','LIMITED',1142,null,'Florian Wirtz','GER','XXL',null),
('AXLXL10','wc2026-adrenalyn','axl-xxl','XXL Limited','LIMITED','LIMITED',1143,null,'Gilberto Mora','MEX','XXL',null),
('AXLXL11','wc2026-adrenalyn','axl-xxl','XXL Limited','LIMITED','LIMITED',1144,null,'Harry Kane','ENG','XXL',null),
('AXLXL12','wc2026-adrenalyn','axl-xxl','XXL Limited','LIMITED','LIMITED',1145,null,'Jamal Musiala','GER','XXL',null),
('AXLXL13','wc2026-adrenalyn','axl-xxl','XXL Limited','LIMITED','LIMITED',1146,null,'Jérémy Doku','BEL','XXL',null),
('AXLXL14','wc2026-adrenalyn','axl-xxl','XXL Limited','LIMITED','LIMITED',1147,null,'João Neves','POR','XXL',null),
('AXLXL15','wc2026-adrenalyn','axl-xxl','XXL Limited','LIMITED','LIMITED',1148,null,'Jonathan David','CAN','XXL',null),
('AXLXL16','wc2026-adrenalyn','axl-xxl','XXL Limited','LIMITED','LIMITED',1149,null,'Joško Gvardiol','CRO','XXL',null),
('AXLXL17','wc2026-adrenalyn','axl-xxl','XXL Limited','LIMITED','LIMITED',1150,null,'Jude Bellingham','ENG','XXL',null),
('AXLXL18','wc2026-adrenalyn','axl-xxl','XXL Limited','LIMITED','LIMITED',1151,null,'Julián Alvarez','ARG','XXL',null),
('AXLXL19','wc2026-adrenalyn','axl-xxl','XXL Limited','LIMITED','LIMITED',1152,null,'Kevin De Bruyne','BEL','XXL',null),
('AXLXL20','wc2026-adrenalyn','axl-xxl','XXL Limited','LIMITED','LIMITED',1153,null,'Kylian Mbappé','FRA','XXL',null),
('AXLXL21','wc2026-adrenalyn','axl-xxl','XXL Limited','LIMITED','LIMITED',1154,null,'Lamine Yamal','ESP','XXL',null),
('AXLXL22','wc2026-adrenalyn','axl-xxl','XXL Limited','LIMITED','LIMITED',1155,null,'Lionel Messi','ARG','XXL',null),
('AXLXL23','wc2026-adrenalyn','axl-xxl','XXL Limited','LIMITED','LIMITED',1156,null,'Luis Díaz','COL','XXL',null),
('AXLXL24','wc2026-adrenalyn','axl-xxl','XXL Limited','LIMITED','LIMITED',1157,null,'Luka Modrić','CRO','XXL',null),
('AXLXL25','wc2026-adrenalyn','axl-xxl','XXL Limited','LIMITED','LIMITED',1158,null,'Marquinhos','BRA','XXL',null),
('AXLXL26','wc2026-adrenalyn','axl-xxl','XXL Limited','LIMITED','LIMITED',1159,null,'Mohamed Salah','EGY','XXL',null),
('AXLXL27','wc2026-adrenalyn','axl-xxl','XXL Limited','LIMITED','LIMITED',1160,null,'Nico Paz','ARG','XXL',null),
('AXLXL28','wc2026-adrenalyn','axl-xxl','XXL Limited','LIMITED','LIMITED',1161,null,'Ousmane Dembélé','FRA','XXL',null),
('AXLXL29','wc2026-adrenalyn','axl-xxl','XXL Limited','LIMITED','LIMITED',1162,null,'Pau Cubarsí','ESP','XXL',null),
('AXLXL30','wc2026-adrenalyn','axl-xxl','XXL Limited','LIMITED','LIMITED',1163,null,'Pedri','ESP','XXL',null),
('AXLXL31','wc2026-adrenalyn','axl-xxl','XXL Limited','LIMITED','LIMITED',1164,null,'Rafael Leão','POR','XXL',null),
('AXLXL32','wc2026-adrenalyn','axl-xxl','XXL Limited','LIMITED','LIMITED',1165,null,'Heungmin Son','KOR','XXL',null),
('AXLXL33','wc2026-adrenalyn','axl-xxl','XXL Limited','LIMITED','LIMITED',1166,null,'Takefusa Kubo','JPN','XXL',null),
('AXLXL34','wc2026-adrenalyn','axl-xxl','XXL Limited','LIMITED','LIMITED',1167,null,'Vinícius Júnior','BRA','XXL',null),
('AXLXL35','wc2026-adrenalyn','axl-xxl','XXL Limited','LIMITED','LIMITED',1168,null,'Virgil van Dijk','NED','XXL',null),
('AXLXL36','wc2026-adrenalyn','axl-xxl','XXL Limited','LIMITED','LIMITED',1169,null,'Xavi Simons','NED','XXL',null),
('AXLXH1','wc2026-adrenalyn','axl-xxl-holo','XXL Holo Limited','LIMITED','LIMITED',1170,null,'Achraf Hakimi','MAR','XXL_HOLO',null),
('AXLXH2','wc2026-adrenalyn','axl-xxl-holo','XXL Holo Limited','LIMITED','LIMITED',1171,null,'Christian Pulisic','USA','XXL_HOLO',null),
('AXLXH3','wc2026-adrenalyn','axl-xxl-holo','XXL Holo Limited','LIMITED','LIMITED',1172,null,'Cristiano Ronaldo','POR','XXL_HOLO',null),
('AXLXH4','wc2026-adrenalyn','axl-xxl-holo','XXL Holo Limited','LIMITED','LIMITED',1173,null,'Erling Haaland','NOR','XXL_HOLO',null),
('AXLXH5','wc2026-adrenalyn','axl-xxl-holo','XXL Holo Limited','LIMITED','LIMITED',1174,null,'Harry Kane','ENG','XXL_HOLO',null),
('AXLXH6','wc2026-adrenalyn','axl-xxl-holo','XXL Holo Limited','LIMITED','LIMITED',1175,null,'Heungmin Son','KOR','XXL_HOLO',null),
('AXLXH7','wc2026-adrenalyn','axl-xxl-holo','XXL Holo Limited','LIMITED','LIMITED',1176,null,'Jamal Musiala','GER','XXL_HOLO',null),
('AXLXH8','wc2026-adrenalyn','axl-xxl-holo','XXL Holo Limited','LIMITED','LIMITED',1177,null,'Jérémy Doku','BEL','XXL_HOLO',null),
('AXLXH9','wc2026-adrenalyn','axl-xxl-holo','XXL Holo Limited','LIMITED','LIMITED',1178,null,'Jonathan David','CAN','XXL_HOLO',null),
('AXLXH10','wc2026-adrenalyn','axl-xxl-holo','XXL Holo Limited','LIMITED','LIMITED',1179,null,'Kylian Mbappé','FRA','XXL_HOLO',null),
('AXLXH11','wc2026-adrenalyn','axl-xxl-holo','XXL Holo Limited','LIMITED','LIMITED',1180,null,'Lamine Yamal','ESP','XXL_HOLO',null),
('AXLXH12','wc2026-adrenalyn','axl-xxl-holo','XXL Holo Limited','LIMITED','LIMITED',1181,null,'Lionel Messi','ARG','XXL_HOLO',null),
('AXLXH13','wc2026-adrenalyn','axl-xxl-holo','XXL Holo Limited','LIMITED','LIMITED',1182,null,'Luis Díaz','COL','XXL_HOLO',null),
('AXLXH14','wc2026-adrenalyn','axl-xxl-holo','XXL Holo Limited','LIMITED','LIMITED',1183,null,'Luka Modrić','CRO','XXL_HOLO',null),
('AXLXH15','wc2026-adrenalyn','axl-xxl-holo','XXL Holo Limited','LIMITED','LIMITED',1184,null,'Mohamed Salah','EGY','XXL_HOLO',null),
('AXLXH16','wc2026-adrenalyn','axl-xxl-holo','XXL Holo Limited','LIMITED','LIMITED',1185,null,'Ousmane Dembélé','FRA','XXL_HOLO',null),
('AXLXH17','wc2026-adrenalyn','axl-xxl-holo','XXL Holo Limited','LIMITED','LIMITED',1186,null,'Vinícius Júnior','BRA','XXL_HOLO',null),
('AXLXH18','wc2026-adrenalyn','axl-xxl-holo','XXL Holo Limited','LIMITED','LIMITED',1187,null,'Virgil van Dijk','NED','XXL_HOLO',null)
on conflict (code) do update
  set album_id = excluded.album_id, block_id = excluded.block_id, block_name = excluded.block_name,
      block_type = excluded.block_type, group_key = excluded.group_key, position = excluded.position,
      number = excluded.number, name = excluded.name, team_code = excluded.team_code,
      card_type = excluded.card_type, player_position = excluded.player_position;
