-- Migração: várias coleções (Fase 1 — só banco, aditiva). Rode depois de todas as anteriores. Idempotente.
--
-- Ideia central: o código de cada item continua único na plataforma inteira. O Álbum Copa mantém
-- os códigos de hoje (BRA1, FWC3, LIL1…) e a Adrenalyn XL usa AXL1–AXL630. Por isso collection,
-- sticker_prices, pedidos e carrinhos seguem funcionando sem trocar chaves.
--
-- Nada é apagado nem renomeado: o app em produção continua lendo o que lê hoje.
--   • albums: ganha slug, nome do item (figurinha/card) e total. Entra a "Adrenalyn XL" INATIVA
--     (não aparece no cadastro até a Fase 2).
--   • stickers: aceita os tipos de bloco da Adrenalyn e ganha número, nome, seleção, tipo de card e
--     posição. Recebe os 630 cards (fonte: data/adrenalyn-xl.csv).
--   • user_albums (nova): coleções que cada pessoa acompanha, com nome próprio. Todos os usuários
--     atuais entram no Álbum Copa com o nome que já usam; contas novas entram por trigger.
--   • shop_albums (nova): configuração da loja por coleção (ativa, pedido mínimo, preços por grupo).
--     Copiada de shops para o Álbum Copa. Até a Fase 3 o app ainda usa as colunas de shops — a
--     migração da Fase 3 recopia os valores antes de trocar.
--   • orders, cart_holds, collection_shares: ganham album_id (padrão: Álbum Copa).

-- ---------- albums ----------
alter table public.albums add column if not exists slug          text;
alter table public.albums add column if not exists item_singular text not null default 'figurinha';
alter table public.albums add column if not exists item_plural   text not null default 'figurinhas';
alter table public.albums add column if not exists total_items   int;

update public.albums
   set name = 'Álbum Copa do Mundo 2026', slug = 'copa-2026', total_items = 994
 where id = 'wc2026-panini';

insert into public.albums (id, name, slug, item_singular, item_plural, total_items, active, position)
values ('wc2026-adrenalyn', 'Adrenalyn XL', 'adrenalyn-xl', 'card', 'cards', 630, false, 2)
on conflict (id) do update
  set name = excluded.name, slug = excluded.slug, item_singular = excluded.item_singular,
      item_plural = excluded.item_plural, total_items = excluded.total_items;

create unique index if not exists albums_slug_key on public.albums(slug);

-- ---------- stickers ----------
alter table public.stickers drop constraint if exists stickers_block_type_check;
alter table public.stickers
  add constraint stickers_block_type_check
  check (block_type in ('TEAM','FWC','CC','LEG','SPECIAL','CONTENDER'));

alter table public.stickers add column if not exists number          int;
alter table public.stickers add column if not exists name            text;
alter table public.stickers add column if not exists team_code       text;
alter table public.stickers add column if not exists card_type       text;
alter table public.stickers add column if not exists player_position text;

alter table public.stickers drop constraint if exists stickers_player_position_check;
alter table public.stickers
  add constraint stickers_player_position_check
  check (player_position is null or player_position in ('GK','DEF','MID','FWD'));

create index if not exists stickers_album_idx on public.stickers(album_id, position);

insert into public.stickers
  (code, album_id, block_id, block_name, block_type, group_key, position, number, name, team_code, card_type, player_position)
values
('AXL1','wc2026-adrenalyn','axl-golden-ballers','Golden Ballers','SPECIAL','GOLDEN_BALLERS',1,1,'Messi (ARG)','ARG','GOLDEN_BALLER','FWD'),
('AXL2','wc2026-adrenalyn','axl-golden-ballers','Golden Ballers','SPECIAL','GOLDEN_BALLERS',2,2,'Vinícius Júnior (BRA)','BRA','GOLDEN_BALLER','FWD'),
('AXL3','wc2026-adrenalyn','axl-golden-ballers','Golden Ballers','SPECIAL','GOLDEN_BALLERS',3,3,'Salah (EGY)','EGY','GOLDEN_BALLER','FWD'),
('AXL4','wc2026-adrenalyn','axl-golden-ballers','Golden Ballers','SPECIAL','GOLDEN_BALLERS',4,4,'Kane (ENG)','ENG','GOLDEN_BALLER','FWD'),
('AXL5','wc2026-adrenalyn','axl-golden-ballers','Golden Ballers','SPECIAL','GOLDEN_BALLERS',5,5,'Mbappé (FRA)','FRA','GOLDEN_BALLER','FWD'),
('AXL6','wc2026-adrenalyn','axl-golden-ballers','Golden Ballers','SPECIAL','GOLDEN_BALLERS',6,6,'Son (KOR)','KOR','GOLDEN_BALLER','FWD'),
('AXL7','wc2026-adrenalyn','axl-golden-ballers','Golden Ballers','SPECIAL','GOLDEN_BALLERS',7,7,'Haaland (NOR)','NOR','GOLDEN_BALLER','FWD'),
('AXL8','wc2026-adrenalyn','axl-golden-ballers','Golden Ballers','SPECIAL','GOLDEN_BALLERS',8,8,'Ronaldo (POR)','POR','GOLDEN_BALLER','FWD'),
('AXL9','wc2026-adrenalyn','axl-golden-ballers','Golden Ballers','SPECIAL','GOLDEN_BALLERS',9,9,'Yamal (ESP)','ESP','GOLDEN_BALLER','FWD'),
('AXL10','wc2026-adrenalyn','axl-ALG','Argélia','TEAM','SELECOES',10,10,'Rayan Aït-Nouri','ALG','FAN_FAVOURITE','DEF'),
('AXL11','wc2026-adrenalyn','axl-ALG','Argélia','TEAM','SELECOES',11,11,'Escudo','ALG','CREST',null),
('AXL12','wc2026-adrenalyn','axl-ALG','Argélia','TEAM','SELECOES',12,12,'Riyad Mahrez','ALG','ICON','FWD'),
('AXL13','wc2026-adrenalyn','axl-ALG','Argélia','TEAM','SELECOES',13,13,'Alexis Guendouz','ALG','BASE','GK'),
('AXL14','wc2026-adrenalyn','axl-ALG','Argélia','TEAM','SELECOES',14,14,'Ramy Bensebaini','ALG','BASE','DEF'),
('AXL15','wc2026-adrenalyn','axl-ALG','Argélia','TEAM','SELECOES',15,15,'Youcef Atal','ALG','BASE','DEF'),
('AXL16','wc2026-adrenalyn','axl-ALG','Argélia','TEAM','SELECOES',16,16,'Aïssa Mandi','ALG','BASE','DEF'),
('AXL17','wc2026-adrenalyn','axl-ALG','Argélia','TEAM','SELECOES',17,17,'Nabil Bentaleb','ALG','BASE','MID'),
('AXL18','wc2026-adrenalyn','axl-ALG','Argélia','TEAM','SELECOES',18,18,'Saïd Benrahma','ALG','BASE','FWD'),
('AXL19','wc2026-adrenalyn','axl-ALG','Argélia','TEAM','SELECOES',19,19,'Amine Gouiri','ALG','BASE','FWD'),
('AXL20','wc2026-adrenalyn','axl-ALG','Argélia','TEAM','SELECOES',20,20,'Mohamed Amoura','ALG','BASE','FWD'),
('AXL21','wc2026-adrenalyn','axl-ALG','Argélia','TEAM','SELECOES',21,21,'Baghdad Bounedjah','ALG','BASE','FWD'),
('AXL22','wc2026-adrenalyn','axl-ARG','Argentina','TEAM','SELECOES',22,22,'Julián Alvarez','ARG','FAN_FAVOURITE','FWD'),
('AXL23','wc2026-adrenalyn','axl-ARG','Argentina','TEAM','SELECOES',23,23,'Escudo','ARG','CREST',null),
('AXL24','wc2026-adrenalyn','axl-ARG','Argentina','TEAM','SELECOES',24,24,'Lionel Messi','ARG','ICON','FWD'),
('AXL25','wc2026-adrenalyn','axl-ARG','Argentina','TEAM','SELECOES',25,25,'Emiliano Martínez','ARG','BASE','GK'),
('AXL26','wc2026-adrenalyn','axl-ARG','Argentina','TEAM','SELECOES',26,26,'Nahuel Molina','ARG','BASE','DEF'),
('AXL27','wc2026-adrenalyn','axl-ARG','Argentina','TEAM','SELECOES',27,27,'Cristian Romero','ARG','BASE','DEF'),
('AXL28','wc2026-adrenalyn','axl-ARG','Argentina','TEAM','SELECOES',28,28,'Nicolás Otamendi','ARG','BASE','DEF'),
('AXL29','wc2026-adrenalyn','axl-ARG','Argentina','TEAM','SELECOES',29,29,'Enzo Fernández','ARG','BASE','MID'),
('AXL30','wc2026-adrenalyn','axl-ARG','Argentina','TEAM','SELECOES',30,30,'Alexis Mac Allister','ARG','BASE','MID'),
('AXL31','wc2026-adrenalyn','axl-ARG','Argentina','TEAM','SELECOES',31,31,'Rodrigo De Paul','ARG','BASE','MID'),
('AXL32','wc2026-adrenalyn','axl-ARG','Argentina','TEAM','SELECOES',32,32,'Giuliano Simeone','ARG','BASE','FWD'),
('AXL33','wc2026-adrenalyn','axl-ARG','Argentina','TEAM','SELECOES',33,33,'Lautaro Martínez','ARG','BASE','FWD'),
('AXL34','wc2026-adrenalyn','axl-AUS','Austrália','TEAM','SELECOES',34,34,'Harry Souttar','AUS','FAN_FAVOURITE','DEF'),
('AXL35','wc2026-adrenalyn','axl-AUS','Austrália','TEAM','SELECOES',35,35,'Escudo','AUS','CREST',null),
('AXL36','wc2026-adrenalyn','axl-AUS','Austrália','TEAM','SELECOES',36,36,'Mathew Ryan','AUS','ICON','GK'),
('AXL37','wc2026-adrenalyn','axl-AUS','Austrália','TEAM','SELECOES',37,37,'Alessandro Circati','AUS','BASE','DEF'),
('AXL38','wc2026-adrenalyn','axl-AUS','Austrália','TEAM','SELECOES',38,38,'Jordan Bos','AUS','BASE','DEF'),
('AXL39','wc2026-adrenalyn','axl-AUS','Austrália','TEAM','SELECOES',39,39,'Lewis Miller','AUS','BASE','DEF'),
('AXL40','wc2026-adrenalyn','axl-AUS','Austrália','TEAM','SELECOES',40,40,'Milos Degenek','AUS','BASE','DEF'),
('AXL41','wc2026-adrenalyn','axl-AUS','Austrália','TEAM','SELECOES',41,41,'Jackson Irvine','AUS','BASE','MID'),
('AXL42','wc2026-adrenalyn','axl-AUS','Austrália','TEAM','SELECOES',42,42,'Riley McGree','AUS','BASE','MID'),
('AXL43','wc2026-adrenalyn','axl-AUS','Austrália','TEAM','SELECOES',43,43,'Aiden O''Neill','AUS','BASE','MID'),
('AXL44','wc2026-adrenalyn','axl-AUS','Austrália','TEAM','SELECOES',44,44,'Connor Metcalfe','AUS','BASE','MID'),
('AXL45','wc2026-adrenalyn','axl-AUS','Austrália','TEAM','SELECOES',45,45,'Craig Goodwin','AUS','BASE','FWD'),
('AXL46','wc2026-adrenalyn','axl-AUT','Áustria','TEAM','SELECOES',46,46,'Marko Arnautović','AUT','FAN_FAVOURITE','FWD'),
('AXL47','wc2026-adrenalyn','axl-AUT','Áustria','TEAM','SELECOES',47,47,'Escudo','AUT','CREST',null),
('AXL48','wc2026-adrenalyn','axl-AUT','Áustria','TEAM','SELECOES',48,48,'David Alaba','AUT','ICON','DEF'),
('AXL49','wc2026-adrenalyn','axl-AUT','Áustria','TEAM','SELECOES',49,49,'Alexander Schlager','AUT','BASE','GK'),
('AXL50','wc2026-adrenalyn','axl-AUT','Áustria','TEAM','SELECOES',50,50,'Kevin Danso','AUT','BASE','DEF'),
('AXL51','wc2026-adrenalyn','axl-AUT','Áustria','TEAM','SELECOES',51,51,'Philipp Lienhart','AUT','BASE','DEF'),
('AXL52','wc2026-adrenalyn','axl-AUT','Áustria','TEAM','SELECOES',52,52,'Konrad Laimer','AUT','BASE','MID'),
('AXL53','wc2026-adrenalyn','axl-AUT','Áustria','TEAM','SELECOES',53,53,'Nicolas Seiwald','AUT','BASE','MID'),
('AXL54','wc2026-adrenalyn','axl-AUT','Áustria','TEAM','SELECOES',54,54,'Marcel Sabitzer','AUT','BASE','MID'),
('AXL55','wc2026-adrenalyn','axl-AUT','Áustria','TEAM','SELECOES',55,55,'Florian Grillitsch','AUT','BASE','MID'),
('AXL56','wc2026-adrenalyn','axl-AUT','Áustria','TEAM','SELECOES',56,56,'Christoph Baumgartner','AUT','BASE','FWD'),
('AXL57','wc2026-adrenalyn','axl-AUT','Áustria','TEAM','SELECOES',57,57,'Michael Gregoritsch','AUT','BASE','FWD'),
('AXL58','wc2026-adrenalyn','axl-BEL','Bélgica','TEAM','SELECOES',58,58,'Youri Tielemans','BEL','FAN_FAVOURITE','MID'),
('AXL59','wc2026-adrenalyn','axl-BEL','Bélgica','TEAM','SELECOES',59,59,'Escudo','BEL','CREST',null),
('AXL60','wc2026-adrenalyn','axl-BEL','Bélgica','TEAM','SELECOES',60,60,'Kevin De Bruyne','BEL','ICON','MID'),
('AXL61','wc2026-adrenalyn','axl-BEL','Bélgica','TEAM','SELECOES',61,61,'Thibaut Courtois','BEL','BASE','GK'),
('AXL62','wc2026-adrenalyn','axl-BEL','Bélgica','TEAM','SELECOES',62,62,'Arthur Theate','BEL','BASE','DEF'),
('AXL63','wc2026-adrenalyn','axl-BEL','Bélgica','TEAM','SELECOES',63,63,'Timothy Castagne','BEL','BASE','DEF'),
('AXL64','wc2026-adrenalyn','axl-BEL','Bélgica','TEAM','SELECOES',64,64,'Maxim De Cuyper','BEL','BASE','DEF'),
('AXL65','wc2026-adrenalyn','axl-BEL','Bélgica','TEAM','SELECOES',65,65,'Amadou Onana','BEL','BASE','MID'),
('AXL66','wc2026-adrenalyn','axl-BEL','Bélgica','TEAM','SELECOES',66,66,'Jérémy Doku','BEL','BASE','FWD'),
('AXL67','wc2026-adrenalyn','axl-BEL','Bélgica','TEAM','SELECOES',67,67,'Charles De Ketelaere','BEL','BASE','FWD'),
('AXL68','wc2026-adrenalyn','axl-BEL','Bélgica','TEAM','SELECOES',68,68,'Leandro Trossard','BEL','BASE','FWD'),
('AXL69','wc2026-adrenalyn','axl-BEL','Bélgica','TEAM','SELECOES',69,69,'Romelu Lukaku','BEL','BASE','FWD'),
('AXL70','wc2026-adrenalyn','axl-BRA','Brasil','TEAM','SELECOES',70,70,'Marquinhos','BRA','FAN_FAVOURITE','DEF'),
('AXL71','wc2026-adrenalyn','axl-BRA','Brasil','TEAM','SELECOES',71,71,'Escudo','BRA','CREST',null),
('AXL72','wc2026-adrenalyn','axl-BRA','Brasil','TEAM','SELECOES',72,72,'Vinícius Júnior','BRA','ICON','FWD'),
('AXL73','wc2026-adrenalyn','axl-BRA','Brasil','TEAM','SELECOES',73,73,'Alisson','BRA','BASE','GK'),
('AXL74','wc2026-adrenalyn','axl-BRA','Brasil','TEAM','SELECOES',74,74,'Danilo','BRA','BASE','DEF'),
('AXL75','wc2026-adrenalyn','axl-BRA','Brasil','TEAM','SELECOES',75,75,'Éder Militão','BRA','BASE','DEF'),
('AXL76','wc2026-adrenalyn','axl-BRA','Brasil','TEAM','SELECOES',76,76,'Gabriel Magalhães','BRA','BASE','DEF'),
('AXL77','wc2026-adrenalyn','axl-BRA','Brasil','TEAM','SELECOES',77,77,'Casemiro','BRA','BASE','MID'),
('AXL78','wc2026-adrenalyn','axl-BRA','Brasil','TEAM','SELECOES',78,78,'Bruno Guimarães','BRA','BASE','MID'),
('AXL79','wc2026-adrenalyn','axl-BRA','Brasil','TEAM','SELECOES',79,79,'Rodrygo','BRA','BASE','FWD'),
('AXL80','wc2026-adrenalyn','axl-BRA','Brasil','TEAM','SELECOES',80,80,'Matheus Cunha','BRA','BASE','FWD'),
('AXL81','wc2026-adrenalyn','axl-BRA','Brasil','TEAM','SELECOES',81,81,'Raphinha','BRA','BASE','FWD'),
('AXL82','wc2026-adrenalyn','axl-CAN','Canadá','TEAM','SELECOES',82,82,'Jonathan David','CAN','FAN_FAVOURITE','FWD'),
('AXL83','wc2026-adrenalyn','axl-CAN','Canadá','TEAM','SELECOES',83,83,'Escudo','CAN','CREST',null),
('AXL84','wc2026-adrenalyn','axl-CAN','Canadá','TEAM','SELECOES',84,84,'Alphonso Davies','CAN','ICON','DEF'),
('AXL85','wc2026-adrenalyn','axl-CAN','Canadá','TEAM','SELECOES',85,85,'Dayne St. Clair','CAN','BASE','GK'),
('AXL86','wc2026-adrenalyn','axl-CAN','Canadá','TEAM','SELECOES',86,86,'Richie Laryea','CAN','BASE','DEF'),
('AXL87','wc2026-adrenalyn','axl-CAN','Canadá','TEAM','SELECOES',87,87,'Derek Cornelius','CAN','BASE','DEF'),
('AXL88','wc2026-adrenalyn','axl-CAN','Canadá','TEAM','SELECOES',88,88,'Stephen Eustáquio','CAN','BASE','MID'),
('AXL89','wc2026-adrenalyn','axl-CAN','Canadá','TEAM','SELECOES',89,89,'Ismaël Koné','CAN','BASE','MID'),
('AXL90','wc2026-adrenalyn','axl-CAN','Canadá','TEAM','SELECOES',90,90,'Jonathan Osorio','CAN','BASE','MID'),
('AXL91','wc2026-adrenalyn','axl-CAN','Canadá','TEAM','SELECOES',91,91,'Jacob Shaffelburg','CAN','BASE','MID'),
('AXL92','wc2026-adrenalyn','axl-CAN','Canadá','TEAM','SELECOES',92,92,'Tajon Buchanan','CAN','BASE','MID'),
('AXL93','wc2026-adrenalyn','axl-CAN','Canadá','TEAM','SELECOES',93,93,'Cyle Larin','CAN','BASE','FWD'),
('AXL94','wc2026-adrenalyn','axl-CPV','Cabo Verde','TEAM','SELECOES',94,94,'Vozinha','CPV','FAN_FAVOURITE','GK'),
('AXL95','wc2026-adrenalyn','axl-CPV','Cabo Verde','TEAM','SELECOES',95,95,'Escudo','CPV','CREST',null),
('AXL96','wc2026-adrenalyn','axl-CPV','Cabo Verde','TEAM','SELECOES',96,96,'Ryan Mendes','CPV','ICON','FWD'),
('AXL97','wc2026-adrenalyn','axl-CPV','Cabo Verde','TEAM','SELECOES',97,97,'Logan Costa','CPV','BASE','DEF'),
('AXL98','wc2026-adrenalyn','axl-CPV','Cabo Verde','TEAM','SELECOES',98,98,'Pico','CPV','BASE','DEF'),
('AXL99','wc2026-adrenalyn','axl-CPV','Cabo Verde','TEAM','SELECOES',99,99,'Steven Moreira','CPV','BASE','DEF'),
('AXL100','wc2026-adrenalyn','axl-CPV','Cabo Verde','TEAM','SELECOES',100,100,'João Paulo','CPV','BASE','DEF'),
('AXL101','wc2026-adrenalyn','axl-CPV','Cabo Verde','TEAM','SELECOES',101,101,'Kevin Pina','CPV','BASE','MID'),
('AXL102','wc2026-adrenalyn','axl-CPV','Cabo Verde','TEAM','SELECOES',102,102,'Jamiro Monteiro','CPV','BASE','MID'),
('AXL103','wc2026-adrenalyn','axl-CPV','Cabo Verde','TEAM','SELECOES',103,103,'Yannick Semedo','CPV','BASE','MID'),
('AXL104','wc2026-adrenalyn','axl-CPV','Cabo Verde','TEAM','SELECOES',104,104,'Jovane Cabral','CPV','BASE','FWD'),
('AXL105','wc2026-adrenalyn','axl-CPV','Cabo Verde','TEAM','SELECOES',105,105,'Dailon Livramento','CPV','BASE','FWD'),
('AXL106','wc2026-adrenalyn','axl-COL','Colômbia','TEAM','SELECOES',106,106,'Luis Díaz','COL','FAN_FAVOURITE','FWD'),
('AXL107','wc2026-adrenalyn','axl-COL','Colômbia','TEAM','SELECOES',107,107,'Escudo','COL','CREST',null),
('AXL108','wc2026-adrenalyn','axl-COL','Colômbia','TEAM','SELECOES',108,108,'James Rodríguez','COL','ICON','MID'),
('AXL109','wc2026-adrenalyn','axl-COL','Colômbia','TEAM','SELECOES',109,109,'Camilo Vargas','COL','BASE','GK'),
('AXL110','wc2026-adrenalyn','axl-COL','Colômbia','TEAM','SELECOES',110,110,'Dávinson Sánchez','COL','BASE','DEF'),
('AXL111','wc2026-adrenalyn','axl-COL','Colômbia','TEAM','SELECOES',111,111,'Yerry Mina','COL','BASE','DEF'),
('AXL112','wc2026-adrenalyn','axl-COL','Colômbia','TEAM','SELECOES',112,112,'Daniel Muñoz','COL','BASE','DEF'),
('AXL113','wc2026-adrenalyn','axl-COL','Colômbia','TEAM','SELECOES',113,113,'Jefferson Lerma','COL','BASE','MID'),
('AXL114','wc2026-adrenalyn','axl-COL','Colômbia','TEAM','SELECOES',114,114,'Richard Ríos','COL','BASE','MID'),
('AXL115','wc2026-adrenalyn','axl-COL','Colômbia','TEAM','SELECOES',115,115,'Juan Fernando Quintero','COL','BASE','MID'),
('AXL116','wc2026-adrenalyn','axl-COL','Colômbia','TEAM','SELECOES',116,116,'Jhon Arias','COL','BASE','FWD'),
('AXL117','wc2026-adrenalyn','axl-COL','Colômbia','TEAM','SELECOES',117,117,'Luis Suárez','COL','BASE','FWD'),
('AXL118','wc2026-adrenalyn','axl-CRO','Croácia','TEAM','SELECOES',118,118,'Ivan Perišić','CRO','FAN_FAVOURITE','MID'),
('AXL119','wc2026-adrenalyn','axl-CRO','Croácia','TEAM','SELECOES',119,119,'Escudo','CRO','CREST',null),
('AXL120','wc2026-adrenalyn','axl-CRO','Croácia','TEAM','SELECOES',120,120,'Luka Modrić','CRO','ICON','MID'),
('AXL121','wc2026-adrenalyn','axl-CRO','Croácia','TEAM','SELECOES',121,121,'Dominik Livaković','CRO','BASE','GK'),
('AXL122','wc2026-adrenalyn','axl-CRO','Croácia','TEAM','SELECOES',122,122,'Duje Ćaleta-Car','CRO','BASE','DEF'),
('AXL123','wc2026-adrenalyn','axl-CRO','Croácia','TEAM','SELECOES',123,123,'Joško Gvardiol','CRO','BASE','DEF'),
('AXL124','wc2026-adrenalyn','axl-CRO','Croácia','TEAM','SELECOES',124,124,'Josip Stanišić','CRO','BASE','DEF'),
('AXL125','wc2026-adrenalyn','axl-CRO','Croácia','TEAM','SELECOES',125,125,'Mateo Kovačić','CRO','BASE','MID'),
('AXL126','wc2026-adrenalyn','axl-CRO','Croácia','TEAM','SELECOES',126,126,'Lovro Majer','CRO','BASE','MID'),
('AXL127','wc2026-adrenalyn','axl-CRO','Croácia','TEAM','SELECOES',127,127,'Mario Pašalić','CRO','BASE','MID'),
('AXL128','wc2026-adrenalyn','axl-CRO','Croácia','TEAM','SELECOES',128,128,'Ante Budimir','CRO','BASE','FWD'),
('AXL129','wc2026-adrenalyn','axl-CRO','Croácia','TEAM','SELECOES',129,129,'Andrej Kramarić','CRO','BASE','FWD'),
('AXL130','wc2026-adrenalyn','axl-CUW','Curaçao','TEAM','SELECOES',130,130,'Juriën Gaari','CUW','FAN_FAVOURITE','DEF'),
('AXL131','wc2026-adrenalyn','axl-CUW','Curaçao','TEAM','SELECOES',131,131,'Escudo','CUW','CREST',null),
('AXL132','wc2026-adrenalyn','axl-CUW','Curaçao','TEAM','SELECOES',132,132,'Leandro Bacuna','CUW','ICON','MID'),
('AXL133','wc2026-adrenalyn','axl-CUW','Curaçao','TEAM','SELECOES',133,133,'Eloy Room','CUW','BASE','GK'),
('AXL134','wc2026-adrenalyn','axl-CUW','Curaçao','TEAM','SELECOES',134,134,'Sherel Floranus','CUW','BASE','DEF'),
('AXL135','wc2026-adrenalyn','axl-CUW','Curaçao','TEAM','SELECOES',135,135,'Roshon van Eijma','CUW','BASE','DEF'),
('AXL136','wc2026-adrenalyn','axl-CUW','Curaçao','TEAM','SELECOES',136,136,'Armando Obispo','CUW','BASE','DEF'),
('AXL137','wc2026-adrenalyn','axl-CUW','Curaçao','TEAM','SELECOES',137,137,'Livano Comenencia','CUW','BASE','MID'),
('AXL138','wc2026-adrenalyn','axl-CUW','Curaçao','TEAM','SELECOES',138,138,'Juninho Bacuna','CUW','BASE','MID'),
('AXL139','wc2026-adrenalyn','axl-CUW','Curaçao','TEAM','SELECOES',139,139,'Kenji Gorré','CUW','BASE','MID'),
('AXL140','wc2026-adrenalyn','axl-CUW','Curaçao','TEAM','SELECOES',140,140,'Sontje Hansen','CUW','BASE','FWD'),
('AXL141','wc2026-adrenalyn','axl-CUW','Curaçao','TEAM','SELECOES',141,141,'Jearl Margaritha','CUW','BASE','FWD'),
('AXL142','wc2026-adrenalyn','axl-ECU','Equador','TEAM','SELECOES',142,142,'Moisés Caicedo','ECU','FAN_FAVOURITE','MID'),
('AXL143','wc2026-adrenalyn','axl-ECU','Equador','TEAM','SELECOES',143,143,'Escudo','ECU','CREST',null),
('AXL144','wc2026-adrenalyn','axl-ECU','Equador','TEAM','SELECOES',144,144,'Enner Valencia','ECU','ICON','FWD'),
('AXL145','wc2026-adrenalyn','axl-ECU','Equador','TEAM','SELECOES',145,145,'Hernán Galíndez','ECU','BASE','GK'),
('AXL146','wc2026-adrenalyn','axl-ECU','Equador','TEAM','SELECOES',146,146,'Piero Hincapié','ECU','BASE','DEF'),
('AXL147','wc2026-adrenalyn','axl-ECU','Equador','TEAM','SELECOES',147,147,'Pervis Estupiñán','ECU','BASE','DEF'),
('AXL148','wc2026-adrenalyn','axl-ECU','Equador','TEAM','SELECOES',148,148,'Willian Pacho','ECU','BASE','DEF'),
('AXL149','wc2026-adrenalyn','axl-ECU','Equador','TEAM','SELECOES',149,149,'Ángelo Preciado','ECU','BASE','DEF'),
('AXL150','wc2026-adrenalyn','axl-ECU','Equador','TEAM','SELECOES',150,150,'Joel Ordóñez','ECU','BASE','DEF'),
('AXL151','wc2026-adrenalyn','axl-ECU','Equador','TEAM','SELECOES',151,151,'Alan Franco','ECU','BASE','MID'),
('AXL152','wc2026-adrenalyn','axl-ECU','Equador','TEAM','SELECOES',152,152,'Gonzalo Plata','ECU','BASE','FWD'),
('AXL153','wc2026-adrenalyn','axl-ECU','Equador','TEAM','SELECOES',153,153,'Kevin Rodríguez','ECU','BASE','FWD'),
('AXL154','wc2026-adrenalyn','axl-EGY','Egito','TEAM','SELECOES',154,154,'Omar Marmoush','EGY','FAN_FAVOURITE','FWD'),
('AXL155','wc2026-adrenalyn','axl-EGY','Egito','TEAM','SELECOES',155,155,'Escudo','EGY','CREST',null),
('AXL156','wc2026-adrenalyn','axl-EGY','Egito','TEAM','SELECOES',156,156,'Mohamed Salah','EGY','ICON','FWD'),
('AXL157','wc2026-adrenalyn','axl-EGY','Egito','TEAM','SELECOES',157,157,'Mohamed El Shenawy','EGY','BASE','GK'),
('AXL158','wc2026-adrenalyn','axl-EGY','Egito','TEAM','SELECOES',158,158,'Mohamed Hany','EGY','BASE','DEF'),
('AXL159','wc2026-adrenalyn','axl-EGY','Egito','TEAM','SELECOES',159,159,'Mohamed Abdelmonem','EGY','BASE','DEF'),
('AXL160','wc2026-adrenalyn','axl-EGY','Egito','TEAM','SELECOES',160,160,'Ramy Rabia','EGY','BASE','DEF'),
('AXL161','wc2026-adrenalyn','axl-EGY','Egito','TEAM','SELECOES',161,161,'Marwan Attia','EGY','BASE','MID'),
('AXL162','wc2026-adrenalyn','axl-EGY','Egito','TEAM','SELECOES',162,162,'Zizo','EGY','BASE','MID'),
('AXL163','wc2026-adrenalyn','axl-EGY','Egito','TEAM','SELECOES',163,163,'Hamdy Fathy','EGY','BASE','MID'),
('AXL164','wc2026-adrenalyn','axl-EGY','Egito','TEAM','SELECOES',164,164,'Mostafa Mohamed','EGY','BASE','FWD'),
('AXL165','wc2026-adrenalyn','axl-EGY','Egito','TEAM','SELECOES',165,165,'Trézéguet','EGY','BASE','FWD'),
('AXL166','wc2026-adrenalyn','axl-ENG','Inglaterra','TEAM','SELECOES',166,166,'Jude Bellingham','ENG','FAN_FAVOURITE','MID'),
('AXL167','wc2026-adrenalyn','axl-ENG','Inglaterra','TEAM','SELECOES',167,167,'Escudo','ENG','CREST',null),
('AXL168','wc2026-adrenalyn','axl-ENG','Inglaterra','TEAM','SELECOES',168,168,'Harry Kane','ENG','ICON','FWD'),
('AXL169','wc2026-adrenalyn','axl-ENG','Inglaterra','TEAM','SELECOES',169,169,'Jordan Pickford','ENG','BASE','GK'),
('AXL170','wc2026-adrenalyn','axl-ENG','Inglaterra','TEAM','SELECOES',170,170,'Reece James','ENG','BASE','DEF'),
('AXL171','wc2026-adrenalyn','axl-ENG','Inglaterra','TEAM','SELECOES',171,171,'John Stones','ENG','BASE','DEF'),
('AXL172','wc2026-adrenalyn','axl-ENG','Inglaterra','TEAM','SELECOES',172,172,'Declan Rice','ENG','BASE','MID'),
('AXL173','wc2026-adrenalyn','axl-ENG','Inglaterra','TEAM','SELECOES',173,173,'Jordan Henderson','ENG','BASE','MID'),
('AXL174','wc2026-adrenalyn','axl-ENG','Inglaterra','TEAM','SELECOES',174,174,'Phil Foden','ENG','BASE','MID'),
('AXL175','wc2026-adrenalyn','axl-ENG','Inglaterra','TEAM','SELECOES',175,175,'Bukayo Saka','ENG','BASE','FWD'),
('AXL176','wc2026-adrenalyn','axl-ENG','Inglaterra','TEAM','SELECOES',176,176,'Cole Palmer','ENG','BASE','FWD'),
('AXL177','wc2026-adrenalyn','axl-ENG','Inglaterra','TEAM','SELECOES',177,177,'Marcus Rashford','ENG','BASE','FWD'),
('AXL178','wc2026-adrenalyn','axl-FRA','França','TEAM','SELECOES',178,178,'Ousmane Dembélé','FRA','FAN_FAVOURITE','FWD'),
('AXL179','wc2026-adrenalyn','axl-FRA','França','TEAM','SELECOES',179,179,'Escudo','FRA','CREST',null),
('AXL180','wc2026-adrenalyn','axl-FRA','França','TEAM','SELECOES',180,180,'Kylian Mbappé','FRA','ICON','FWD'),
('AXL181','wc2026-adrenalyn','axl-FRA','França','TEAM','SELECOES',181,181,'Mike Maignan','FRA','BASE','GK'),
('AXL182','wc2026-adrenalyn','axl-FRA','França','TEAM','SELECOES',182,182,'William Saliba','FRA','BASE','DEF'),
('AXL183','wc2026-adrenalyn','axl-FRA','França','TEAM','SELECOES',183,183,'Jules Koundé','FRA','BASE','DEF'),
('AXL184','wc2026-adrenalyn','axl-FRA','França','TEAM','SELECOES',184,184,'Théo Hernández','FRA','BASE','DEF'),
('AXL185','wc2026-adrenalyn','axl-FRA','França','TEAM','SELECOES',185,185,'Aurélien Tchouaméni','FRA','BASE','MID'),
('AXL186','wc2026-adrenalyn','axl-FRA','França','TEAM','SELECOES',186,186,'Eduardo Camavinga','FRA','BASE','MID'),
('AXL187','wc2026-adrenalyn','axl-FRA','França','TEAM','SELECOES',187,187,'Bradley Barcola','FRA','BASE','FWD'),
('AXL188','wc2026-adrenalyn','axl-FRA','França','TEAM','SELECOES',188,188,'Marcus Thuram','FRA','BASE','FWD'),
('AXL189','wc2026-adrenalyn','axl-FRA','França','TEAM','SELECOES',189,189,'Randal Kolo Muani','FRA','BASE','FWD'),
('AXL190','wc2026-adrenalyn','axl-GER','Alemanha','TEAM','SELECOES',190,190,'Jamal Musiala','GER','FAN_FAVOURITE','FWD'),
('AXL191','wc2026-adrenalyn','axl-GER','Alemanha','TEAM','SELECOES',191,191,'Escudo','GER','CREST',null),
('AXL192','wc2026-adrenalyn','axl-GER','Alemanha','TEAM','SELECOES',192,192,'Joshua Kimmich','GER','ICON','MID'),
('AXL193','wc2026-adrenalyn','axl-GER','Alemanha','TEAM','SELECOES',193,193,'Marc-André ter Stegen','GER','BASE','GK'),
('AXL194','wc2026-adrenalyn','axl-GER','Alemanha','TEAM','SELECOES',194,194,'Antonio Rüdiger','GER','BASE','DEF'),
('AXL195','wc2026-adrenalyn','axl-GER','Alemanha','TEAM','SELECOES',195,195,'Jonathan Tah','GER','BASE','DEF'),
('AXL196','wc2026-adrenalyn','axl-GER','Alemanha','TEAM','SELECOES',196,196,'Felix Nmecha','GER','BASE','MID'),
('AXL197','wc2026-adrenalyn','axl-GER','Alemanha','TEAM','SELECOES',197,197,'Leon Goretzka','GER','BASE','MID'),
('AXL198','wc2026-adrenalyn','axl-GER','Alemanha','TEAM','SELECOES',198,198,'Florian Wirtz','GER','BASE','MID'),
('AXL199','wc2026-adrenalyn','axl-GER','Alemanha','TEAM','SELECOES',199,199,'Serge Gnabry','GER','BASE','MID'),
('AXL200','wc2026-adrenalyn','axl-GER','Alemanha','TEAM','SELECOES',200,200,'Kai Havertz','GER','BASE','FWD'),
('AXL201','wc2026-adrenalyn','axl-GER','Alemanha','TEAM','SELECOES',201,201,'Leroy Sané','GER','BASE','FWD'),
('AXL202','wc2026-adrenalyn','axl-GHA','Gana','TEAM','SELECOES',202,202,'Thomas Partey','GHA','FAN_FAVOURITE','MID'),
('AXL203','wc2026-adrenalyn','axl-GHA','Gana','TEAM','SELECOES',203,203,'Escudo','GHA','CREST',null),
('AXL204','wc2026-adrenalyn','axl-GHA','Gana','TEAM','SELECOES',204,204,'Mohammed Kudus','GHA','ICON','FWD'),
('AXL205','wc2026-adrenalyn','axl-GHA','Gana','TEAM','SELECOES',205,205,'Lawrence Ati Zigi','GHA','BASE','GK'),
('AXL206','wc2026-adrenalyn','axl-GHA','Gana','TEAM','SELECOES',206,206,'Alidu Seidu','GHA','BASE','DEF'),
('AXL207','wc2026-adrenalyn','axl-GHA','Gana','TEAM','SELECOES',207,207,'Alexander Djiku','GHA','BASE','DEF'),
('AXL208','wc2026-adrenalyn','axl-GHA','Gana','TEAM','SELECOES',208,208,'Gideon Mensah','GHA','BASE','DEF'),
('AXL209','wc2026-adrenalyn','axl-GHA','Gana','TEAM','SELECOES',209,209,'Caleb Yirenkyi','GHA','BASE','DEF'),
('AXL210','wc2026-adrenalyn','axl-GHA','Gana','TEAM','SELECOES',210,210,'Abdul Issahaku Fatawu','GHA','BASE','MID'),
('AXL211','wc2026-adrenalyn','axl-GHA','Gana','TEAM','SELECOES',211,211,'Kamaldeen Sulemana','GHA','BASE','FWD'),
('AXL212','wc2026-adrenalyn','axl-GHA','Gana','TEAM','SELECOES',212,212,'Jordan Ayew','GHA','BASE','FWD'),
('AXL213','wc2026-adrenalyn','axl-GHA','Gana','TEAM','SELECOES',213,213,'Antoine Semenyo','GHA','BASE','FWD'),
('AXL214','wc2026-adrenalyn','axl-HAI','Haiti','TEAM','SELECOES',214,214,'Frantzdy Pierrot','HAI','FAN_FAVOURITE','FWD'),
('AXL215','wc2026-adrenalyn','axl-HAI','Haiti','TEAM','SELECOES',215,215,'Escudo','HAI','CREST',null),
('AXL216','wc2026-adrenalyn','axl-HAI','Haiti','TEAM','SELECOES',216,216,'Duckens Nazon','HAI','ICON','FWD'),
('AXL217','wc2026-adrenalyn','axl-HAI','Haiti','TEAM','SELECOES',217,217,'Johny Placide','HAI','BASE','GK'),
('AXL218','wc2026-adrenalyn','axl-HAI','Haiti','TEAM','SELECOES',218,218,'Ricardo Adé','HAI','BASE','DEF'),
('AXL219','wc2026-adrenalyn','axl-HAI','Haiti','TEAM','SELECOES',219,219,'Carlens Arcus','HAI','BASE','DEF'),
('AXL220','wc2026-adrenalyn','axl-HAI','Haiti','TEAM','SELECOES',220,220,'Hannes Delcroix','HAI','BASE','DEF'),
('AXL221','wc2026-adrenalyn','axl-HAI','Haiti','TEAM','SELECOES',221,221,'Leverton Pierre','HAI','BASE','MID'),
('AXL222','wc2026-adrenalyn','axl-HAI','Haiti','TEAM','SELECOES',222,222,'Danley Jean Jacques','HAI','BASE','MID'),
('AXL223','wc2026-adrenalyn','axl-HAI','Haiti','TEAM','SELECOES',223,223,'Jean-Ricner Bellegarde','HAI','BASE','MID'),
('AXL224','wc2026-adrenalyn','axl-HAI','Haiti','TEAM','SELECOES',224,224,'Ruben Providence','HAI','BASE','FWD'),
('AXL225','wc2026-adrenalyn','axl-HAI','Haiti','TEAM','SELECOES',225,225,'Don Deedson Louicius','HAI','BASE','FWD'),
('AXL226','wc2026-adrenalyn','axl-IRN','Irã','TEAM','SELECOES',226,226,'Mehdi Taremi','IRN','FAN_FAVOURITE','FWD'),
('AXL227','wc2026-adrenalyn','axl-IRN','Irã','TEAM','SELECOES',227,227,'Escudo','IRN','CREST',null),
('AXL228','wc2026-adrenalyn','axl-IRN','Irã','TEAM','SELECOES',228,228,'Sardar Azmoun','IRN','ICON','FWD'),
('AXL229','wc2026-adrenalyn','axl-IRN','Irã','TEAM','SELECOES',229,229,'Alireza Beiranvand','IRN','BASE','GK'),
('AXL230','wc2026-adrenalyn','axl-IRN','Irã','TEAM','SELECOES',230,230,'Shoja Khalilzadeh','IRN','BASE','DEF'),
('AXL231','wc2026-adrenalyn','axl-IRN','Irã','TEAM','SELECOES',231,231,'Milad Mohammadi','IRN','BASE','DEF'),
('AXL232','wc2026-adrenalyn','axl-IRN','Irã','TEAM','SELECOES',232,232,'Ramin Rezaeian','IRN','BASE','DEF'),
('AXL233','wc2026-adrenalyn','axl-IRN','Irã','TEAM','SELECOES',233,233,'Hossein Kanaani','IRN','BASE','DEF'),
('AXL234','wc2026-adrenalyn','axl-IRN','Irã','TEAM','SELECOES',234,234,'Saeid Ezatolahi','IRN','BASE','MID'),
('AXL235','wc2026-adrenalyn','axl-IRN','Irã','TEAM','SELECOES',235,235,'Saman Ghoddos','IRN','BASE','MID'),
('AXL236','wc2026-adrenalyn','axl-IRN','Irã','TEAM','SELECOES',236,236,'Mohammad Mohebi','IRN','BASE','MID'),
('AXL237','wc2026-adrenalyn','axl-IRN','Irã','TEAM','SELECOES',237,237,'Alireza Jahanbakhsh','IRN','BASE','FWD'),
('AXL238','wc2026-adrenalyn','axl-CIV','Costa do Marfim','TEAM','SELECOES',238,238,'Franck Kessié','CIV','FAN_FAVOURITE','MID'),
('AXL239','wc2026-adrenalyn','axl-CIV','Costa do Marfim','TEAM','SELECOES',239,239,'Escudo','CIV','CREST',null),
('AXL240','wc2026-adrenalyn','axl-CIV','Costa do Marfim','TEAM','SELECOES',240,240,'Sébastien Haller','CIV','ICON','FWD'),
('AXL241','wc2026-adrenalyn','axl-CIV','Costa do Marfim','TEAM','SELECOES',241,241,'Yahia Fofana','CIV','BASE','GK'),
('AXL242','wc2026-adrenalyn','axl-CIV','Costa do Marfim','TEAM','SELECOES',242,242,'Ghislain Konan','CIV','BASE','DEF'),
('AXL243','wc2026-adrenalyn','axl-CIV','Costa do Marfim','TEAM','SELECOES',243,243,'Odilon Kossounou','CIV','BASE','DEF'),
('AXL244','wc2026-adrenalyn','axl-CIV','Costa do Marfim','TEAM','SELECOES',244,244,'Evan N''Dicka','CIV','BASE','DEF'),
('AXL245','wc2026-adrenalyn','axl-CIV','Costa do Marfim','TEAM','SELECOES',245,245,'Wilfried Singo','CIV','BASE','DEF'),
('AXL246','wc2026-adrenalyn','axl-CIV','Costa do Marfim','TEAM','SELECOES',246,246,'Ibrahim Sangaré','CIV','BASE','MID'),
('AXL247','wc2026-adrenalyn','axl-CIV','Costa do Marfim','TEAM','SELECOES',247,247,'Nicolas Pépé','CIV','BASE','FWD'),
('AXL248','wc2026-adrenalyn','axl-CIV','Costa do Marfim','TEAM','SELECOES',248,248,'Simon Adingra','CIV','BASE','FWD'),
('AXL249','wc2026-adrenalyn','axl-CIV','Costa do Marfim','TEAM','SELECOES',249,249,'Oumar Diakité','CIV','BASE','FWD'),
('AXL250','wc2026-adrenalyn','axl-JPN','Japão','TEAM','SELECOES',250,250,'Takumi Minamino','JPN','FAN_FAVOURITE','MID'),
('AXL251','wc2026-adrenalyn','axl-JPN','Japão','TEAM','SELECOES',251,251,'Escudo','JPN','CREST',null),
('AXL252','wc2026-adrenalyn','axl-JPN','Japão','TEAM','SELECOES',252,252,'Takefusa Kubo','JPN','ICON','MID'),
('AXL253','wc2026-adrenalyn','axl-JPN','Japão','TEAM','SELECOES',253,253,'Zion Suzuki','JPN','BASE','GK'),
('AXL254','wc2026-adrenalyn','axl-JPN','Japão','TEAM','SELECOES',254,254,'Tsuyoshi Watanabe','JPN','BASE','DEF'),
('AXL255','wc2026-adrenalyn','axl-JPN','Japão','TEAM','SELECOES',255,255,'Kaishu Sano','JPN','BASE','MID'),
('AXL256','wc2026-adrenalyn','axl-JPN','Japão','TEAM','SELECOES',256,256,'Ao Tanaka','JPN','BASE','MID'),
('AXL257','wc2026-adrenalyn','axl-JPN','Japão','TEAM','SELECOES',257,257,'Daichi Kamada','JPN','BASE','MID'),
('AXL258','wc2026-adrenalyn','axl-JPN','Japão','TEAM','SELECOES',258,258,'Ritsu Doan','JPN','BASE','MID'),
('AXL259','wc2026-adrenalyn','axl-JPN','Japão','TEAM','SELECOES',259,259,'Keito Nakamura','JPN','BASE','MID'),
('AXL260','wc2026-adrenalyn','axl-JPN','Japão','TEAM','SELECOES',260,260,'Shuto Machino','JPN','BASE','FWD'),
('AXL261','wc2026-adrenalyn','axl-JPN','Japão','TEAM','SELECOES',261,261,'Ayase Ueda','JPN','BASE','FWD'),
('AXL262','wc2026-adrenalyn','axl-JOR','Jordânia','TEAM','SELECOES',262,262,'Yazan Al-Naimat','JOR','FAN_FAVOURITE','FWD'),
('AXL263','wc2026-adrenalyn','axl-JOR','Jordânia','TEAM','SELECOES',263,263,'Escudo','JOR','CREST',null),
('AXL264','wc2026-adrenalyn','axl-JOR','Jordânia','TEAM','SELECOES',264,264,'Musa Al-Taamari','JOR','ICON','FWD'),
('AXL265','wc2026-adrenalyn','axl-JOR','Jordânia','TEAM','SELECOES',265,265,'Yazeed Abulaila','JOR','BASE','GK'),
('AXL266','wc2026-adrenalyn','axl-JOR','Jordânia','TEAM','SELECOES',266,266,'Mohammad Abu Hashish','JOR','BASE','DEF'),
('AXL267','wc2026-adrenalyn','axl-JOR','Jordânia','TEAM','SELECOES',267,267,'Yazan Al-Arab','JOR','BASE','DEF'),
('AXL268','wc2026-adrenalyn','axl-JOR','Jordânia','TEAM','SELECOES',268,268,'Abdallah Nasib','JOR','BASE','DEF'),
('AXL269','wc2026-adrenalyn','axl-JOR','Jordânia','TEAM','SELECOES',269,269,'Ibrahim Saadeh','JOR','BASE','MID'),
('AXL270','wc2026-adrenalyn','axl-JOR','Jordânia','TEAM','SELECOES',270,270,'Nizar Al-Rashdan','JOR','BASE','MID'),
('AXL271','wc2026-adrenalyn','axl-JOR','Jordânia','TEAM','SELECOES',271,271,'Noor Al-Rawabdeh','JOR','BASE','MID'),
('AXL272','wc2026-adrenalyn','axl-JOR','Jordânia','TEAM','SELECOES',272,272,'Mahmoud Al-Mardi','JOR','BASE','FWD'),
('AXL273','wc2026-adrenalyn','axl-JOR','Jordânia','TEAM','SELECOES',273,273,'Ali Olwan','JOR','BASE','FWD'),
('AXL274','wc2026-adrenalyn','axl-KOR','Coreia do Sul','TEAM','SELECOES',274,274,'Minjae Kim','KOR','FAN_FAVOURITE','DEF'),
('AXL275','wc2026-adrenalyn','axl-KOR','Coreia do Sul','TEAM','SELECOES',275,275,'Escudo','KOR','CREST',null),
('AXL276','wc2026-adrenalyn','axl-KOR','Coreia do Sul','TEAM','SELECOES',276,276,'Heungmin Son','KOR','ICON','FWD'),
('AXL277','wc2026-adrenalyn','axl-KOR','Coreia do Sul','TEAM','SELECOES',277,277,'Hyeonwoo Jo','KOR','BASE','GK'),
('AXL278','wc2026-adrenalyn','axl-KOR','Coreia do Sul','TEAM','SELECOES',278,278,'Youngwoo Seol','KOR','BASE','DEF'),
('AXL279','wc2026-adrenalyn','axl-KOR','Coreia do Sul','TEAM','SELECOES',279,279,'Yumin Cho','KOR','BASE','DEF'),
('AXL280','wc2026-adrenalyn','axl-KOR','Coreia do Sul','TEAM','SELECOES',280,280,'Taeseok Lee','KOR','BASE','DEF'),
('AXL281','wc2026-adrenalyn','axl-KOR','Coreia do Sul','TEAM','SELECOES',281,281,'Inbeom Hwang','KOR','BASE','MID'),
('AXL282','wc2026-adrenalyn','axl-KOR','Coreia do Sul','TEAM','SELECOES',282,282,'Jaesung Lee','KOR','BASE','MID'),
('AXL283','wc2026-adrenalyn','axl-KOR','Coreia do Sul','TEAM','SELECOES',283,283,'Kangin Lee','KOR','BASE','MID'),
('AXL284','wc2026-adrenalyn','axl-KOR','Coreia do Sul','TEAM','SELECOES',284,284,'Hyeongyu Oh','KOR','BASE','FWD'),
('AXL285','wc2026-adrenalyn','axl-KOR','Coreia do Sul','TEAM','SELECOES',285,285,'Heechan Hwang','KOR','BASE','FWD'),
('AXL286','wc2026-adrenalyn','axl-MEX','México','TEAM','SELECOES',286,286,'Edson Álvarez','MEX','FAN_FAVOURITE','MID'),
('AXL287','wc2026-adrenalyn','axl-MEX','México','TEAM','SELECOES',287,287,'Escudo','MEX','CREST',null),
('AXL288','wc2026-adrenalyn','axl-MEX','México','TEAM','SELECOES',288,288,'Raúl Jiménez','MEX','ICON','FWD'),
('AXL289','wc2026-adrenalyn','axl-MEX','México','TEAM','SELECOES',289,289,'Luis Malagón','MEX','BASE','GK'),
('AXL290','wc2026-adrenalyn','axl-MEX','México','TEAM','SELECOES',290,290,'Israel Reyes','MEX','BASE','DEF'),
('AXL291','wc2026-adrenalyn','axl-MEX','México','TEAM','SELECOES',291,291,'Johan Vásquez','MEX','BASE','DEF'),
('AXL292','wc2026-adrenalyn','axl-MEX','México','TEAM','SELECOES',292,292,'César Montes','MEX','BASE','DEF'),
('AXL293','wc2026-adrenalyn','axl-MEX','México','TEAM','SELECOES',293,293,'Jesús Gallardo','MEX','BASE','DEF'),
('AXL294','wc2026-adrenalyn','axl-MEX','México','TEAM','SELECOES',294,294,'Carlos Rodríguez','MEX','BASE','MID'),
('AXL295','wc2026-adrenalyn','axl-MEX','México','TEAM','SELECOES',295,295,'Orbelín Pineda','MEX','BASE','MID'),
('AXL296','wc2026-adrenalyn','axl-MEX','México','TEAM','SELECOES',296,296,'Hirving Lozano','MEX','BASE','FWD'),
('AXL297','wc2026-adrenalyn','axl-MEX','México','TEAM','SELECOES',297,297,'Santiago Giménez','MEX','BASE','FWD'),
('AXL298','wc2026-adrenalyn','axl-MAR','Marrocos','TEAM','SELECOES',298,298,'Youssef En-Nesyri','MAR','FAN_FAVOURITE','FWD'),
('AXL299','wc2026-adrenalyn','axl-MAR','Marrocos','TEAM','SELECOES',299,299,'Escudo','MAR','CREST',null),
('AXL300','wc2026-adrenalyn','axl-MAR','Marrocos','TEAM','SELECOES',300,300,'Achraf Hakimi','MAR','ICON','DEF'),
('AXL301','wc2026-adrenalyn','axl-MAR','Marrocos','TEAM','SELECOES',301,301,'Yassine Bounou','MAR','BASE','GK'),
('AXL302','wc2026-adrenalyn','axl-MAR','Marrocos','TEAM','SELECOES',302,302,'Noussair Mazraoui','MAR','BASE','DEF'),
('AXL303','wc2026-adrenalyn','axl-MAR','Marrocos','TEAM','SELECOES',303,303,'Nayef Aguerd','MAR','BASE','DEF'),
('AXL304','wc2026-adrenalyn','axl-MAR','Marrocos','TEAM','SELECOES',304,304,'Sofyan Amrabat','MAR','BASE','MID'),
('AXL305','wc2026-adrenalyn','axl-MAR','Marrocos','TEAM','SELECOES',305,305,'Eliesse Ben Seghir','MAR','BASE','MID'),
('AXL306','wc2026-adrenalyn','axl-MAR','Marrocos','TEAM','SELECOES',306,306,'Ismael Saibari','MAR','BASE','MID'),
('AXL307','wc2026-adrenalyn','axl-MAR','Marrocos','TEAM','SELECOES',307,307,'Brahim Díaz','MAR','BASE','FWD'),
('AXL308','wc2026-adrenalyn','axl-MAR','Marrocos','TEAM','SELECOES',308,308,'Abde Ezzalzouli','MAR','BASE','FWD'),
('AXL309','wc2026-adrenalyn','axl-MAR','Marrocos','TEAM','SELECOES',309,309,'Ayoub El Kaabi','MAR','BASE','FWD'),
('AXL310','wc2026-adrenalyn','axl-NED','Holanda','TEAM','SELECOES',310,310,'Memphis Depay','NED','FAN_FAVOURITE','FWD'),
('AXL311','wc2026-adrenalyn','axl-NED','Holanda','TEAM','SELECOES',311,311,'Escudo','NED','CREST',null),
('AXL312','wc2026-adrenalyn','axl-NED','Holanda','TEAM','SELECOES',312,312,'Virgil van Dijk','NED','ICON','DEF'),
('AXL313','wc2026-adrenalyn','axl-NED','Holanda','TEAM','SELECOES',313,313,'Bart Verbruggen','NED','BASE','GK'),
('AXL314','wc2026-adrenalyn','axl-NED','Holanda','TEAM','SELECOES',314,314,'Nathan Aké','NED','BASE','DEF'),
('AXL315','wc2026-adrenalyn','axl-NED','Holanda','TEAM','SELECOES',315,315,'Jeremie Frimpong','NED','BASE','DEF'),
('AXL316','wc2026-adrenalyn','axl-NED','Holanda','TEAM','SELECOES',316,316,'Denzel Dumfries','NED','BASE','DEF'),
('AXL317','wc2026-adrenalyn','axl-NED','Holanda','TEAM','SELECOES',317,317,'Tijjani Reijnders','NED','BASE','MID'),
('AXL318','wc2026-adrenalyn','axl-NED','Holanda','TEAM','SELECOES',318,318,'Ryan Gravenberch','NED','BASE','MID'),
('AXL319','wc2026-adrenalyn','axl-NED','Holanda','TEAM','SELECOES',319,319,'Cody Gakpo','NED','BASE','FWD'),
('AXL320','wc2026-adrenalyn','axl-NED','Holanda','TEAM','SELECOES',320,320,'Donyell Malen','NED','BASE','FWD'),
('AXL321','wc2026-adrenalyn','axl-NED','Holanda','TEAM','SELECOES',321,321,'Wout Weghorst','NED','BASE','FWD'),
('AXL322','wc2026-adrenalyn','axl-NZL','Nova Zelândia','TEAM','SELECOES',322,322,'Marko Stamenic','NZL','FAN_FAVOURITE','MID'),
('AXL323','wc2026-adrenalyn','axl-NZL','Nova Zelândia','TEAM','SELECOES',323,323,'Escudo','NZL','CREST',null),
('AXL324','wc2026-adrenalyn','axl-NZL','Nova Zelândia','TEAM','SELECOES',324,324,'Chris Wood','NZL','ICON','FWD'),
('AXL325','wc2026-adrenalyn','axl-NZL','Nova Zelândia','TEAM','SELECOES',325,325,'Max Crocombe','NZL','BASE','GK'),
('AXL326','wc2026-adrenalyn','axl-NZL','Nova Zelândia','TEAM','SELECOES',326,326,'Michael Boxall','NZL','BASE','DEF'),
('AXL327','wc2026-adrenalyn','axl-NZL','Nova Zelândia','TEAM','SELECOES',327,327,'Liberato Cacace','NZL','BASE','DEF'),
('AXL328','wc2026-adrenalyn','axl-NZL','Nova Zelândia','TEAM','SELECOES',328,328,'Tim Payne','NZL','BASE','DEF'),
('AXL329','wc2026-adrenalyn','axl-NZL','Nova Zelândia','TEAM','SELECOES',329,329,'Finn Surman','NZL','BASE','DEF'),
('AXL330','wc2026-adrenalyn','axl-NZL','Nova Zelândia','TEAM','SELECOES',330,330,'Joe Bell','NZL','BASE','MID'),
('AXL331','wc2026-adrenalyn','axl-NZL','Nova Zelândia','TEAM','SELECOES',331,331,'Sarpreet Singh','NZL','BASE','MID'),
('AXL332','wc2026-adrenalyn','axl-NZL','Nova Zelândia','TEAM','SELECOES',332,332,'Matt Garbett','NZL','BASE','MID'),
('AXL333','wc2026-adrenalyn','axl-NZL','Nova Zelândia','TEAM','SELECOES',333,333,'Elijah Just','NZL','BASE','FWD'),
('AXL334','wc2026-adrenalyn','axl-NOR','Noruega','TEAM','SELECOES',334,334,'Martin Ødegaard','NOR','FAN_FAVOURITE','MID'),
('AXL335','wc2026-adrenalyn','axl-NOR','Noruega','TEAM','SELECOES',335,335,'Escudo','NOR','CREST',null),
('AXL336','wc2026-adrenalyn','axl-NOR','Noruega','TEAM','SELECOES',336,336,'Erling Haaland','NOR','ICON','FWD'),
('AXL337','wc2026-adrenalyn','axl-NOR','Noruega','TEAM','SELECOES',337,337,'Ørjan Nyland','NOR','BASE','GK'),
('AXL338','wc2026-adrenalyn','axl-NOR','Noruega','TEAM','SELECOES',338,338,'Julian Ryerson','NOR','BASE','DEF'),
('AXL339','wc2026-adrenalyn','axl-NOR','Noruega','TEAM','SELECOES',339,339,'Kristoffer Vassbakk Ajer','NOR','BASE','DEF'),
('AXL340','wc2026-adrenalyn','axl-NOR','Noruega','TEAM','SELECOES',340,340,'David Møller Wolfe','NOR','BASE','DEF'),
('AXL341','wc2026-adrenalyn','axl-NOR','Noruega','TEAM','SELECOES',341,341,'Sander Berge','NOR','BASE','MID'),
('AXL342','wc2026-adrenalyn','axl-NOR','Noruega','TEAM','SELECOES',342,342,'Patrick Berg','NOR','BASE','MID'),
('AXL343','wc2026-adrenalyn','axl-NOR','Noruega','TEAM','SELECOES',343,343,'Antonio Nusa','NOR','BASE','FWD'),
('AXL344','wc2026-adrenalyn','axl-NOR','Noruega','TEAM','SELECOES',344,344,'Oscar Bobb','NOR','BASE','FWD'),
('AXL345','wc2026-adrenalyn','axl-NOR','Noruega','TEAM','SELECOES',345,345,'Alexander Sørloth','NOR','BASE','FWD'),
('AXL346','wc2026-adrenalyn','axl-PAN','Panamá','TEAM','SELECOES',346,346,'Michael Amir Murillo','PAN','FAN_FAVOURITE','DEF'),
('AXL347','wc2026-adrenalyn','axl-PAN','Panamá','TEAM','SELECOES',347,347,'Escudo','PAN','CREST',null),
('AXL348','wc2026-adrenalyn','axl-PAN','Panamá','TEAM','SELECOES',348,348,'Aníbal Godoy','PAN','ICON','MID'),
('AXL349','wc2026-adrenalyn','axl-PAN','Panamá','TEAM','SELECOES',349,349,'Orlando Mosquera','PAN','BASE','GK'),
('AXL350','wc2026-adrenalyn','axl-PAN','Panamá','TEAM','SELECOES',350,350,'Andrés Andrade','PAN','BASE','DEF'),
('AXL351','wc2026-adrenalyn','axl-PAN','Panamá','TEAM','SELECOES',351,351,'Fidel Escobar','PAN','BASE','DEF'),
('AXL352','wc2026-adrenalyn','axl-PAN','Panamá','TEAM','SELECOES',352,352,'Cristian Martínez','PAN','BASE','MID'),
('AXL353','wc2026-adrenalyn','axl-PAN','Panamá','TEAM','SELECOES',353,353,'Adalberto Carrasquilla','PAN','BASE','MID'),
('AXL354','wc2026-adrenalyn','axl-PAN','Panamá','TEAM','SELECOES',354,354,'Édgar Bárcenas','PAN','BASE','MID'),
('AXL355','wc2026-adrenalyn','axl-PAN','Panamá','TEAM','SELECOES',355,355,'José Fajardo','PAN','BASE','FWD'),
('AXL356','wc2026-adrenalyn','axl-PAN','Panamá','TEAM','SELECOES',356,356,'Ismael Díaz','PAN','BASE','FWD'),
('AXL357','wc2026-adrenalyn','axl-PAN','Panamá','TEAM','SELECOES',357,357,'José Luiz Rodríguez','PAN','BASE','FWD'),
('AXL358','wc2026-adrenalyn','axl-PAR','Paraguai','TEAM','SELECOES',358,358,'Gustavo Gómez','PAR','FAN_FAVOURITE','DEF'),
('AXL359','wc2026-adrenalyn','axl-PAR','Paraguai','TEAM','SELECOES',359,359,'Escudo','PAR','CREST',null),
('AXL360','wc2026-adrenalyn','axl-PAR','Paraguai','TEAM','SELECOES',360,360,'Miguel Almirón','PAR','ICON','FWD'),
('AXL361','wc2026-adrenalyn','axl-PAR','Paraguai','TEAM','SELECOES',361,361,'Roberto Fernández','PAR','BASE','GK'),
('AXL362','wc2026-adrenalyn','axl-PAR','Paraguai','TEAM','SELECOES',362,362,'Juan José Cáceres','PAR','BASE','DEF'),
('AXL363','wc2026-adrenalyn','axl-PAR','Paraguai','TEAM','SELECOES',363,363,'Omar Alderete','PAR','BASE','DEF'),
('AXL364','wc2026-adrenalyn','axl-PAR','Paraguai','TEAM','SELECOES',364,364,'Júnior Alonso','PAR','BASE','DEF'),
('AXL365','wc2026-adrenalyn','axl-PAR','Paraguai','TEAM','SELECOES',365,365,'Andrés Cubas','PAR','BASE','MID'),
('AXL366','wc2026-adrenalyn','axl-PAR','Paraguai','TEAM','SELECOES',366,366,'Mathías Villasanti','PAR','BASE','MID'),
('AXL367','wc2026-adrenalyn','axl-PAR','Paraguai','TEAM','SELECOES',367,367,'Julio Enciso','PAR','BASE','MID'),
('AXL368','wc2026-adrenalyn','axl-PAR','Paraguai','TEAM','SELECOES',368,368,'Ramón Sosa','PAR','BASE','FWD'),
('AXL369','wc2026-adrenalyn','axl-PAR','Paraguai','TEAM','SELECOES',369,369,'Antonio Sanabria','PAR','BASE','FWD'),
('AXL370','wc2026-adrenalyn','axl-POR','Portugal','TEAM','SELECOES',370,370,'Vitinha','POR','FAN_FAVOURITE','MID'),
('AXL371','wc2026-adrenalyn','axl-POR','Portugal','TEAM','SELECOES',371,371,'Escudo','POR','CREST',null),
('AXL372','wc2026-adrenalyn','axl-POR','Portugal','TEAM','SELECOES',372,372,'Cristiano Ronaldo','POR','ICON','FWD'),
('AXL373','wc2026-adrenalyn','axl-POR','Portugal','TEAM','SELECOES',373,373,'Diogo Costa','POR','BASE','GK'),
('AXL374','wc2026-adrenalyn','axl-POR','Portugal','TEAM','SELECOES',374,374,'Rúben Dias','POR','BASE','DEF'),
('AXL375','wc2026-adrenalyn','axl-POR','Portugal','TEAM','SELECOES',375,375,'Nuno Mendes','POR','BASE','DEF'),
('AXL376','wc2026-adrenalyn','axl-POR','Portugal','TEAM','SELECOES',376,376,'Bernardo Silva','POR','BASE','MID'),
('AXL377','wc2026-adrenalyn','axl-POR','Portugal','TEAM','SELECOES',377,377,'Bruno Fernandes','POR','BASE','MID'),
('AXL378','wc2026-adrenalyn','axl-POR','Portugal','TEAM','SELECOES',378,378,'Rúben Neves','POR','BASE','MID'),
('AXL379','wc2026-adrenalyn','axl-POR','Portugal','TEAM','SELECOES',379,379,'Francisco Conceição','POR','BASE','FWD'),
('AXL380','wc2026-adrenalyn','axl-POR','Portugal','TEAM','SELECOES',380,380,'Pedro Neto','POR','BASE','FWD'),
('AXL381','wc2026-adrenalyn','axl-POR','Portugal','TEAM','SELECOES',381,381,'Rafael Leão','POR','BASE','FWD'),
('AXL382','wc2026-adrenalyn','axl-QAT','Catar','TEAM','SELECOES',382,382,'Almoez Ali','QAT','FAN_FAVOURITE','FWD'),
('AXL383','wc2026-adrenalyn','axl-QAT','Catar','TEAM','SELECOES',383,383,'Escudo','QAT','CREST',null),
('AXL384','wc2026-adrenalyn','axl-QAT','Catar','TEAM','SELECOES',384,384,'Hasan Al-Haydos','QAT','ICON','FWD'),
('AXL385','wc2026-adrenalyn','axl-QAT','Catar','TEAM','SELECOES',385,385,'Meshaal Barsham','QAT','BASE','GK'),
('AXL386','wc2026-adrenalyn','axl-QAT','Catar','TEAM','SELECOES',386,386,'Boualem Khoukhi','QAT','BASE','DEF'),
('AXL387','wc2026-adrenalyn','axl-QAT','Catar','TEAM','SELECOES',387,387,'Lucas Mendes','QAT','BASE','DEF'),
('AXL388','wc2026-adrenalyn','axl-QAT','Catar','TEAM','SELECOES',388,388,'Pedro Miguel','QAT','BASE','DEF'),
('AXL389','wc2026-adrenalyn','axl-QAT','Catar','TEAM','SELECOES',389,389,'Homam Al-Amin','QAT','BASE','DEF'),
('AXL390','wc2026-adrenalyn','axl-QAT','Catar','TEAM','SELECOES',390,390,'Ahmed Fathi','QAT','BASE','MID'),
('AXL391','wc2026-adrenalyn','axl-QAT','Catar','TEAM','SELECOES',391,391,'Edmílson Junior','QAT','BASE','FWD'),
('AXL392','wc2026-adrenalyn','axl-QAT','Catar','TEAM','SELECOES',392,392,'Ahmed Al-Ganehi','QAT','BASE','FWD'),
('AXL393','wc2026-adrenalyn','axl-QAT','Catar','TEAM','SELECOES',393,393,'Akram Hassan Afif','QAT','BASE','FWD'),
('AXL394','wc2026-adrenalyn','axl-KSA','Arábia Saudita','TEAM','SELECOES',394,394,'Feras Albrikan','KSA','FAN_FAVOURITE','FWD'),
('AXL395','wc2026-adrenalyn','axl-KSA','Arábia Saudita','TEAM','SELECOES',395,395,'Escudo','KSA','CREST',null),
('AXL396','wc2026-adrenalyn','axl-KSA','Arábia Saudita','TEAM','SELECOES',396,396,'Salem Aldawsari','KSA','ICON','FWD'),
('AXL397','wc2026-adrenalyn','axl-KSA','Arábia Saudita','TEAM','SELECOES',397,397,'Nawaf Alaqidi','KSA','BASE','GK'),
('AXL398','wc2026-adrenalyn','axl-KSA','Arábia Saudita','TEAM','SELECOES',398,398,'Hassan Altambakti','KSA','BASE','DEF'),
('AXL399','wc2026-adrenalyn','axl-KSA','Arábia Saudita','TEAM','SELECOES',399,399,'Jehad Thikri','KSA','BASE','DEF'),
('AXL400','wc2026-adrenalyn','axl-KSA','Arábia Saudita','TEAM','SELECOES',400,400,'Saud Abdulhamid','KSA','BASE','DEF'),
('AXL401','wc2026-adrenalyn','axl-KSA','Arábia Saudita','TEAM','SELECOES',401,401,'Nasser Aldawsari','KSA','BASE','MID'),
('AXL402','wc2026-adrenalyn','axl-KSA','Arábia Saudita','TEAM','SELECOES',402,402,'Abdullah Alkhaibari','KSA','BASE','MID'),
('AXL403','wc2026-adrenalyn','axl-KSA','Arábia Saudita','TEAM','SELECOES',403,403,'Musab Aljuwayr','KSA','BASE','MID'),
('AXL404','wc2026-adrenalyn','axl-KSA','Arábia Saudita','TEAM','SELECOES',404,404,'Saleh Abu Alshamat','KSA','BASE','FWD'),
('AXL405','wc2026-adrenalyn','axl-KSA','Arábia Saudita','TEAM','SELECOES',405,405,'Saleh Alshehri','KSA','BASE','FWD'),
('AXL406','wc2026-adrenalyn','axl-SCO','Escócia','TEAM','SELECOES',406,406,'Scott McTominay','SCO','FAN_FAVOURITE','MID'),
('AXL407','wc2026-adrenalyn','axl-SCO','Escócia','TEAM','SELECOES',407,407,'Escudo','SCO','CREST',null),
('AXL408','wc2026-adrenalyn','axl-SCO','Escócia','TEAM','SELECOES',408,408,'Andrew Robertson','SCO','ICON','DEF'),
('AXL409','wc2026-adrenalyn','axl-SCO','Escócia','TEAM','SELECOES',409,409,'Angus Gunn','SCO','BASE','GK'),
('AXL410','wc2026-adrenalyn','axl-SCO','Escócia','TEAM','SELECOES',410,410,'Kieran Tierney','SCO','BASE','DEF'),
('AXL411','wc2026-adrenalyn','axl-SCO','Escócia','TEAM','SELECOES',411,411,'Grant Hanley','SCO','BASE','DEF'),
('AXL412','wc2026-adrenalyn','axl-SCO','Escócia','TEAM','SELECOES',412,412,'Billy Gilmour','SCO','BASE','MID'),
('AXL413','wc2026-adrenalyn','axl-SCO','Escócia','TEAM','SELECOES',413,413,'Lewis Ferguson','SCO','BASE','MID'),
('AXL414','wc2026-adrenalyn','axl-SCO','Escócia','TEAM','SELECOES',414,414,'Ryan Christie','SCO','BASE','MID'),
('AXL415','wc2026-adrenalyn','axl-SCO','Escócia','TEAM','SELECOES',415,415,'John McGinn','SCO','BASE','MID'),
('AXL416','wc2026-adrenalyn','axl-SCO','Escócia','TEAM','SELECOES',416,416,'Ben Gannon-Doak','SCO','BASE','FWD'),
('AXL417','wc2026-adrenalyn','axl-SCO','Escócia','TEAM','SELECOES',417,417,'Ché Adams','SCO','BASE','FWD'),
('AXL418','wc2026-adrenalyn','axl-SEN','Senegal','TEAM','SELECOES',418,418,'Kalidou Koulibaly','SEN','FAN_FAVOURITE','DEF'),
('AXL419','wc2026-adrenalyn','axl-SEN','Senegal','TEAM','SELECOES',419,419,'Escudo','SEN','CREST',null),
('AXL420','wc2026-adrenalyn','axl-SEN','Senegal','TEAM','SELECOES',420,420,'Sadio Mané','SEN','ICON','FWD'),
('AXL421','wc2026-adrenalyn','axl-SEN','Senegal','TEAM','SELECOES',421,421,'Edouard Mendy','SEN','BASE','GK'),
('AXL422','wc2026-adrenalyn','axl-SEN','Senegal','TEAM','SELECOES',422,422,'Moussa Niakhaté','SEN','BASE','DEF'),
('AXL423','wc2026-adrenalyn','axl-SEN','Senegal','TEAM','SELECOES',423,423,'El Hadji Malick Diouf','SEN','BASE','DEF'),
('AXL424','wc2026-adrenalyn','axl-SEN','Senegal','TEAM','SELECOES',424,424,'Idrissa Gana Gueye','SEN','BASE','MID'),
('AXL425','wc2026-adrenalyn','axl-SEN','Senegal','TEAM','SELECOES',425,425,'Pape Matar Sarr','SEN','BASE','MID'),
('AXL426','wc2026-adrenalyn','axl-SEN','Senegal','TEAM','SELECOES',426,426,'Iliman Ndiaye','SEN','BASE','FWD'),
('AXL427','wc2026-adrenalyn','axl-SEN','Senegal','TEAM','SELECOES',427,427,'Krépin Diatta','SEN','BASE','FWD'),
('AXL428','wc2026-adrenalyn','axl-SEN','Senegal','TEAM','SELECOES',428,428,'Ismaïla Sarr','SEN','BASE','FWD'),
('AXL429','wc2026-adrenalyn','axl-SEN','Senegal','TEAM','SELECOES',429,429,'Nicolas Jackson','SEN','BASE','FWD'),
('AXL430','wc2026-adrenalyn','axl-RSA','África do Sul','TEAM','SELECOES',430,430,'Lyle Foster','RSA','FAN_FAVOURITE','FWD'),
('AXL431','wc2026-adrenalyn','axl-RSA','África do Sul','TEAM','SELECOES',431,431,'Escudo','RSA','CREST',null),
('AXL432','wc2026-adrenalyn','axl-RSA','África do Sul','TEAM','SELECOES',432,432,'Ronwen Williams','RSA','ICON','GK'),
('AXL433','wc2026-adrenalyn','axl-RSA','África do Sul','TEAM','SELECOES',433,433,'Sivabonga Ngezana','RSA','BASE','DEF'),
('AXL434','wc2026-adrenalyn','axl-RSA','África do Sul','TEAM','SELECOES',434,434,'Aubrey Modiba','RSA','BASE','DEF'),
('AXL435','wc2026-adrenalyn','axl-RSA','África do Sul','TEAM','SELECOES',435,435,'Mbekezeli Mbokazi','RSA','BASE','DEF'),
('AXL436','wc2026-adrenalyn','axl-RSA','África do Sul','TEAM','SELECOES',436,436,'Khuliso Mudau','RSA','BASE','DEF'),
('AXL437','wc2026-adrenalyn','axl-RSA','África do Sul','TEAM','SELECOES',437,437,'Teboho Mokoena','RSA','BASE','MID'),
('AXL438','wc2026-adrenalyn','axl-RSA','África do Sul','TEAM','SELECOES',438,438,'Yaya Sithole','RSA','BASE','MID'),
('AXL439','wc2026-adrenalyn','axl-RSA','África do Sul','TEAM','SELECOES',439,439,'Themba Zwane','RSA','BASE','MID'),
('AXL440','wc2026-adrenalyn','axl-RSA','África do Sul','TEAM','SELECOES',440,440,'Oswin Appollis','RSA','BASE','FWD'),
('AXL441','wc2026-adrenalyn','axl-RSA','África do Sul','TEAM','SELECOES',441,441,'Iqraam Rayners','RSA','BASE','FWD'),
('AXL442','wc2026-adrenalyn','axl-ESP','Espanha','TEAM','SELECOES',442,442,'Lamine Yamal','ESP','FAN_FAVOURITE','FWD'),
('AXL443','wc2026-adrenalyn','axl-ESP','Espanha','TEAM','SELECOES',443,443,'Escudo','ESP','CREST',null),
('AXL444','wc2026-adrenalyn','axl-ESP','Espanha','TEAM','SELECOES',444,444,'Rodri','ESP','ICON','MID'),
('AXL445','wc2026-adrenalyn','axl-ESP','Espanha','TEAM','SELECOES',445,445,'Unai Simón','ESP','BASE','GK'),
('AXL446','wc2026-adrenalyn','axl-ESP','Espanha','TEAM','SELECOES',446,446,'Robin Le Normand','ESP','BASE','DEF'),
('AXL447','wc2026-adrenalyn','axl-ESP','Espanha','TEAM','SELECOES',447,447,'Dean Huijsen','ESP','BASE','DEF'),
('AXL448','wc2026-adrenalyn','axl-ESP','Espanha','TEAM','SELECOES',448,448,'Marc Cucurella','ESP','BASE','DEF'),
('AXL449','wc2026-adrenalyn','axl-ESP','Espanha','TEAM','SELECOES',449,449,'Martín Zubimendi','ESP','BASE','MID'),
('AXL450','wc2026-adrenalyn','axl-ESP','Espanha','TEAM','SELECOES',450,450,'Pedri','ESP','BASE','MID'),
('AXL451','wc2026-adrenalyn','axl-ESP','Espanha','TEAM','SELECOES',451,451,'Fabián Ruiz','ESP','BASE','MID'),
('AXL452','wc2026-adrenalyn','axl-ESP','Espanha','TEAM','SELECOES',452,452,'Nico Williams','ESP','BASE','FWD'),
('AXL453','wc2026-adrenalyn','axl-ESP','Espanha','TEAM','SELECOES',453,453,'Mikel Oyarzabal','ESP','BASE','FWD'),
('AXL454','wc2026-adrenalyn','axl-SUI','Suíça','TEAM','SELECOES',454,454,'Manuel Akanji','SUI','FAN_FAVOURITE','DEF'),
('AXL455','wc2026-adrenalyn','axl-SUI','Suíça','TEAM','SELECOES',455,455,'Escudo','SUI','CREST',null),
('AXL456','wc2026-adrenalyn','axl-SUI','Suíça','TEAM','SELECOES',456,456,'Granit Xhaka','SUI','ICON','MID'),
('AXL457','wc2026-adrenalyn','axl-SUI','Suíça','TEAM','SELECOES',457,457,'Gregor Kobel','SUI','BASE','GK'),
('AXL458','wc2026-adrenalyn','axl-SUI','Suíça','TEAM','SELECOES',458,458,'Nico Elvedi','SUI','BASE','DEF'),
('AXL459','wc2026-adrenalyn','axl-SUI','Suíça','TEAM','SELECOES',459,459,'Ricardo Rodríguez','SUI','BASE','DEF'),
('AXL460','wc2026-adrenalyn','axl-SUI','Suíça','TEAM','SELECOES',460,460,'Silvan Widmer','SUI','BASE','DEF'),
('AXL461','wc2026-adrenalyn','axl-SUI','Suíça','TEAM','SELECOES',461,461,'Denis Zakaria','SUI','BASE','MID'),
('AXL462','wc2026-adrenalyn','axl-SUI','Suíça','TEAM','SELECOES',462,462,'Remo Freuler','SUI','BASE','MID'),
('AXL463','wc2026-adrenalyn','axl-SUI','Suíça','TEAM','SELECOES',463,463,'Breel Embolo','SUI','BASE','FWD'),
('AXL464','wc2026-adrenalyn','axl-SUI','Suíça','TEAM','SELECOES',464,464,'Rubén Vargas','SUI','BASE','FWD'),
('AXL465','wc2026-adrenalyn','axl-SUI','Suíça','TEAM','SELECOES',465,465,'Dan Ndoye','SUI','BASE','FWD'),
('AXL466','wc2026-adrenalyn','axl-TUN','Tunísia','TEAM','SELECOES',466,466,'Ferjani Sassi','TUN','FAN_FAVOURITE','MID'),
('AXL467','wc2026-adrenalyn','axl-TUN','Tunísia','TEAM','SELECOES',467,467,'Escudo','TUN','CREST',null),
('AXL468','wc2026-adrenalyn','axl-TUN','Tunísia','TEAM','SELECOES',468,468,'Ellyes Skhiri','TUN','ICON','MID'),
('AXL469','wc2026-adrenalyn','axl-TUN','Tunísia','TEAM','SELECOES',469,469,'Aymen Dahmen','TUN','BASE','GK'),
('AXL470','wc2026-adrenalyn','axl-TUN','Tunísia','TEAM','SELECOES',470,470,'Montassar Talbi','TUN','BASE','DEF'),
('AXL471','wc2026-adrenalyn','axl-TUN','Tunísia','TEAM','SELECOES',471,471,'Yassine Meriah','TUN','BASE','DEF'),
('AXL472','wc2026-adrenalyn','axl-TUN','Tunísia','TEAM','SELECOES',472,472,'Ali Abdi','TUN','BASE','DEF'),
('AXL473','wc2026-adrenalyn','axl-TUN','Tunísia','TEAM','SELECOES',473,473,'Aïssa Laïdouni','TUN','BASE','MID'),
('AXL474','wc2026-adrenalyn','axl-TUN','Tunísia','TEAM','SELECOES',474,474,'Hannibal Mejbri','TUN','BASE','MID'),
('AXL475','wc2026-adrenalyn','axl-TUN','Tunísia','TEAM','SELECOES',475,475,'Naïm Sliti','TUN','BASE','FWD'),
('AXL476','wc2026-adrenalyn','axl-TUN','Tunísia','TEAM','SELECOES',476,476,'Elias Achouri','TUN','BASE','FWD'),
('AXL477','wc2026-adrenalyn','axl-TUN','Tunísia','TEAM','SELECOES',477,477,'Hazem Mastouri','TUN','BASE','FWD'),
('AXL478','wc2026-adrenalyn','axl-USA','Estados Unidos','TEAM','SELECOES',478,478,'Weston McKennie','USA','FAN_FAVOURITE','MID'),
('AXL479','wc2026-adrenalyn','axl-USA','Estados Unidos','TEAM','SELECOES',479,479,'Escudo','USA','CREST',null),
('AXL480','wc2026-adrenalyn','axl-USA','Estados Unidos','TEAM','SELECOES',480,480,'Christian Pulisic','USA','ICON','FWD'),
('AXL481','wc2026-adrenalyn','axl-USA','Estados Unidos','TEAM','SELECOES',481,481,'Matt Freese','USA','BASE','GK'),
('AXL482','wc2026-adrenalyn','axl-USA','Estados Unidos','TEAM','SELECOES',482,482,'Chris Richards','USA','BASE','DEF'),
('AXL483','wc2026-adrenalyn','axl-USA','Estados Unidos','TEAM','SELECOES',483,483,'Tim Ream','USA','BASE','DEF'),
('AXL484','wc2026-adrenalyn','axl-USA','Estados Unidos','TEAM','SELECOES',484,484,'Antonee Robinson','USA','BASE','DEF'),
('AXL485','wc2026-adrenalyn','axl-USA','Estados Unidos','TEAM','SELECOES',485,485,'Tanner Tessmann','USA','BASE','MID'),
('AXL486','wc2026-adrenalyn','axl-USA','Estados Unidos','TEAM','SELECOES',486,486,'Tyler Adams','USA','BASE','MID'),
('AXL487','wc2026-adrenalyn','axl-USA','Estados Unidos','TEAM','SELECOES',487,487,'Timothy Weah','USA','BASE','MID'),
('AXL488','wc2026-adrenalyn','axl-USA','Estados Unidos','TEAM','SELECOES',488,488,'Malik Tillman','USA','BASE','FWD'),
('AXL489','wc2026-adrenalyn','axl-USA','Estados Unidos','TEAM','SELECOES',489,489,'Folarin Balogun','USA','BASE','FWD'),
('AXL490','wc2026-adrenalyn','axl-URU','Uruguai','TEAM','SELECOES',490,490,'José María Giménez','URU','FAN_FAVOURITE','DEF'),
('AXL491','wc2026-adrenalyn','axl-URU','Uruguai','TEAM','SELECOES',491,491,'Escudo','URU','CREST',null),
('AXL492','wc2026-adrenalyn','axl-URU','Uruguai','TEAM','SELECOES',492,492,'Federico Valverde','URU','ICON','MID'),
('AXL493','wc2026-adrenalyn','axl-URU','Uruguai','TEAM','SELECOES',493,493,'Sergio Rochet','URU','BASE','GK'),
('AXL494','wc2026-adrenalyn','axl-URU','Uruguai','TEAM','SELECOES',494,494,'Ronald Araújo','URU','BASE','DEF'),
('AXL495','wc2026-adrenalyn','axl-URU','Uruguai','TEAM','SELECOES',495,495,'Sebastián Cáceres','URU','BASE','DEF'),
('AXL496','wc2026-adrenalyn','axl-URU','Uruguai','TEAM','SELECOES',496,496,'Mathías Olivera','URU','BASE','DEF'),
('AXL497','wc2026-adrenalyn','axl-URU','Uruguai','TEAM','SELECOES',497,497,'Nahitan Nández','URU','BASE','DEF'),
('AXL498','wc2026-adrenalyn','axl-URU','Uruguai','TEAM','SELECOES',498,498,'Rodrigo Bentancur','URU','BASE','MID'),
('AXL499','wc2026-adrenalyn','axl-URU','Uruguai','TEAM','SELECOES',499,499,'Manuel Ugarte','URU','BASE','MID'),
('AXL500','wc2026-adrenalyn','axl-URU','Uruguai','TEAM','SELECOES',500,500,'Facundo Pellistri','URU','BASE','FWD'),
('AXL501','wc2026-adrenalyn','axl-URU','Uruguai','TEAM','SELECOES',501,501,'Darwin Núñez','URU','BASE','FWD'),
('AXL502','wc2026-adrenalyn','axl-UZB','Uzbequistão','TEAM','SELECOES',502,502,'Abdukodir Khusanov','UZB','FAN_FAVOURITE','DEF'),
('AXL503','wc2026-adrenalyn','axl-UZB','Uzbequistão','TEAM','SELECOES',503,503,'Escudo','UZB','CREST',null),
('AXL504','wc2026-adrenalyn','axl-UZB','Uzbequistão','TEAM','SELECOES',504,504,'Eldor Shomurodov','UZB','ICON','FWD'),
('AXL505','wc2026-adrenalyn','axl-UZB','Uzbequistão','TEAM','SELECOES',505,505,'Utkir Yusupov','UZB','BASE','GK'),
('AXL506','wc2026-adrenalyn','axl-UZB','Uzbequistão','TEAM','SELECOES',506,506,'Farrukh Sayfiev','UZB','BASE','DEF'),
('AXL507','wc2026-adrenalyn','axl-UZB','Uzbequistão','TEAM','SELECOES',507,507,'Sherzod Nasrullaev','UZB','BASE','DEF'),
('AXL508','wc2026-adrenalyn','axl-UZB','Uzbequistão','TEAM','SELECOES',508,508,'Husniddin Aliqulov','UZB','BASE','DEF'),
('AXL509','wc2026-adrenalyn','axl-UZB','Uzbequistão','TEAM','SELECOES',509,509,'Rustam Ashurmatov','UZB','BASE','DEF'),
('AXL510','wc2026-adrenalyn','axl-UZB','Uzbequistão','TEAM','SELECOES',510,510,'Khojiakbar Alijonov','UZB','BASE','DEF'),
('AXL511','wc2026-adrenalyn','axl-UZB','Uzbequistão','TEAM','SELECOES',511,511,'Odiljon Hamrobekov','UZB','BASE','MID'),
('AXL512','wc2026-adrenalyn','axl-UZB','Uzbequistão','TEAM','SELECOES',512,512,'Otabek Shukurov','UZB','BASE','MID'),
('AXL513','wc2026-adrenalyn','axl-UZB','Uzbequistão','TEAM','SELECOES',513,513,'Abbosbek Fayzullaev','UZB','BASE','FWD'),
('AXL514','wc2026-adrenalyn','axl-contenders','Contenders','CONTENDER','CONTENDERS',514,514,'ITA - NIR/WAL - BIH',null,'CONTENDER_PATH',null),
('AXL515','wc2026-adrenalyn','axl-contenders','Contenders','CONTENDER','CONTENDERS',515,515,'UKR - SWE/POL - ALB',null,'CONTENDER_PATH',null),
('AXL516','wc2026-adrenalyn','axl-contenders','Contenders','CONTENDER','CONTENDERS',516,516,'TUR - ROU/SVK - KOS',null,'CONTENDER_PATH',null),
('AXL517','wc2026-adrenalyn','axl-contenders','Contenders','CONTENDER','CONTENDERS',517,517,'DEN - MKD/CZE - IRL',null,'CONTENDER_PATH',null),
('AXL518','wc2026-adrenalyn','axl-contenders','Contenders','CONTENDER','CONTENDERS',518,518,'NCL - JAM/COD',null,'CONTENDER_PATH',null),
('AXL519','wc2026-adrenalyn','axl-contenders','Contenders','CONTENDER','CONTENDERS',519,519,'SUR - BOL/IRQ',null,'CONTENDER_PATH',null),
('AXL520','wc2026-adrenalyn','axl-contenders','Contenders','CONTENDER','CONTENDERS',520,520,'Hjulmand (DEN)','DEN','CONTENDER','MID'),
('AXL521','wc2026-adrenalyn','axl-contenders','Contenders','CONTENDER','CONTENDERS',521,521,'Højbjerg (DEN)','DEN','CONTENDER','MID'),
('AXL522','wc2026-adrenalyn','axl-contenders','Contenders','CONTENDER','CONTENDERS',522,522,'Eriksen (DEN)','DEN','CONTENDER','MID'),
('AXL523','wc2026-adrenalyn','axl-contenders','Contenders','CONTENDER','CONTENDERS',523,523,'Damsgaard (DEN)','DEN','CONTENDER','MID'),
('AXL524','wc2026-adrenalyn','axl-contenders','Contenders','CONTENDER','CONTENDERS',524,524,'Højlund (DEN)','DEN','CONTENDER','FWD'),
('AXL525','wc2026-adrenalyn','axl-contenders','Contenders','CONTENDER','CONTENDERS',525,525,'Donnarumma (ITA)','ITA','CONTENDER','GK'),
('AXL526','wc2026-adrenalyn','axl-contenders','Contenders','CONTENDER','CONTENDERS',526,526,'Bastoni (ITA)','ITA','CONTENDER','DEF'),
('AXL527','wc2026-adrenalyn','axl-contenders','Contenders','CONTENDER','CONTENDERS',527,527,'Tonali (ITA)','ITA','CONTENDER','MID'),
('AXL528','wc2026-adrenalyn','axl-contenders','Contenders','CONTENDER','CONTENDERS',528,528,'Barella (ITA)','ITA','CONTENDER','MID'),
('AXL529','wc2026-adrenalyn','axl-contenders','Contenders','CONTENDER','CONTENDERS',529,529,'Kean (ITA)','ITA','CONTENDER','FWD'),
('AXL530','wc2026-adrenalyn','axl-contenders','Contenders','CONTENDER','CONTENDERS',530,530,'Blake (JAM)','JAM','CONTENDER','GK'),
('AXL531','wc2026-adrenalyn','axl-contenders','Contenders','CONTENDER','CONTENDERS',531,531,'Pinnock (JAM)','JAM','CONTENDER','DEF'),
('AXL532','wc2026-adrenalyn','axl-contenders','Contenders','CONTENDER','CONTENDERS',532,532,'Gray (JAM)','JAM','CONTENDER','FWD'),
('AXL533','wc2026-adrenalyn','axl-contenders','Contenders','CONTENDER','CONTENDERS',533,533,'Bailey (JAM)','JAM','CONTENDER','FWD'),
('AXL534','wc2026-adrenalyn','axl-contenders','Contenders','CONTENDER','CONTENDERS',534,534,'Nicholson (JAM)','JAM','CONTENDER','FWD'),
('AXL535','wc2026-adrenalyn','axl-contenders','Contenders','CONTENDER','CONTENDERS',535,535,'Cash (POL)','POL','CONTENDER','DEF'),
('AXL536','wc2026-adrenalyn','axl-contenders','Contenders','CONTENDER','CONTENDERS',536,536,'Kiwior (POL)','POL','CONTENDER','DEF'),
('AXL537','wc2026-adrenalyn','axl-contenders','Contenders','CONTENDER','CONTENDERS',537,537,'Zieliński (POL)','POL','CONTENDER','MID'),
('AXL538','wc2026-adrenalyn','axl-contenders','Contenders','CONTENDER','CONTENDERS',538,538,'Szymański (POL)','POL','CONTENDER','MID'),
('AXL539','wc2026-adrenalyn','axl-contenders','Contenders','CONTENDER','CONTENDERS',539,539,'Lewandowski (POL)','POL','CONTENDER','FWD'),
('AXL540','wc2026-adrenalyn','axl-contenders','Contenders','CONTENDER','CONTENDERS',540,540,'Hien (SWE)','SWE','CONTENDER','DEF'),
('AXL541','wc2026-adrenalyn','axl-contenders','Contenders','CONTENDER','CONTENDERS',541,541,'Kulusevski (SWE)','SWE','CONTENDER','MID'),
('AXL542','wc2026-adrenalyn','axl-contenders','Contenders','CONTENDER','CONTENDERS',542,542,'Elanga (SWE)','SWE','CONTENDER','FWD'),
('AXL543','wc2026-adrenalyn','axl-contenders','Contenders','CONTENDER','CONTENDERS',543,543,'Gyökeres (SWE)','SWE','CONTENDER','FWD'),
('AXL544','wc2026-adrenalyn','axl-contenders','Contenders','CONTENDER','CONTENDERS',544,544,'Isak (SWE)','SWE','CONTENDER','FWD'),
('AXL545','wc2026-adrenalyn','axl-contenders','Contenders','CONTENDER','CONTENDERS',545,545,'Söyüncü (TUR)','TUR','CONTENDER','DEF'),
('AXL546','wc2026-adrenalyn','axl-contenders','Contenders','CONTENDER','CONTENDERS',546,546,'Çalhanoğlu (TUR)','TUR','CONTENDER','MID'),
('AXL547','wc2026-adrenalyn','axl-contenders','Contenders','CONTENDER','CONTENDERS',547,547,'Güler (TUR)','TUR','CONTENDER','MID'),
('AXL548','wc2026-adrenalyn','axl-contenders','Contenders','CONTENDER','CONTENDERS',548,548,'Yildiz (TUR)','TUR','CONTENDER','FWD'),
('AXL549','wc2026-adrenalyn','axl-contenders','Contenders','CONTENDER','CONTENDERS',549,549,'Aktürkoğlu (TUR)','TUR','CONTENDER','FWD'),
('AXL550','wc2026-adrenalyn','axl-top-keepers','Top Keepers','SPECIAL','TOP_KEEPERS',550,550,'Martínez (ARG)','ARG','TOP_KEEPER','GK'),
('AXL551','wc2026-adrenalyn','axl-top-keepers','Top Keepers','SPECIAL','TOP_KEEPERS',551,551,'Courtois (BEL)','BEL','TOP_KEEPER','GK'),
('AXL552','wc2026-adrenalyn','axl-top-keepers','Top Keepers','SPECIAL','TOP_KEEPERS',552,552,'Alisson (BRA)','BRA','TOP_KEEPER','GK'),
('AXL553','wc2026-adrenalyn','axl-top-keepers','Top Keepers','SPECIAL','TOP_KEEPERS',553,553,'Maignan (FRA)','FRA','TOP_KEEPER','GK'),
('AXL554','wc2026-adrenalyn','axl-top-keepers','Top Keepers','SPECIAL','TOP_KEEPERS',554,554,'Suzuki (JPN)','JPN','TOP_KEEPER','GK'),
('AXL555','wc2026-adrenalyn','axl-top-keepers','Top Keepers','SPECIAL','TOP_KEEPERS',555,555,'Bounou (MAR)','MAR','TOP_KEEPER','GK'),
('AXL556','wc2026-adrenalyn','axl-top-keepers','Top Keepers','SPECIAL','TOP_KEEPERS',556,556,'Diogo Costa (POR)','POR','TOP_KEEPER','GK'),
('AXL557','wc2026-adrenalyn','axl-top-keepers','Top Keepers','SPECIAL','TOP_KEEPERS',557,557,'Simón (ESP)','ESP','TOP_KEEPER','GK'),
('AXL558','wc2026-adrenalyn','axl-top-keepers','Top Keepers','SPECIAL','TOP_KEEPERS',558,558,'Kobel (SUI)','SUI','TOP_KEEPER','GK'),
('AXL559','wc2026-adrenalyn','axl-defensive-rocks','Defensive Rocks','SPECIAL','DEFENSIVE_ROCKS',559,559,'Éder Militão (BRA)','BRA','DEFENSIVE_ROCK','DEF'),
('AXL560','wc2026-adrenalyn','axl-defensive-rocks','Defensive Rocks','SPECIAL','DEFENSIVE_ROCKS',560,560,'Davies (CAN)','CAN','DEFENSIVE_ROCK','DEF'),
('AXL561','wc2026-adrenalyn','axl-defensive-rocks','Defensive Rocks','SPECIAL','DEFENSIVE_ROCKS',561,561,'Saliba (FRA)','FRA','DEFENSIVE_ROCK','DEF'),
('AXL562','wc2026-adrenalyn','axl-defensive-rocks','Defensive Rocks','SPECIAL','DEFENSIVE_ROCKS',562,562,'Rüdiger (GER)','GER','DEFENSIVE_ROCK','DEF'),
('AXL563','wc2026-adrenalyn','axl-defensive-rocks','Defensive Rocks','SPECIAL','DEFENSIVE_ROCKS',563,563,'Kim (KOR)','KOR','DEFENSIVE_ROCK','DEF'),
('AXL564','wc2026-adrenalyn','axl-defensive-rocks','Defensive Rocks','SPECIAL','DEFENSIVE_ROCKS',564,564,'Hakimi (MAR)','MAR','DEFENSIVE_ROCK','DEF'),
('AXL565','wc2026-adrenalyn','axl-defensive-rocks','Defensive Rocks','SPECIAL','DEFENSIVE_ROCKS',565,565,'Van Dijk (NED)','NED','DEFENSIVE_ROCK','DEF'),
('AXL566','wc2026-adrenalyn','axl-defensive-rocks','Defensive Rocks','SPECIAL','DEFENSIVE_ROCKS',566,566,'Nuno Mendes (POR)','POR','DEFENSIVE_ROCK','DEF'),
('AXL567','wc2026-adrenalyn','axl-defensive-rocks','Defensive Rocks','SPECIAL','DEFENSIVE_ROCKS',567,567,'Huijsen (ESP)','ESP','DEFENSIVE_ROCK','DEF'),
('AXL568','wc2026-adrenalyn','axl-midfield-maestros','Midfield Maestros','SPECIAL','MIDFIELD_MAESTROS',568,568,'Fernández (ARG)','ARG','MIDFIELD_MAESTRO','MID'),
('AXL569','wc2026-adrenalyn','axl-midfield-maestros','Midfield Maestros','SPECIAL','MIDFIELD_MAESTROS',569,569,'De Bruyne (BEL)','BEL','MIDFIELD_MAESTRO','MID'),
('AXL570','wc2026-adrenalyn','axl-midfield-maestros','Midfield Maestros','SPECIAL','MIDFIELD_MAESTROS',570,570,'Casemiro (BRA)','BRA','MIDFIELD_MAESTRO','MID'),
('AXL571','wc2026-adrenalyn','axl-midfield-maestros','Midfield Maestros','SPECIAL','MIDFIELD_MAESTROS',571,571,'Modrić (CRO)','CRO','MIDFIELD_MAESTRO','MID'),
('AXL572','wc2026-adrenalyn','axl-midfield-maestros','Midfield Maestros','SPECIAL','MIDFIELD_MAESTROS',572,572,'Caicedo (ECU)','ECU','MIDFIELD_MAESTRO','MID'),
('AXL573','wc2026-adrenalyn','axl-midfield-maestros','Midfield Maestros','SPECIAL','MIDFIELD_MAESTROS',573,573,'Bellingham (ENG)','ENG','MIDFIELD_MAESTRO','MID'),
('AXL574','wc2026-adrenalyn','axl-midfield-maestros','Midfield Maestros','SPECIAL','MIDFIELD_MAESTROS',574,574,'Tchouaméni (FRA)','FRA','MIDFIELD_MAESTRO','MID'),
('AXL575','wc2026-adrenalyn','axl-midfield-maestros','Midfield Maestros','SPECIAL','MIDFIELD_MAESTROS',575,575,'Wirtz (GER)','GER','MIDFIELD_MAESTRO','MID'),
('AXL576','wc2026-adrenalyn','axl-midfield-maestros','Midfield Maestros','SPECIAL','MIDFIELD_MAESTROS',576,576,'Amrabat (MAR)','MAR','MIDFIELD_MAESTRO','MID'),
('AXL577','wc2026-adrenalyn','axl-midfield-maestros','Midfield Maestros','SPECIAL','MIDFIELD_MAESTROS',577,577,'Reijnders (NED)','NED','MIDFIELD_MAESTRO','MID'),
('AXL578','wc2026-adrenalyn','axl-midfield-maestros','Midfield Maestros','SPECIAL','MIDFIELD_MAESTROS',578,578,'Ødegaard (NOR)','NOR','MIDFIELD_MAESTRO','MID'),
('AXL579','wc2026-adrenalyn','axl-midfield-maestros','Midfield Maestros','SPECIAL','MIDFIELD_MAESTROS',579,579,'Vitinha (POR)','POR','MIDFIELD_MAESTRO','MID'),
('AXL580','wc2026-adrenalyn','axl-midfield-maestros','Midfield Maestros','SPECIAL','MIDFIELD_MAESTROS',580,580,'McTominay (SCO)','SCO','MIDFIELD_MAESTRO','MID'),
('AXL581','wc2026-adrenalyn','axl-midfield-maestros','Midfield Maestros','SPECIAL','MIDFIELD_MAESTROS',581,581,'Rodri (ESP)','ESP','MIDFIELD_MAESTRO','MID'),
('AXL582','wc2026-adrenalyn','axl-midfield-maestros','Midfield Maestros','SPECIAL','MIDFIELD_MAESTROS',582,582,'Pedri (ESP)','ESP','MIDFIELD_MAESTRO','MID'),
('AXL583','wc2026-adrenalyn','axl-midfield-maestros','Midfield Maestros','SPECIAL','MIDFIELD_MAESTROS',583,583,'Xhaka (SUI)','SUI','MIDFIELD_MAESTRO','MID'),
('AXL584','wc2026-adrenalyn','axl-midfield-maestros','Midfield Maestros','SPECIAL','MIDFIELD_MAESTROS',584,584,'Adams (USA)','USA','MIDFIELD_MAESTRO','MID'),
('AXL585','wc2026-adrenalyn','axl-midfield-maestros','Midfield Maestros','SPECIAL','MIDFIELD_MAESTROS',585,585,'Valverde (URU)','URU','MIDFIELD_MAESTRO','MID'),
('AXL586','wc2026-adrenalyn','axl-goal-machines','Goal Machines','SPECIAL','GOAL_MACHINES',586,586,'Alvarez (ARG)','ARG','GOAL_MACHINE','FWD'),
('AXL587','wc2026-adrenalyn','axl-goal-machines','Goal Machines','SPECIAL','GOAL_MACHINES',587,587,'Lukaku (BEL)','BEL','GOAL_MACHINE','FWD'),
('AXL588','wc2026-adrenalyn','axl-goal-machines','Goal Machines','SPECIAL','GOAL_MACHINES',588,588,'Raphinha (BRA)','BRA','GOAL_MACHINE','FWD'),
('AXL589','wc2026-adrenalyn','axl-goal-machines','Goal Machines','SPECIAL','GOAL_MACHINES',589,589,'David (CAN)','CAN','GOAL_MACHINE','FWD'),
('AXL590','wc2026-adrenalyn','axl-goal-machines','Goal Machines','SPECIAL','GOAL_MACHINES',590,590,'Díaz (COL)','COL','GOAL_MACHINE','FWD'),
('AXL591','wc2026-adrenalyn','axl-goal-machines','Goal Machines','SPECIAL','GOAL_MACHINES',591,591,'Kramarić (CRO)','CRO','GOAL_MACHINE','FWD'),
('AXL592','wc2026-adrenalyn','axl-goal-machines','Goal Machines','SPECIAL','GOAL_MACHINES',592,592,'Valencia (ECU)','ECU','GOAL_MACHINE','FWD'),
('AXL593','wc2026-adrenalyn','axl-goal-machines','Goal Machines','SPECIAL','GOAL_MACHINES',593,593,'Marmoush (EGY)','EGY','GOAL_MACHINE','FWD'),
('AXL594','wc2026-adrenalyn','axl-goal-machines','Goal Machines','SPECIAL','GOAL_MACHINES',594,594,'Rashford (ENG)','ENG','GOAL_MACHINE','FWD'),
('AXL595','wc2026-adrenalyn','axl-goal-machines','Goal Machines','SPECIAL','GOAL_MACHINES',595,595,'Kolo Muani (FRA)','FRA','GOAL_MACHINE','FWD'),
('AXL596','wc2026-adrenalyn','axl-goal-machines','Goal Machines','SPECIAL','GOAL_MACHINES',596,596,'Havertz (GER)','GER','GOAL_MACHINE','FWD'),
('AXL597','wc2026-adrenalyn','axl-goal-machines','Goal Machines','SPECIAL','GOAL_MACHINES',597,597,'Haller (CIV)','CIV','GOAL_MACHINE','FWD'),
('AXL598','wc2026-adrenalyn','axl-goal-machines','Goal Machines','SPECIAL','GOAL_MACHINES',598,598,'Jiménez (MEX)','MEX','GOAL_MACHINE','FWD'),
('AXL599','wc2026-adrenalyn','axl-goal-machines','Goal Machines','SPECIAL','GOAL_MACHINES',599,599,'En-Nesyri (MAR)','MAR','GOAL_MACHINE','FWD'),
('AXL600','wc2026-adrenalyn','axl-goal-machines','Goal Machines','SPECIAL','GOAL_MACHINES',600,600,'Gakpo (NED)','NED','GOAL_MACHINE','FWD'),
('AXL601','wc2026-adrenalyn','axl-goal-machines','Goal Machines','SPECIAL','GOAL_MACHINES',601,601,'Wood (NZL)','NZL','GOAL_MACHINE','FWD'),
('AXL602','wc2026-adrenalyn','axl-goal-machines','Goal Machines','SPECIAL','GOAL_MACHINES',602,602,'Sørloth (NOR)','NOR','GOAL_MACHINE','FWD'),
('AXL603','wc2026-adrenalyn','axl-goal-machines','Goal Machines','SPECIAL','GOAL_MACHINES',603,603,'Jackson (SEN)','SEN','GOAL_MACHINE','FWD'),
('AXL604','wc2026-adrenalyn','axl-goal-machines','Goal Machines','SPECIAL','GOAL_MACHINES',604,604,'Oyarzabal (ESP)','ESP','GOAL_MACHINE','FWD'),
('AXL605','wc2026-adrenalyn','axl-goal-machines','Goal Machines','SPECIAL','GOAL_MACHINES',605,605,'Embolo (SUI)','SUI','GOAL_MACHINE','FWD'),
('AXL606','wc2026-adrenalyn','axl-goal-machines','Goal Machines','SPECIAL','GOAL_MACHINES',606,606,'Pulisic (USA)','USA','GOAL_MACHINE','FWD'),
('AXL607','wc2026-adrenalyn','axl-goal-machines','Goal Machines','SPECIAL','GOAL_MACHINES',607,607,'Núñez (URU)','URU','GOAL_MACHINE','FWD'),
('AXL608','wc2026-adrenalyn','axl-master-rookies','Master Rookies','SPECIAL','MASTER_ROOKIES',608,608,'Paz (ARG)','ARG','MASTER_ROOKIE','MID'),
('AXL609','wc2026-adrenalyn','axl-master-rookies','Master Rookies','SPECIAL','MASTER_ROOKIES',609,609,'Mastantuono (ARG)','ARG','MASTER_ROOKIE','FWD'),
('AXL610','wc2026-adrenalyn','axl-master-rookies','Master Rookies','SPECIAL','MASTER_ROOKIES',610,610,'Debast (BEL)','BEL','MASTER_ROOKIE','DEF'),
('AXL611','wc2026-adrenalyn','axl-master-rookies','Master Rookies','SPECIAL','MASTER_ROOKIES',611,611,'Wesley (BRA)','BRA','MASTER_ROOKIE','DEF'),
('AXL612','wc2026-adrenalyn','axl-master-rookies','Master Rookies','SPECIAL','MASTER_ROOKIES',612,612,'Estêvão (BRA)','BRA','MASTER_ROOKIE','FWD'),
('AXL613','wc2026-adrenalyn','axl-master-rookies','Master Rookies','SPECIAL','MASTER_ROOKIES',613,613,'Sučić (CRO)','CRO','MASTER_ROOKIE','MID'),
('AXL614','wc2026-adrenalyn','axl-master-rookies','Master Rookies','SPECIAL','MASTER_ROOKIES',614,614,'Páez (ECU)','ECU','MASTER_ROOKIE','MID'),
('AXL615','wc2026-adrenalyn','axl-master-rookies','Master Rookies','SPECIAL','MASTER_ROOKIES',615,615,'Rogers (ENG)','ENG','MASTER_ROOKIE','MID'),
('AXL616','wc2026-adrenalyn','axl-master-rookies','Master Rookies','SPECIAL','MASTER_ROOKIES',616,616,'Doué (FRA)','FRA','MASTER_ROOKIE','FWD'),
('AXL617','wc2026-adrenalyn','axl-master-rookies','Master Rookies','SPECIAL','MASTER_ROOKIES',617,617,'Barcola (FRA)','FRA','MASTER_ROOKIE','FWD'),
('AXL618','wc2026-adrenalyn','axl-master-rookies','Master Rookies','SPECIAL','MASTER_ROOKIES',618,618,'Woltemade (GER)','GER','MASTER_ROOKIE','FWD'),
('AXL619','wc2026-adrenalyn','axl-master-rookies','Master Rookies','SPECIAL','MASTER_ROOKIES',619,619,'Simons (NED)','NED','MASTER_ROOKIE','FWD'),
('AXL620','wc2026-adrenalyn','axl-master-rookies','Master Rookies','SPECIAL','MASTER_ROOKIES',620,620,'Schjelderup (NOR)','NOR','MASTER_ROOKIE','MID'),
('AXL621','wc2026-adrenalyn','axl-master-rookies','Master Rookies','SPECIAL','MASTER_ROOKIES',621,621,'Gómez (PAR)','PAR','MASTER_ROOKIE','MID'),
('AXL622','wc2026-adrenalyn','axl-master-rookies','Master Rookies','SPECIAL','MASTER_ROOKIES',622,622,'João Neves (POR)','POR','MASTER_ROOKIE','MID'),
('AXL623','wc2026-adrenalyn','axl-master-rookies','Master Rookies','SPECIAL','MASTER_ROOKIES',623,623,'Cubarsí (ESP)','ESP','MASTER_ROOKIE','DEF'),
('AXL624','wc2026-adrenalyn','axl-especiais','Especiais','SPECIAL','ESPECIAIS',624,624,'Official Emblem',null,'EMBLEM',null),
('AXL625','wc2026-adrenalyn','axl-especiais','Especiais','SPECIAL','ESPECIAIS',625,625,'Official Mascot - Maple',null,'MASCOT','GK'),
('AXL626','wc2026-adrenalyn','axl-especiais','Especiais','SPECIAL','ESPECIAIS',626,626,'Official Mascot - Clutch',null,'MASCOT','MID'),
('AXL627','wc2026-adrenalyn','axl-especiais','Especiais','SPECIAL','ESPECIAIS',627,627,'Official Mascot - Zayu',null,'MASCOT','FWD'),
('AXL628','wc2026-adrenalyn','axl-especiais','Especiais','SPECIAL','ESPECIAIS',628,628,'Eternos 22 - Defenders',null,'ETERNOS_22','DEF'),
('AXL629','wc2026-adrenalyn','axl-especiais','Especiais','SPECIAL','ESPECIAIS',629,629,'Eternos 22 - Midfielders',null,'ETERNOS_22','MID'),
('AXL630','wc2026-adrenalyn','axl-especiais','Especiais','SPECIAL','ESPECIAIS',630,630,'Eternos 22 - Forwards','ARG','ETERNOS_22','FWD')
on conflict (code) do update
  set album_id = excluded.album_id, block_id = excluded.block_id, block_name = excluded.block_name,
      block_type = excluded.block_type, group_key = excluded.group_key, position = excluded.position,
      number = excluded.number, name = excluded.name, team_code = excluded.team_code,
      card_type = excluded.card_type, player_position = excluded.player_position;

-- ---------- user_albums ----------
create table if not exists public.user_albums (
  user_id         uuid not null references auth.users(id) on delete cascade,
  album_id        text not null references public.albums(id),
  collection_name text,
  position        int  not null default 0,
  created_at      timestamptz not null default now(),
  primary key (user_id, album_id)
);

alter table public.user_albums enable row level security;

drop policy if exists "users manage their own albums" on public.user_albums;
create policy "users manage their own albums"
  on public.user_albums for all to authenticated
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Usuários atuais: todos colecionam o Álbum Copa (é o único que existe até aqui).
insert into public.user_albums (user_id, album_id, collection_name)
select u.id, 'wc2026-panini', nullif(btrim(u.raw_user_meta_data->>'collection_name'), '')
  from auth.users u
on conflict (user_id, album_id) do nothing;

-- Contas novas: entram na coleção escolhida no cadastro (user_metadata.album_id), se ela existir
-- e estiver ativa; senão, no Álbum Copa.
create or replace function public.handle_new_user_album()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_album text := new.raw_user_meta_data->>'album_id';
begin
  if v_album is null or not exists (select 1 from public.albums a where a.id = v_album and a.active) then
    v_album := 'wc2026-panini';
  end if;
  insert into public.user_albums (user_id, album_id, collection_name)
  values (new.id, v_album, nullif(btrim(new.raw_user_meta_data->>'collection_name'), ''))
  on conflict (user_id, album_id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created_album on auth.users;
create trigger on_auth_user_created_album
  after insert on auth.users
  for each row execute function public.handle_new_user_album();

-- ---------- shop_albums ----------
create table if not exists public.shop_albums (
  user_id         uuid not null references public.shops(user_id) on delete cascade,
  album_id        text not null references public.albums(id),
  enabled         boolean not null default true,
  min_order_cents int  not null default 0 check (min_order_cents >= 0),
  group_prices    jsonb not null default '{}'::jsonb,       -- { "TEAM": 150, "FWC": 300, … } (centavos)
  updated_at      timestamptz not null default now(),
  primary key (user_id, album_id)
);

alter table public.shop_albums enable row level security;

drop policy if exists "users manage their own shop albums" on public.shop_albums;
create policy "users manage their own shop albums"
  on public.shop_albums for all to authenticated
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

insert into public.shop_albums (user_id, album_id, min_order_cents, group_prices)
select s.user_id, 'wc2026-panini', s.min_order_cents,
       jsonb_strip_nulls(jsonb_build_object(
         'FWC', s.price_fwc_cents, 'TEAM', s.price_team_cents,
         'CC',  s.price_cc_cents,  'LEG',  s.price_leg_cents))
  from public.shops s
on conflict (user_id, album_id) do nothing;

-- ---------- pedidos, carrinhos e links públicos ----------
alter table public.orders
  add column if not exists album_id text not null default 'wc2026-panini' references public.albums(id);
alter table public.cart_holds
  add column if not exists album_id text not null default 'wc2026-panini' references public.albums(id);
alter table public.collection_shares
  add column if not exists album_id text not null default 'wc2026-panini' references public.albums(id);
