-- Migração: coleção Gold Crumple Edition. Idempotente — gerada por scripts/build-golden-crumple-catalog.mjs.
-- Rode depois de supabase_migration_adrenalyn_limited.sql.
--
-- As mesmas figurinhas do Álbum Copa (FWC + 48 seleções, 980 no total) com layout dourado; sem Coca-Cola
-- e Legends. Códigos com prefixo GC (GCBRA9, GC00…). Fica fora da loja até o lojista ativar.

insert into public.albums (id, name, slug, item_singular, item_plural, total_items, active, position)
values ('wc2026-golden-crumple', 'Gold Crumple Edition', 'golden-crumple-2026', 'figurinha', 'figurinhas', 980, true, 3)
on conflict (id) do update
  set name = excluded.name, slug = excluded.slug, item_singular = excluded.item_singular,
      item_plural = excluded.item_plural, total_items = excluded.total_items, active = excluded.active;

insert into public.stickers
  (code, album_id, block_id, block_name, block_type, group_key, position, number, name, team_code, card_type, player_position)
values
('GC00','wc2026-golden-crumple','gc-fwc','FIFA World Cup History','FWC','FWC',1,null,null,null,null,null),
('GCFWC1','wc2026-golden-crumple','gc-fwc','FIFA World Cup History','FWC','FWC',2,null,null,null,null,null),
('GCFWC2','wc2026-golden-crumple','gc-fwc','FIFA World Cup History','FWC','FWC',3,null,null,null,null,null),
('GCFWC3','wc2026-golden-crumple','gc-fwc','FIFA World Cup History','FWC','FWC',4,null,null,null,null,null),
('GCFWC4','wc2026-golden-crumple','gc-fwc','FIFA World Cup History','FWC','FWC',5,null,null,null,null,null),
('GCFWC5','wc2026-golden-crumple','gc-fwc','FIFA World Cup History','FWC','FWC',6,null,null,null,null,null),
('GCFWC6','wc2026-golden-crumple','gc-fwc','FIFA World Cup History','FWC','FWC',7,null,null,null,null,null),
('GCFWC7','wc2026-golden-crumple','gc-fwc','FIFA World Cup History','FWC','FWC',8,null,null,null,null,null),
('GCFWC8','wc2026-golden-crumple','gc-fwc','FIFA World Cup History','FWC','FWC',9,null,null,null,null,null),
('GCFWC9','wc2026-golden-crumple','gc-fwc','FIFA World Cup History','FWC','FWC',10,null,null,null,null,null),
('GCFWC10','wc2026-golden-crumple','gc-fwc','FIFA World Cup History','FWC','FWC',11,null,null,null,null,null),
('GCFWC11','wc2026-golden-crumple','gc-fwc','FIFA World Cup History','FWC','FWC',12,null,null,null,null,null),
('GCFWC12','wc2026-golden-crumple','gc-fwc','FIFA World Cup History','FWC','FWC',13,null,null,null,null,null),
('GCFWC13','wc2026-golden-crumple','gc-fwc','FIFA World Cup History','FWC','FWC',14,null,null,null,null,null),
('GCFWC14','wc2026-golden-crumple','gc-fwc','FIFA World Cup History','FWC','FWC',15,null,null,null,null,null),
('GCFWC15','wc2026-golden-crumple','gc-fwc','FIFA World Cup History','FWC','FWC',16,null,null,null,null,null),
('GCFWC16','wc2026-golden-crumple','gc-fwc','FIFA World Cup History','FWC','FWC',17,null,null,null,null,null),
('GCFWC17','wc2026-golden-crumple','gc-fwc','FIFA World Cup History','FWC','FWC',18,null,null,null,null,null),
('GCFWC18','wc2026-golden-crumple','gc-fwc','FIFA World Cup History','FWC','FWC',19,null,null,null,null,null),
('GCFWC19','wc2026-golden-crumple','gc-fwc','FIFA World Cup History','FWC','FWC',20,null,null,null,null,null),
('GCMEX1','wc2026-golden-crumple','gc-MEX','México','TEAM','A',1,null,null,'MEX',null,null),
('GCMEX2','wc2026-golden-crumple','gc-MEX','México','TEAM','A',2,null,null,'MEX',null,null),
('GCMEX3','wc2026-golden-crumple','gc-MEX','México','TEAM','A',3,null,null,'MEX',null,null),
('GCMEX4','wc2026-golden-crumple','gc-MEX','México','TEAM','A',4,null,null,'MEX',null,null),
('GCMEX5','wc2026-golden-crumple','gc-MEX','México','TEAM','A',5,null,null,'MEX',null,null),
('GCMEX6','wc2026-golden-crumple','gc-MEX','México','TEAM','A',6,null,null,'MEX',null,null),
('GCMEX7','wc2026-golden-crumple','gc-MEX','México','TEAM','A',7,null,null,'MEX',null,null),
('GCMEX8','wc2026-golden-crumple','gc-MEX','México','TEAM','A',8,null,null,'MEX',null,null),
('GCMEX9','wc2026-golden-crumple','gc-MEX','México','TEAM','A',9,null,null,'MEX',null,null),
('GCMEX10','wc2026-golden-crumple','gc-MEX','México','TEAM','A',10,null,null,'MEX',null,null),
('GCMEX11','wc2026-golden-crumple','gc-MEX','México','TEAM','A',11,null,null,'MEX',null,null),
('GCMEX12','wc2026-golden-crumple','gc-MEX','México','TEAM','A',12,null,null,'MEX',null,null),
('GCMEX13','wc2026-golden-crumple','gc-MEX','México','TEAM','A',13,null,null,'MEX',null,null),
('GCMEX14','wc2026-golden-crumple','gc-MEX','México','TEAM','A',14,null,null,'MEX',null,null),
('GCMEX15','wc2026-golden-crumple','gc-MEX','México','TEAM','A',15,null,null,'MEX',null,null),
('GCMEX16','wc2026-golden-crumple','gc-MEX','México','TEAM','A',16,null,null,'MEX',null,null),
('GCMEX17','wc2026-golden-crumple','gc-MEX','México','TEAM','A',17,null,null,'MEX',null,null),
('GCMEX18','wc2026-golden-crumple','gc-MEX','México','TEAM','A',18,null,null,'MEX',null,null),
('GCMEX19','wc2026-golden-crumple','gc-MEX','México','TEAM','A',19,null,null,'MEX',null,null),
('GCMEX20','wc2026-golden-crumple','gc-MEX','México','TEAM','A',20,null,null,'MEX',null,null),
('GCRSA1','wc2026-golden-crumple','gc-RSA','África do Sul','TEAM','A',1,null,null,'RSA',null,null),
('GCRSA2','wc2026-golden-crumple','gc-RSA','África do Sul','TEAM','A',2,null,null,'RSA',null,null),
('GCRSA3','wc2026-golden-crumple','gc-RSA','África do Sul','TEAM','A',3,null,null,'RSA',null,null),
('GCRSA4','wc2026-golden-crumple','gc-RSA','África do Sul','TEAM','A',4,null,null,'RSA',null,null),
('GCRSA5','wc2026-golden-crumple','gc-RSA','África do Sul','TEAM','A',5,null,null,'RSA',null,null),
('GCRSA6','wc2026-golden-crumple','gc-RSA','África do Sul','TEAM','A',6,null,null,'RSA',null,null),
('GCRSA7','wc2026-golden-crumple','gc-RSA','África do Sul','TEAM','A',7,null,null,'RSA',null,null),
('GCRSA8','wc2026-golden-crumple','gc-RSA','África do Sul','TEAM','A',8,null,null,'RSA',null,null),
('GCRSA9','wc2026-golden-crumple','gc-RSA','África do Sul','TEAM','A',9,null,null,'RSA',null,null),
('GCRSA10','wc2026-golden-crumple','gc-RSA','África do Sul','TEAM','A',10,null,null,'RSA',null,null),
('GCRSA11','wc2026-golden-crumple','gc-RSA','África do Sul','TEAM','A',11,null,null,'RSA',null,null),
('GCRSA12','wc2026-golden-crumple','gc-RSA','África do Sul','TEAM','A',12,null,null,'RSA',null,null),
('GCRSA13','wc2026-golden-crumple','gc-RSA','África do Sul','TEAM','A',13,null,null,'RSA',null,null),
('GCRSA14','wc2026-golden-crumple','gc-RSA','África do Sul','TEAM','A',14,null,null,'RSA',null,null),
('GCRSA15','wc2026-golden-crumple','gc-RSA','África do Sul','TEAM','A',15,null,null,'RSA',null,null),
('GCRSA16','wc2026-golden-crumple','gc-RSA','África do Sul','TEAM','A',16,null,null,'RSA',null,null),
('GCRSA17','wc2026-golden-crumple','gc-RSA','África do Sul','TEAM','A',17,null,null,'RSA',null,null),
('GCRSA18','wc2026-golden-crumple','gc-RSA','África do Sul','TEAM','A',18,null,null,'RSA',null,null),
('GCRSA19','wc2026-golden-crumple','gc-RSA','África do Sul','TEAM','A',19,null,null,'RSA',null,null),
('GCRSA20','wc2026-golden-crumple','gc-RSA','África do Sul','TEAM','A',20,null,null,'RSA',null,null),
('GCKOR1','wc2026-golden-crumple','gc-KOR','Coreia do Sul','TEAM','A',1,null,null,'KOR',null,null),
('GCKOR2','wc2026-golden-crumple','gc-KOR','Coreia do Sul','TEAM','A',2,null,null,'KOR',null,null),
('GCKOR3','wc2026-golden-crumple','gc-KOR','Coreia do Sul','TEAM','A',3,null,null,'KOR',null,null),
('GCKOR4','wc2026-golden-crumple','gc-KOR','Coreia do Sul','TEAM','A',4,null,null,'KOR',null,null),
('GCKOR5','wc2026-golden-crumple','gc-KOR','Coreia do Sul','TEAM','A',5,null,null,'KOR',null,null),
('GCKOR6','wc2026-golden-crumple','gc-KOR','Coreia do Sul','TEAM','A',6,null,null,'KOR',null,null),
('GCKOR7','wc2026-golden-crumple','gc-KOR','Coreia do Sul','TEAM','A',7,null,null,'KOR',null,null),
('GCKOR8','wc2026-golden-crumple','gc-KOR','Coreia do Sul','TEAM','A',8,null,null,'KOR',null,null),
('GCKOR9','wc2026-golden-crumple','gc-KOR','Coreia do Sul','TEAM','A',9,null,null,'KOR',null,null),
('GCKOR10','wc2026-golden-crumple','gc-KOR','Coreia do Sul','TEAM','A',10,null,null,'KOR',null,null),
('GCKOR11','wc2026-golden-crumple','gc-KOR','Coreia do Sul','TEAM','A',11,null,null,'KOR',null,null),
('GCKOR12','wc2026-golden-crumple','gc-KOR','Coreia do Sul','TEAM','A',12,null,null,'KOR',null,null),
('GCKOR13','wc2026-golden-crumple','gc-KOR','Coreia do Sul','TEAM','A',13,null,null,'KOR',null,null),
('GCKOR14','wc2026-golden-crumple','gc-KOR','Coreia do Sul','TEAM','A',14,null,null,'KOR',null,null),
('GCKOR15','wc2026-golden-crumple','gc-KOR','Coreia do Sul','TEAM','A',15,null,null,'KOR',null,null),
('GCKOR16','wc2026-golden-crumple','gc-KOR','Coreia do Sul','TEAM','A',16,null,null,'KOR',null,null),
('GCKOR17','wc2026-golden-crumple','gc-KOR','Coreia do Sul','TEAM','A',17,null,null,'KOR',null,null),
('GCKOR18','wc2026-golden-crumple','gc-KOR','Coreia do Sul','TEAM','A',18,null,null,'KOR',null,null),
('GCKOR19','wc2026-golden-crumple','gc-KOR','Coreia do Sul','TEAM','A',19,null,null,'KOR',null,null),
('GCKOR20','wc2026-golden-crumple','gc-KOR','Coreia do Sul','TEAM','A',20,null,null,'KOR',null,null),
('GCCZE1','wc2026-golden-crumple','gc-CZE','Rep. Tcheca','TEAM','A',1,null,null,'CZE',null,null),
('GCCZE2','wc2026-golden-crumple','gc-CZE','Rep. Tcheca','TEAM','A',2,null,null,'CZE',null,null),
('GCCZE3','wc2026-golden-crumple','gc-CZE','Rep. Tcheca','TEAM','A',3,null,null,'CZE',null,null),
('GCCZE4','wc2026-golden-crumple','gc-CZE','Rep. Tcheca','TEAM','A',4,null,null,'CZE',null,null),
('GCCZE5','wc2026-golden-crumple','gc-CZE','Rep. Tcheca','TEAM','A',5,null,null,'CZE',null,null),
('GCCZE6','wc2026-golden-crumple','gc-CZE','Rep. Tcheca','TEAM','A',6,null,null,'CZE',null,null),
('GCCZE7','wc2026-golden-crumple','gc-CZE','Rep. Tcheca','TEAM','A',7,null,null,'CZE',null,null),
('GCCZE8','wc2026-golden-crumple','gc-CZE','Rep. Tcheca','TEAM','A',8,null,null,'CZE',null,null),
('GCCZE9','wc2026-golden-crumple','gc-CZE','Rep. Tcheca','TEAM','A',9,null,null,'CZE',null,null),
('GCCZE10','wc2026-golden-crumple','gc-CZE','Rep. Tcheca','TEAM','A',10,null,null,'CZE',null,null),
('GCCZE11','wc2026-golden-crumple','gc-CZE','Rep. Tcheca','TEAM','A',11,null,null,'CZE',null,null),
('GCCZE12','wc2026-golden-crumple','gc-CZE','Rep. Tcheca','TEAM','A',12,null,null,'CZE',null,null),
('GCCZE13','wc2026-golden-crumple','gc-CZE','Rep. Tcheca','TEAM','A',13,null,null,'CZE',null,null),
('GCCZE14','wc2026-golden-crumple','gc-CZE','Rep. Tcheca','TEAM','A',14,null,null,'CZE',null,null),
('GCCZE15','wc2026-golden-crumple','gc-CZE','Rep. Tcheca','TEAM','A',15,null,null,'CZE',null,null),
('GCCZE16','wc2026-golden-crumple','gc-CZE','Rep. Tcheca','TEAM','A',16,null,null,'CZE',null,null),
('GCCZE17','wc2026-golden-crumple','gc-CZE','Rep. Tcheca','TEAM','A',17,null,null,'CZE',null,null),
('GCCZE18','wc2026-golden-crumple','gc-CZE','Rep. Tcheca','TEAM','A',18,null,null,'CZE',null,null),
('GCCZE19','wc2026-golden-crumple','gc-CZE','Rep. Tcheca','TEAM','A',19,null,null,'CZE',null,null),
('GCCZE20','wc2026-golden-crumple','gc-CZE','Rep. Tcheca','TEAM','A',20,null,null,'CZE',null,null),
('GCCAN1','wc2026-golden-crumple','gc-CAN','Canadá','TEAM','B',1,null,null,'CAN',null,null),
('GCCAN2','wc2026-golden-crumple','gc-CAN','Canadá','TEAM','B',2,null,null,'CAN',null,null),
('GCCAN3','wc2026-golden-crumple','gc-CAN','Canadá','TEAM','B',3,null,null,'CAN',null,null),
('GCCAN4','wc2026-golden-crumple','gc-CAN','Canadá','TEAM','B',4,null,null,'CAN',null,null),
('GCCAN5','wc2026-golden-crumple','gc-CAN','Canadá','TEAM','B',5,null,null,'CAN',null,null),
('GCCAN6','wc2026-golden-crumple','gc-CAN','Canadá','TEAM','B',6,null,null,'CAN',null,null),
('GCCAN7','wc2026-golden-crumple','gc-CAN','Canadá','TEAM','B',7,null,null,'CAN',null,null),
('GCCAN8','wc2026-golden-crumple','gc-CAN','Canadá','TEAM','B',8,null,null,'CAN',null,null),
('GCCAN9','wc2026-golden-crumple','gc-CAN','Canadá','TEAM','B',9,null,null,'CAN',null,null),
('GCCAN10','wc2026-golden-crumple','gc-CAN','Canadá','TEAM','B',10,null,null,'CAN',null,null),
('GCCAN11','wc2026-golden-crumple','gc-CAN','Canadá','TEAM','B',11,null,null,'CAN',null,null),
('GCCAN12','wc2026-golden-crumple','gc-CAN','Canadá','TEAM','B',12,null,null,'CAN',null,null),
('GCCAN13','wc2026-golden-crumple','gc-CAN','Canadá','TEAM','B',13,null,null,'CAN',null,null),
('GCCAN14','wc2026-golden-crumple','gc-CAN','Canadá','TEAM','B',14,null,null,'CAN',null,null),
('GCCAN15','wc2026-golden-crumple','gc-CAN','Canadá','TEAM','B',15,null,null,'CAN',null,null),
('GCCAN16','wc2026-golden-crumple','gc-CAN','Canadá','TEAM','B',16,null,null,'CAN',null,null),
('GCCAN17','wc2026-golden-crumple','gc-CAN','Canadá','TEAM','B',17,null,null,'CAN',null,null),
('GCCAN18','wc2026-golden-crumple','gc-CAN','Canadá','TEAM','B',18,null,null,'CAN',null,null),
('GCCAN19','wc2026-golden-crumple','gc-CAN','Canadá','TEAM','B',19,null,null,'CAN',null,null),
('GCCAN20','wc2026-golden-crumple','gc-CAN','Canadá','TEAM','B',20,null,null,'CAN',null,null),
('GCBIH1','wc2026-golden-crumple','gc-BIH','Bósnia','TEAM','B',1,null,null,'BIH',null,null),
('GCBIH2','wc2026-golden-crumple','gc-BIH','Bósnia','TEAM','B',2,null,null,'BIH',null,null),
('GCBIH3','wc2026-golden-crumple','gc-BIH','Bósnia','TEAM','B',3,null,null,'BIH',null,null),
('GCBIH4','wc2026-golden-crumple','gc-BIH','Bósnia','TEAM','B',4,null,null,'BIH',null,null),
('GCBIH5','wc2026-golden-crumple','gc-BIH','Bósnia','TEAM','B',5,null,null,'BIH',null,null),
('GCBIH6','wc2026-golden-crumple','gc-BIH','Bósnia','TEAM','B',6,null,null,'BIH',null,null),
('GCBIH7','wc2026-golden-crumple','gc-BIH','Bósnia','TEAM','B',7,null,null,'BIH',null,null),
('GCBIH8','wc2026-golden-crumple','gc-BIH','Bósnia','TEAM','B',8,null,null,'BIH',null,null),
('GCBIH9','wc2026-golden-crumple','gc-BIH','Bósnia','TEAM','B',9,null,null,'BIH',null,null),
('GCBIH10','wc2026-golden-crumple','gc-BIH','Bósnia','TEAM','B',10,null,null,'BIH',null,null),
('GCBIH11','wc2026-golden-crumple','gc-BIH','Bósnia','TEAM','B',11,null,null,'BIH',null,null),
('GCBIH12','wc2026-golden-crumple','gc-BIH','Bósnia','TEAM','B',12,null,null,'BIH',null,null),
('GCBIH13','wc2026-golden-crumple','gc-BIH','Bósnia','TEAM','B',13,null,null,'BIH',null,null),
('GCBIH14','wc2026-golden-crumple','gc-BIH','Bósnia','TEAM','B',14,null,null,'BIH',null,null),
('GCBIH15','wc2026-golden-crumple','gc-BIH','Bósnia','TEAM','B',15,null,null,'BIH',null,null),
('GCBIH16','wc2026-golden-crumple','gc-BIH','Bósnia','TEAM','B',16,null,null,'BIH',null,null),
('GCBIH17','wc2026-golden-crumple','gc-BIH','Bósnia','TEAM','B',17,null,null,'BIH',null,null),
('GCBIH18','wc2026-golden-crumple','gc-BIH','Bósnia','TEAM','B',18,null,null,'BIH',null,null),
('GCBIH19','wc2026-golden-crumple','gc-BIH','Bósnia','TEAM','B',19,null,null,'BIH',null,null),
('GCBIH20','wc2026-golden-crumple','gc-BIH','Bósnia','TEAM','B',20,null,null,'BIH',null,null),
('GCQAT1','wc2026-golden-crumple','gc-QAT','Catar','TEAM','B',1,null,null,'QAT',null,null),
('GCQAT2','wc2026-golden-crumple','gc-QAT','Catar','TEAM','B',2,null,null,'QAT',null,null),
('GCQAT3','wc2026-golden-crumple','gc-QAT','Catar','TEAM','B',3,null,null,'QAT',null,null),
('GCQAT4','wc2026-golden-crumple','gc-QAT','Catar','TEAM','B',4,null,null,'QAT',null,null),
('GCQAT5','wc2026-golden-crumple','gc-QAT','Catar','TEAM','B',5,null,null,'QAT',null,null),
('GCQAT6','wc2026-golden-crumple','gc-QAT','Catar','TEAM','B',6,null,null,'QAT',null,null),
('GCQAT7','wc2026-golden-crumple','gc-QAT','Catar','TEAM','B',7,null,null,'QAT',null,null),
('GCQAT8','wc2026-golden-crumple','gc-QAT','Catar','TEAM','B',8,null,null,'QAT',null,null),
('GCQAT9','wc2026-golden-crumple','gc-QAT','Catar','TEAM','B',9,null,null,'QAT',null,null),
('GCQAT10','wc2026-golden-crumple','gc-QAT','Catar','TEAM','B',10,null,null,'QAT',null,null),
('GCQAT11','wc2026-golden-crumple','gc-QAT','Catar','TEAM','B',11,null,null,'QAT',null,null),
('GCQAT12','wc2026-golden-crumple','gc-QAT','Catar','TEAM','B',12,null,null,'QAT',null,null),
('GCQAT13','wc2026-golden-crumple','gc-QAT','Catar','TEAM','B',13,null,null,'QAT',null,null),
('GCQAT14','wc2026-golden-crumple','gc-QAT','Catar','TEAM','B',14,null,null,'QAT',null,null),
('GCQAT15','wc2026-golden-crumple','gc-QAT','Catar','TEAM','B',15,null,null,'QAT',null,null),
('GCQAT16','wc2026-golden-crumple','gc-QAT','Catar','TEAM','B',16,null,null,'QAT',null,null),
('GCQAT17','wc2026-golden-crumple','gc-QAT','Catar','TEAM','B',17,null,null,'QAT',null,null),
('GCQAT18','wc2026-golden-crumple','gc-QAT','Catar','TEAM','B',18,null,null,'QAT',null,null),
('GCQAT19','wc2026-golden-crumple','gc-QAT','Catar','TEAM','B',19,null,null,'QAT',null,null),
('GCQAT20','wc2026-golden-crumple','gc-QAT','Catar','TEAM','B',20,null,null,'QAT',null,null),
('GCSUI1','wc2026-golden-crumple','gc-SUI','Suíça','TEAM','B',1,null,null,'SUI',null,null),
('GCSUI2','wc2026-golden-crumple','gc-SUI','Suíça','TEAM','B',2,null,null,'SUI',null,null),
('GCSUI3','wc2026-golden-crumple','gc-SUI','Suíça','TEAM','B',3,null,null,'SUI',null,null),
('GCSUI4','wc2026-golden-crumple','gc-SUI','Suíça','TEAM','B',4,null,null,'SUI',null,null),
('GCSUI5','wc2026-golden-crumple','gc-SUI','Suíça','TEAM','B',5,null,null,'SUI',null,null),
('GCSUI6','wc2026-golden-crumple','gc-SUI','Suíça','TEAM','B',6,null,null,'SUI',null,null),
('GCSUI7','wc2026-golden-crumple','gc-SUI','Suíça','TEAM','B',7,null,null,'SUI',null,null),
('GCSUI8','wc2026-golden-crumple','gc-SUI','Suíça','TEAM','B',8,null,null,'SUI',null,null),
('GCSUI9','wc2026-golden-crumple','gc-SUI','Suíça','TEAM','B',9,null,null,'SUI',null,null),
('GCSUI10','wc2026-golden-crumple','gc-SUI','Suíça','TEAM','B',10,null,null,'SUI',null,null),
('GCSUI11','wc2026-golden-crumple','gc-SUI','Suíça','TEAM','B',11,null,null,'SUI',null,null),
('GCSUI12','wc2026-golden-crumple','gc-SUI','Suíça','TEAM','B',12,null,null,'SUI',null,null),
('GCSUI13','wc2026-golden-crumple','gc-SUI','Suíça','TEAM','B',13,null,null,'SUI',null,null),
('GCSUI14','wc2026-golden-crumple','gc-SUI','Suíça','TEAM','B',14,null,null,'SUI',null,null),
('GCSUI15','wc2026-golden-crumple','gc-SUI','Suíça','TEAM','B',15,null,null,'SUI',null,null),
('GCSUI16','wc2026-golden-crumple','gc-SUI','Suíça','TEAM','B',16,null,null,'SUI',null,null),
('GCSUI17','wc2026-golden-crumple','gc-SUI','Suíça','TEAM','B',17,null,null,'SUI',null,null),
('GCSUI18','wc2026-golden-crumple','gc-SUI','Suíça','TEAM','B',18,null,null,'SUI',null,null),
('GCSUI19','wc2026-golden-crumple','gc-SUI','Suíça','TEAM','B',19,null,null,'SUI',null,null),
('GCSUI20','wc2026-golden-crumple','gc-SUI','Suíça','TEAM','B',20,null,null,'SUI',null,null),
('GCBRA1','wc2026-golden-crumple','gc-BRA','Brasil','TEAM','C',1,null,null,'BRA',null,null),
('GCBRA2','wc2026-golden-crumple','gc-BRA','Brasil','TEAM','C',2,null,null,'BRA',null,null),
('GCBRA3','wc2026-golden-crumple','gc-BRA','Brasil','TEAM','C',3,null,null,'BRA',null,null),
('GCBRA4','wc2026-golden-crumple','gc-BRA','Brasil','TEAM','C',4,null,null,'BRA',null,null),
('GCBRA5','wc2026-golden-crumple','gc-BRA','Brasil','TEAM','C',5,null,null,'BRA',null,null),
('GCBRA6','wc2026-golden-crumple','gc-BRA','Brasil','TEAM','C',6,null,null,'BRA',null,null),
('GCBRA7','wc2026-golden-crumple','gc-BRA','Brasil','TEAM','C',7,null,null,'BRA',null,null),
('GCBRA8','wc2026-golden-crumple','gc-BRA','Brasil','TEAM','C',8,null,null,'BRA',null,null),
('GCBRA9','wc2026-golden-crumple','gc-BRA','Brasil','TEAM','C',9,null,null,'BRA',null,null),
('GCBRA10','wc2026-golden-crumple','gc-BRA','Brasil','TEAM','C',10,null,null,'BRA',null,null),
('GCBRA11','wc2026-golden-crumple','gc-BRA','Brasil','TEAM','C',11,null,null,'BRA',null,null),
('GCBRA12','wc2026-golden-crumple','gc-BRA','Brasil','TEAM','C',12,null,null,'BRA',null,null),
('GCBRA13','wc2026-golden-crumple','gc-BRA','Brasil','TEAM','C',13,null,null,'BRA',null,null),
('GCBRA14','wc2026-golden-crumple','gc-BRA','Brasil','TEAM','C',14,null,null,'BRA',null,null),
('GCBRA15','wc2026-golden-crumple','gc-BRA','Brasil','TEAM','C',15,null,null,'BRA',null,null),
('GCBRA16','wc2026-golden-crumple','gc-BRA','Brasil','TEAM','C',16,null,null,'BRA',null,null),
('GCBRA17','wc2026-golden-crumple','gc-BRA','Brasil','TEAM','C',17,null,null,'BRA',null,null),
('GCBRA18','wc2026-golden-crumple','gc-BRA','Brasil','TEAM','C',18,null,null,'BRA',null,null),
('GCBRA19','wc2026-golden-crumple','gc-BRA','Brasil','TEAM','C',19,null,null,'BRA',null,null),
('GCBRA20','wc2026-golden-crumple','gc-BRA','Brasil','TEAM','C',20,null,null,'BRA',null,null),
('GCMAR1','wc2026-golden-crumple','gc-MAR','Marrocos','TEAM','C',1,null,null,'MAR',null,null),
('GCMAR2','wc2026-golden-crumple','gc-MAR','Marrocos','TEAM','C',2,null,null,'MAR',null,null),
('GCMAR3','wc2026-golden-crumple','gc-MAR','Marrocos','TEAM','C',3,null,null,'MAR',null,null),
('GCMAR4','wc2026-golden-crumple','gc-MAR','Marrocos','TEAM','C',4,null,null,'MAR',null,null),
('GCMAR5','wc2026-golden-crumple','gc-MAR','Marrocos','TEAM','C',5,null,null,'MAR',null,null),
('GCMAR6','wc2026-golden-crumple','gc-MAR','Marrocos','TEAM','C',6,null,null,'MAR',null,null),
('GCMAR7','wc2026-golden-crumple','gc-MAR','Marrocos','TEAM','C',7,null,null,'MAR',null,null),
('GCMAR8','wc2026-golden-crumple','gc-MAR','Marrocos','TEAM','C',8,null,null,'MAR',null,null),
('GCMAR9','wc2026-golden-crumple','gc-MAR','Marrocos','TEAM','C',9,null,null,'MAR',null,null),
('GCMAR10','wc2026-golden-crumple','gc-MAR','Marrocos','TEAM','C',10,null,null,'MAR',null,null),
('GCMAR11','wc2026-golden-crumple','gc-MAR','Marrocos','TEAM','C',11,null,null,'MAR',null,null),
('GCMAR12','wc2026-golden-crumple','gc-MAR','Marrocos','TEAM','C',12,null,null,'MAR',null,null),
('GCMAR13','wc2026-golden-crumple','gc-MAR','Marrocos','TEAM','C',13,null,null,'MAR',null,null),
('GCMAR14','wc2026-golden-crumple','gc-MAR','Marrocos','TEAM','C',14,null,null,'MAR',null,null),
('GCMAR15','wc2026-golden-crumple','gc-MAR','Marrocos','TEAM','C',15,null,null,'MAR',null,null),
('GCMAR16','wc2026-golden-crumple','gc-MAR','Marrocos','TEAM','C',16,null,null,'MAR',null,null),
('GCMAR17','wc2026-golden-crumple','gc-MAR','Marrocos','TEAM','C',17,null,null,'MAR',null,null),
('GCMAR18','wc2026-golden-crumple','gc-MAR','Marrocos','TEAM','C',18,null,null,'MAR',null,null),
('GCMAR19','wc2026-golden-crumple','gc-MAR','Marrocos','TEAM','C',19,null,null,'MAR',null,null),
('GCMAR20','wc2026-golden-crumple','gc-MAR','Marrocos','TEAM','C',20,null,null,'MAR',null,null),
('GCHAI1','wc2026-golden-crumple','gc-HAI','Haiti','TEAM','C',1,null,null,'HAI',null,null),
('GCHAI2','wc2026-golden-crumple','gc-HAI','Haiti','TEAM','C',2,null,null,'HAI',null,null),
('GCHAI3','wc2026-golden-crumple','gc-HAI','Haiti','TEAM','C',3,null,null,'HAI',null,null),
('GCHAI4','wc2026-golden-crumple','gc-HAI','Haiti','TEAM','C',4,null,null,'HAI',null,null),
('GCHAI5','wc2026-golden-crumple','gc-HAI','Haiti','TEAM','C',5,null,null,'HAI',null,null),
('GCHAI6','wc2026-golden-crumple','gc-HAI','Haiti','TEAM','C',6,null,null,'HAI',null,null),
('GCHAI7','wc2026-golden-crumple','gc-HAI','Haiti','TEAM','C',7,null,null,'HAI',null,null),
('GCHAI8','wc2026-golden-crumple','gc-HAI','Haiti','TEAM','C',8,null,null,'HAI',null,null),
('GCHAI9','wc2026-golden-crumple','gc-HAI','Haiti','TEAM','C',9,null,null,'HAI',null,null),
('GCHAI10','wc2026-golden-crumple','gc-HAI','Haiti','TEAM','C',10,null,null,'HAI',null,null),
('GCHAI11','wc2026-golden-crumple','gc-HAI','Haiti','TEAM','C',11,null,null,'HAI',null,null),
('GCHAI12','wc2026-golden-crumple','gc-HAI','Haiti','TEAM','C',12,null,null,'HAI',null,null),
('GCHAI13','wc2026-golden-crumple','gc-HAI','Haiti','TEAM','C',13,null,null,'HAI',null,null),
('GCHAI14','wc2026-golden-crumple','gc-HAI','Haiti','TEAM','C',14,null,null,'HAI',null,null),
('GCHAI15','wc2026-golden-crumple','gc-HAI','Haiti','TEAM','C',15,null,null,'HAI',null,null),
('GCHAI16','wc2026-golden-crumple','gc-HAI','Haiti','TEAM','C',16,null,null,'HAI',null,null),
('GCHAI17','wc2026-golden-crumple','gc-HAI','Haiti','TEAM','C',17,null,null,'HAI',null,null),
('GCHAI18','wc2026-golden-crumple','gc-HAI','Haiti','TEAM','C',18,null,null,'HAI',null,null),
('GCHAI19','wc2026-golden-crumple','gc-HAI','Haiti','TEAM','C',19,null,null,'HAI',null,null),
('GCHAI20','wc2026-golden-crumple','gc-HAI','Haiti','TEAM','C',20,null,null,'HAI',null,null),
('GCSCO1','wc2026-golden-crumple','gc-SCO','Escócia','TEAM','C',1,null,null,'SCO',null,null),
('GCSCO2','wc2026-golden-crumple','gc-SCO','Escócia','TEAM','C',2,null,null,'SCO',null,null),
('GCSCO3','wc2026-golden-crumple','gc-SCO','Escócia','TEAM','C',3,null,null,'SCO',null,null),
('GCSCO4','wc2026-golden-crumple','gc-SCO','Escócia','TEAM','C',4,null,null,'SCO',null,null),
('GCSCO5','wc2026-golden-crumple','gc-SCO','Escócia','TEAM','C',5,null,null,'SCO',null,null),
('GCSCO6','wc2026-golden-crumple','gc-SCO','Escócia','TEAM','C',6,null,null,'SCO',null,null),
('GCSCO7','wc2026-golden-crumple','gc-SCO','Escócia','TEAM','C',7,null,null,'SCO',null,null),
('GCSCO8','wc2026-golden-crumple','gc-SCO','Escócia','TEAM','C',8,null,null,'SCO',null,null),
('GCSCO9','wc2026-golden-crumple','gc-SCO','Escócia','TEAM','C',9,null,null,'SCO',null,null),
('GCSCO10','wc2026-golden-crumple','gc-SCO','Escócia','TEAM','C',10,null,null,'SCO',null,null),
('GCSCO11','wc2026-golden-crumple','gc-SCO','Escócia','TEAM','C',11,null,null,'SCO',null,null),
('GCSCO12','wc2026-golden-crumple','gc-SCO','Escócia','TEAM','C',12,null,null,'SCO',null,null),
('GCSCO13','wc2026-golden-crumple','gc-SCO','Escócia','TEAM','C',13,null,null,'SCO',null,null),
('GCSCO14','wc2026-golden-crumple','gc-SCO','Escócia','TEAM','C',14,null,null,'SCO',null,null),
('GCSCO15','wc2026-golden-crumple','gc-SCO','Escócia','TEAM','C',15,null,null,'SCO',null,null),
('GCSCO16','wc2026-golden-crumple','gc-SCO','Escócia','TEAM','C',16,null,null,'SCO',null,null),
('GCSCO17','wc2026-golden-crumple','gc-SCO','Escócia','TEAM','C',17,null,null,'SCO',null,null),
('GCSCO18','wc2026-golden-crumple','gc-SCO','Escócia','TEAM','C',18,null,null,'SCO',null,null),
('GCSCO19','wc2026-golden-crumple','gc-SCO','Escócia','TEAM','C',19,null,null,'SCO',null,null),
('GCSCO20','wc2026-golden-crumple','gc-SCO','Escócia','TEAM','C',20,null,null,'SCO',null,null),
('GCUSA1','wc2026-golden-crumple','gc-USA','Estados Unidos','TEAM','D',1,null,null,'USA',null,null),
('GCUSA2','wc2026-golden-crumple','gc-USA','Estados Unidos','TEAM','D',2,null,null,'USA',null,null),
('GCUSA3','wc2026-golden-crumple','gc-USA','Estados Unidos','TEAM','D',3,null,null,'USA',null,null),
('GCUSA4','wc2026-golden-crumple','gc-USA','Estados Unidos','TEAM','D',4,null,null,'USA',null,null),
('GCUSA5','wc2026-golden-crumple','gc-USA','Estados Unidos','TEAM','D',5,null,null,'USA',null,null),
('GCUSA6','wc2026-golden-crumple','gc-USA','Estados Unidos','TEAM','D',6,null,null,'USA',null,null),
('GCUSA7','wc2026-golden-crumple','gc-USA','Estados Unidos','TEAM','D',7,null,null,'USA',null,null),
('GCUSA8','wc2026-golden-crumple','gc-USA','Estados Unidos','TEAM','D',8,null,null,'USA',null,null),
('GCUSA9','wc2026-golden-crumple','gc-USA','Estados Unidos','TEAM','D',9,null,null,'USA',null,null),
('GCUSA10','wc2026-golden-crumple','gc-USA','Estados Unidos','TEAM','D',10,null,null,'USA',null,null),
('GCUSA11','wc2026-golden-crumple','gc-USA','Estados Unidos','TEAM','D',11,null,null,'USA',null,null),
('GCUSA12','wc2026-golden-crumple','gc-USA','Estados Unidos','TEAM','D',12,null,null,'USA',null,null),
('GCUSA13','wc2026-golden-crumple','gc-USA','Estados Unidos','TEAM','D',13,null,null,'USA',null,null),
('GCUSA14','wc2026-golden-crumple','gc-USA','Estados Unidos','TEAM','D',14,null,null,'USA',null,null),
('GCUSA15','wc2026-golden-crumple','gc-USA','Estados Unidos','TEAM','D',15,null,null,'USA',null,null),
('GCUSA16','wc2026-golden-crumple','gc-USA','Estados Unidos','TEAM','D',16,null,null,'USA',null,null),
('GCUSA17','wc2026-golden-crumple','gc-USA','Estados Unidos','TEAM','D',17,null,null,'USA',null,null),
('GCUSA18','wc2026-golden-crumple','gc-USA','Estados Unidos','TEAM','D',18,null,null,'USA',null,null),
('GCUSA19','wc2026-golden-crumple','gc-USA','Estados Unidos','TEAM','D',19,null,null,'USA',null,null),
('GCUSA20','wc2026-golden-crumple','gc-USA','Estados Unidos','TEAM','D',20,null,null,'USA',null,null),
('GCPAR1','wc2026-golden-crumple','gc-PAR','Paraguai','TEAM','D',1,null,null,'PAR',null,null),
('GCPAR2','wc2026-golden-crumple','gc-PAR','Paraguai','TEAM','D',2,null,null,'PAR',null,null),
('GCPAR3','wc2026-golden-crumple','gc-PAR','Paraguai','TEAM','D',3,null,null,'PAR',null,null),
('GCPAR4','wc2026-golden-crumple','gc-PAR','Paraguai','TEAM','D',4,null,null,'PAR',null,null),
('GCPAR5','wc2026-golden-crumple','gc-PAR','Paraguai','TEAM','D',5,null,null,'PAR',null,null),
('GCPAR6','wc2026-golden-crumple','gc-PAR','Paraguai','TEAM','D',6,null,null,'PAR',null,null),
('GCPAR7','wc2026-golden-crumple','gc-PAR','Paraguai','TEAM','D',7,null,null,'PAR',null,null),
('GCPAR8','wc2026-golden-crumple','gc-PAR','Paraguai','TEAM','D',8,null,null,'PAR',null,null),
('GCPAR9','wc2026-golden-crumple','gc-PAR','Paraguai','TEAM','D',9,null,null,'PAR',null,null),
('GCPAR10','wc2026-golden-crumple','gc-PAR','Paraguai','TEAM','D',10,null,null,'PAR',null,null),
('GCPAR11','wc2026-golden-crumple','gc-PAR','Paraguai','TEAM','D',11,null,null,'PAR',null,null),
('GCPAR12','wc2026-golden-crumple','gc-PAR','Paraguai','TEAM','D',12,null,null,'PAR',null,null),
('GCPAR13','wc2026-golden-crumple','gc-PAR','Paraguai','TEAM','D',13,null,null,'PAR',null,null),
('GCPAR14','wc2026-golden-crumple','gc-PAR','Paraguai','TEAM','D',14,null,null,'PAR',null,null),
('GCPAR15','wc2026-golden-crumple','gc-PAR','Paraguai','TEAM','D',15,null,null,'PAR',null,null),
('GCPAR16','wc2026-golden-crumple','gc-PAR','Paraguai','TEAM','D',16,null,null,'PAR',null,null),
('GCPAR17','wc2026-golden-crumple','gc-PAR','Paraguai','TEAM','D',17,null,null,'PAR',null,null),
('GCPAR18','wc2026-golden-crumple','gc-PAR','Paraguai','TEAM','D',18,null,null,'PAR',null,null),
('GCPAR19','wc2026-golden-crumple','gc-PAR','Paraguai','TEAM','D',19,null,null,'PAR',null,null),
('GCPAR20','wc2026-golden-crumple','gc-PAR','Paraguai','TEAM','D',20,null,null,'PAR',null,null),
('GCAUS1','wc2026-golden-crumple','gc-AUS','Austrália','TEAM','D',1,null,null,'AUS',null,null),
('GCAUS2','wc2026-golden-crumple','gc-AUS','Austrália','TEAM','D',2,null,null,'AUS',null,null),
('GCAUS3','wc2026-golden-crumple','gc-AUS','Austrália','TEAM','D',3,null,null,'AUS',null,null),
('GCAUS4','wc2026-golden-crumple','gc-AUS','Austrália','TEAM','D',4,null,null,'AUS',null,null),
('GCAUS5','wc2026-golden-crumple','gc-AUS','Austrália','TEAM','D',5,null,null,'AUS',null,null),
('GCAUS6','wc2026-golden-crumple','gc-AUS','Austrália','TEAM','D',6,null,null,'AUS',null,null),
('GCAUS7','wc2026-golden-crumple','gc-AUS','Austrália','TEAM','D',7,null,null,'AUS',null,null),
('GCAUS8','wc2026-golden-crumple','gc-AUS','Austrália','TEAM','D',8,null,null,'AUS',null,null),
('GCAUS9','wc2026-golden-crumple','gc-AUS','Austrália','TEAM','D',9,null,null,'AUS',null,null),
('GCAUS10','wc2026-golden-crumple','gc-AUS','Austrália','TEAM','D',10,null,null,'AUS',null,null),
('GCAUS11','wc2026-golden-crumple','gc-AUS','Austrália','TEAM','D',11,null,null,'AUS',null,null),
('GCAUS12','wc2026-golden-crumple','gc-AUS','Austrália','TEAM','D',12,null,null,'AUS',null,null),
('GCAUS13','wc2026-golden-crumple','gc-AUS','Austrália','TEAM','D',13,null,null,'AUS',null,null),
('GCAUS14','wc2026-golden-crumple','gc-AUS','Austrália','TEAM','D',14,null,null,'AUS',null,null),
('GCAUS15','wc2026-golden-crumple','gc-AUS','Austrália','TEAM','D',15,null,null,'AUS',null,null),
('GCAUS16','wc2026-golden-crumple','gc-AUS','Austrália','TEAM','D',16,null,null,'AUS',null,null),
('GCAUS17','wc2026-golden-crumple','gc-AUS','Austrália','TEAM','D',17,null,null,'AUS',null,null),
('GCAUS18','wc2026-golden-crumple','gc-AUS','Austrália','TEAM','D',18,null,null,'AUS',null,null),
('GCAUS19','wc2026-golden-crumple','gc-AUS','Austrália','TEAM','D',19,null,null,'AUS',null,null),
('GCAUS20','wc2026-golden-crumple','gc-AUS','Austrália','TEAM','D',20,null,null,'AUS',null,null),
('GCTUR1','wc2026-golden-crumple','gc-TUR','Turquia','TEAM','D',1,null,null,'TUR',null,null),
('GCTUR2','wc2026-golden-crumple','gc-TUR','Turquia','TEAM','D',2,null,null,'TUR',null,null),
('GCTUR3','wc2026-golden-crumple','gc-TUR','Turquia','TEAM','D',3,null,null,'TUR',null,null),
('GCTUR4','wc2026-golden-crumple','gc-TUR','Turquia','TEAM','D',4,null,null,'TUR',null,null),
('GCTUR5','wc2026-golden-crumple','gc-TUR','Turquia','TEAM','D',5,null,null,'TUR',null,null),
('GCTUR6','wc2026-golden-crumple','gc-TUR','Turquia','TEAM','D',6,null,null,'TUR',null,null),
('GCTUR7','wc2026-golden-crumple','gc-TUR','Turquia','TEAM','D',7,null,null,'TUR',null,null),
('GCTUR8','wc2026-golden-crumple','gc-TUR','Turquia','TEAM','D',8,null,null,'TUR',null,null),
('GCTUR9','wc2026-golden-crumple','gc-TUR','Turquia','TEAM','D',9,null,null,'TUR',null,null),
('GCTUR10','wc2026-golden-crumple','gc-TUR','Turquia','TEAM','D',10,null,null,'TUR',null,null),
('GCTUR11','wc2026-golden-crumple','gc-TUR','Turquia','TEAM','D',11,null,null,'TUR',null,null),
('GCTUR12','wc2026-golden-crumple','gc-TUR','Turquia','TEAM','D',12,null,null,'TUR',null,null),
('GCTUR13','wc2026-golden-crumple','gc-TUR','Turquia','TEAM','D',13,null,null,'TUR',null,null),
('GCTUR14','wc2026-golden-crumple','gc-TUR','Turquia','TEAM','D',14,null,null,'TUR',null,null),
('GCTUR15','wc2026-golden-crumple','gc-TUR','Turquia','TEAM','D',15,null,null,'TUR',null,null),
('GCTUR16','wc2026-golden-crumple','gc-TUR','Turquia','TEAM','D',16,null,null,'TUR',null,null),
('GCTUR17','wc2026-golden-crumple','gc-TUR','Turquia','TEAM','D',17,null,null,'TUR',null,null),
('GCTUR18','wc2026-golden-crumple','gc-TUR','Turquia','TEAM','D',18,null,null,'TUR',null,null),
('GCTUR19','wc2026-golden-crumple','gc-TUR','Turquia','TEAM','D',19,null,null,'TUR',null,null),
('GCTUR20','wc2026-golden-crumple','gc-TUR','Turquia','TEAM','D',20,null,null,'TUR',null,null),
('GCGER1','wc2026-golden-crumple','gc-GER','Alemanha','TEAM','E',1,null,null,'GER',null,null),
('GCGER2','wc2026-golden-crumple','gc-GER','Alemanha','TEAM','E',2,null,null,'GER',null,null),
('GCGER3','wc2026-golden-crumple','gc-GER','Alemanha','TEAM','E',3,null,null,'GER',null,null),
('GCGER4','wc2026-golden-crumple','gc-GER','Alemanha','TEAM','E',4,null,null,'GER',null,null),
('GCGER5','wc2026-golden-crumple','gc-GER','Alemanha','TEAM','E',5,null,null,'GER',null,null),
('GCGER6','wc2026-golden-crumple','gc-GER','Alemanha','TEAM','E',6,null,null,'GER',null,null),
('GCGER7','wc2026-golden-crumple','gc-GER','Alemanha','TEAM','E',7,null,null,'GER',null,null),
('GCGER8','wc2026-golden-crumple','gc-GER','Alemanha','TEAM','E',8,null,null,'GER',null,null),
('GCGER9','wc2026-golden-crumple','gc-GER','Alemanha','TEAM','E',9,null,null,'GER',null,null),
('GCGER10','wc2026-golden-crumple','gc-GER','Alemanha','TEAM','E',10,null,null,'GER',null,null),
('GCGER11','wc2026-golden-crumple','gc-GER','Alemanha','TEAM','E',11,null,null,'GER',null,null),
('GCGER12','wc2026-golden-crumple','gc-GER','Alemanha','TEAM','E',12,null,null,'GER',null,null),
('GCGER13','wc2026-golden-crumple','gc-GER','Alemanha','TEAM','E',13,null,null,'GER',null,null),
('GCGER14','wc2026-golden-crumple','gc-GER','Alemanha','TEAM','E',14,null,null,'GER',null,null),
('GCGER15','wc2026-golden-crumple','gc-GER','Alemanha','TEAM','E',15,null,null,'GER',null,null),
('GCGER16','wc2026-golden-crumple','gc-GER','Alemanha','TEAM','E',16,null,null,'GER',null,null),
('GCGER17','wc2026-golden-crumple','gc-GER','Alemanha','TEAM','E',17,null,null,'GER',null,null),
('GCGER18','wc2026-golden-crumple','gc-GER','Alemanha','TEAM','E',18,null,null,'GER',null,null),
('GCGER19','wc2026-golden-crumple','gc-GER','Alemanha','TEAM','E',19,null,null,'GER',null,null),
('GCGER20','wc2026-golden-crumple','gc-GER','Alemanha','TEAM','E',20,null,null,'GER',null,null),
('GCCUW1','wc2026-golden-crumple','gc-CUW','Curaçao','TEAM','E',1,null,null,'CUW',null,null),
('GCCUW2','wc2026-golden-crumple','gc-CUW','Curaçao','TEAM','E',2,null,null,'CUW',null,null),
('GCCUW3','wc2026-golden-crumple','gc-CUW','Curaçao','TEAM','E',3,null,null,'CUW',null,null),
('GCCUW4','wc2026-golden-crumple','gc-CUW','Curaçao','TEAM','E',4,null,null,'CUW',null,null),
('GCCUW5','wc2026-golden-crumple','gc-CUW','Curaçao','TEAM','E',5,null,null,'CUW',null,null),
('GCCUW6','wc2026-golden-crumple','gc-CUW','Curaçao','TEAM','E',6,null,null,'CUW',null,null),
('GCCUW7','wc2026-golden-crumple','gc-CUW','Curaçao','TEAM','E',7,null,null,'CUW',null,null),
('GCCUW8','wc2026-golden-crumple','gc-CUW','Curaçao','TEAM','E',8,null,null,'CUW',null,null),
('GCCUW9','wc2026-golden-crumple','gc-CUW','Curaçao','TEAM','E',9,null,null,'CUW',null,null),
('GCCUW10','wc2026-golden-crumple','gc-CUW','Curaçao','TEAM','E',10,null,null,'CUW',null,null),
('GCCUW11','wc2026-golden-crumple','gc-CUW','Curaçao','TEAM','E',11,null,null,'CUW',null,null),
('GCCUW12','wc2026-golden-crumple','gc-CUW','Curaçao','TEAM','E',12,null,null,'CUW',null,null),
('GCCUW13','wc2026-golden-crumple','gc-CUW','Curaçao','TEAM','E',13,null,null,'CUW',null,null),
('GCCUW14','wc2026-golden-crumple','gc-CUW','Curaçao','TEAM','E',14,null,null,'CUW',null,null),
('GCCUW15','wc2026-golden-crumple','gc-CUW','Curaçao','TEAM','E',15,null,null,'CUW',null,null),
('GCCUW16','wc2026-golden-crumple','gc-CUW','Curaçao','TEAM','E',16,null,null,'CUW',null,null),
('GCCUW17','wc2026-golden-crumple','gc-CUW','Curaçao','TEAM','E',17,null,null,'CUW',null,null),
('GCCUW18','wc2026-golden-crumple','gc-CUW','Curaçao','TEAM','E',18,null,null,'CUW',null,null),
('GCCUW19','wc2026-golden-crumple','gc-CUW','Curaçao','TEAM','E',19,null,null,'CUW',null,null),
('GCCUW20','wc2026-golden-crumple','gc-CUW','Curaçao','TEAM','E',20,null,null,'CUW',null,null),
('GCCIV1','wc2026-golden-crumple','gc-CIV','Costa do Marfim','TEAM','E',1,null,null,'CIV',null,null),
('GCCIV2','wc2026-golden-crumple','gc-CIV','Costa do Marfim','TEAM','E',2,null,null,'CIV',null,null),
('GCCIV3','wc2026-golden-crumple','gc-CIV','Costa do Marfim','TEAM','E',3,null,null,'CIV',null,null),
('GCCIV4','wc2026-golden-crumple','gc-CIV','Costa do Marfim','TEAM','E',4,null,null,'CIV',null,null),
('GCCIV5','wc2026-golden-crumple','gc-CIV','Costa do Marfim','TEAM','E',5,null,null,'CIV',null,null),
('GCCIV6','wc2026-golden-crumple','gc-CIV','Costa do Marfim','TEAM','E',6,null,null,'CIV',null,null),
('GCCIV7','wc2026-golden-crumple','gc-CIV','Costa do Marfim','TEAM','E',7,null,null,'CIV',null,null),
('GCCIV8','wc2026-golden-crumple','gc-CIV','Costa do Marfim','TEAM','E',8,null,null,'CIV',null,null),
('GCCIV9','wc2026-golden-crumple','gc-CIV','Costa do Marfim','TEAM','E',9,null,null,'CIV',null,null),
('GCCIV10','wc2026-golden-crumple','gc-CIV','Costa do Marfim','TEAM','E',10,null,null,'CIV',null,null),
('GCCIV11','wc2026-golden-crumple','gc-CIV','Costa do Marfim','TEAM','E',11,null,null,'CIV',null,null),
('GCCIV12','wc2026-golden-crumple','gc-CIV','Costa do Marfim','TEAM','E',12,null,null,'CIV',null,null),
('GCCIV13','wc2026-golden-crumple','gc-CIV','Costa do Marfim','TEAM','E',13,null,null,'CIV',null,null),
('GCCIV14','wc2026-golden-crumple','gc-CIV','Costa do Marfim','TEAM','E',14,null,null,'CIV',null,null),
('GCCIV15','wc2026-golden-crumple','gc-CIV','Costa do Marfim','TEAM','E',15,null,null,'CIV',null,null),
('GCCIV16','wc2026-golden-crumple','gc-CIV','Costa do Marfim','TEAM','E',16,null,null,'CIV',null,null),
('GCCIV17','wc2026-golden-crumple','gc-CIV','Costa do Marfim','TEAM','E',17,null,null,'CIV',null,null),
('GCCIV18','wc2026-golden-crumple','gc-CIV','Costa do Marfim','TEAM','E',18,null,null,'CIV',null,null),
('GCCIV19','wc2026-golden-crumple','gc-CIV','Costa do Marfim','TEAM','E',19,null,null,'CIV',null,null),
('GCCIV20','wc2026-golden-crumple','gc-CIV','Costa do Marfim','TEAM','E',20,null,null,'CIV',null,null),
('GCECU1','wc2026-golden-crumple','gc-ECU','Equador','TEAM','E',1,null,null,'ECU',null,null),
('GCECU2','wc2026-golden-crumple','gc-ECU','Equador','TEAM','E',2,null,null,'ECU',null,null),
('GCECU3','wc2026-golden-crumple','gc-ECU','Equador','TEAM','E',3,null,null,'ECU',null,null),
('GCECU4','wc2026-golden-crumple','gc-ECU','Equador','TEAM','E',4,null,null,'ECU',null,null),
('GCECU5','wc2026-golden-crumple','gc-ECU','Equador','TEAM','E',5,null,null,'ECU',null,null),
('GCECU6','wc2026-golden-crumple','gc-ECU','Equador','TEAM','E',6,null,null,'ECU',null,null),
('GCECU7','wc2026-golden-crumple','gc-ECU','Equador','TEAM','E',7,null,null,'ECU',null,null),
('GCECU8','wc2026-golden-crumple','gc-ECU','Equador','TEAM','E',8,null,null,'ECU',null,null),
('GCECU9','wc2026-golden-crumple','gc-ECU','Equador','TEAM','E',9,null,null,'ECU',null,null),
('GCECU10','wc2026-golden-crumple','gc-ECU','Equador','TEAM','E',10,null,null,'ECU',null,null),
('GCECU11','wc2026-golden-crumple','gc-ECU','Equador','TEAM','E',11,null,null,'ECU',null,null),
('GCECU12','wc2026-golden-crumple','gc-ECU','Equador','TEAM','E',12,null,null,'ECU',null,null),
('GCECU13','wc2026-golden-crumple','gc-ECU','Equador','TEAM','E',13,null,null,'ECU',null,null),
('GCECU14','wc2026-golden-crumple','gc-ECU','Equador','TEAM','E',14,null,null,'ECU',null,null),
('GCECU15','wc2026-golden-crumple','gc-ECU','Equador','TEAM','E',15,null,null,'ECU',null,null),
('GCECU16','wc2026-golden-crumple','gc-ECU','Equador','TEAM','E',16,null,null,'ECU',null,null),
('GCECU17','wc2026-golden-crumple','gc-ECU','Equador','TEAM','E',17,null,null,'ECU',null,null),
('GCECU18','wc2026-golden-crumple','gc-ECU','Equador','TEAM','E',18,null,null,'ECU',null,null),
('GCECU19','wc2026-golden-crumple','gc-ECU','Equador','TEAM','E',19,null,null,'ECU',null,null),
('GCECU20','wc2026-golden-crumple','gc-ECU','Equador','TEAM','E',20,null,null,'ECU',null,null),
('GCNED1','wc2026-golden-crumple','gc-NED','Holanda','TEAM','F',1,null,null,'NED',null,null),
('GCNED2','wc2026-golden-crumple','gc-NED','Holanda','TEAM','F',2,null,null,'NED',null,null),
('GCNED3','wc2026-golden-crumple','gc-NED','Holanda','TEAM','F',3,null,null,'NED',null,null),
('GCNED4','wc2026-golden-crumple','gc-NED','Holanda','TEAM','F',4,null,null,'NED',null,null),
('GCNED5','wc2026-golden-crumple','gc-NED','Holanda','TEAM','F',5,null,null,'NED',null,null),
('GCNED6','wc2026-golden-crumple','gc-NED','Holanda','TEAM','F',6,null,null,'NED',null,null),
('GCNED7','wc2026-golden-crumple','gc-NED','Holanda','TEAM','F',7,null,null,'NED',null,null),
('GCNED8','wc2026-golden-crumple','gc-NED','Holanda','TEAM','F',8,null,null,'NED',null,null),
('GCNED9','wc2026-golden-crumple','gc-NED','Holanda','TEAM','F',9,null,null,'NED',null,null),
('GCNED10','wc2026-golden-crumple','gc-NED','Holanda','TEAM','F',10,null,null,'NED',null,null),
('GCNED11','wc2026-golden-crumple','gc-NED','Holanda','TEAM','F',11,null,null,'NED',null,null),
('GCNED12','wc2026-golden-crumple','gc-NED','Holanda','TEAM','F',12,null,null,'NED',null,null),
('GCNED13','wc2026-golden-crumple','gc-NED','Holanda','TEAM','F',13,null,null,'NED',null,null),
('GCNED14','wc2026-golden-crumple','gc-NED','Holanda','TEAM','F',14,null,null,'NED',null,null),
('GCNED15','wc2026-golden-crumple','gc-NED','Holanda','TEAM','F',15,null,null,'NED',null,null),
('GCNED16','wc2026-golden-crumple','gc-NED','Holanda','TEAM','F',16,null,null,'NED',null,null),
('GCNED17','wc2026-golden-crumple','gc-NED','Holanda','TEAM','F',17,null,null,'NED',null,null),
('GCNED18','wc2026-golden-crumple','gc-NED','Holanda','TEAM','F',18,null,null,'NED',null,null),
('GCNED19','wc2026-golden-crumple','gc-NED','Holanda','TEAM','F',19,null,null,'NED',null,null),
('GCNED20','wc2026-golden-crumple','gc-NED','Holanda','TEAM','F',20,null,null,'NED',null,null),
('GCJPN1','wc2026-golden-crumple','gc-JPN','Japão','TEAM','F',1,null,null,'JPN',null,null),
('GCJPN2','wc2026-golden-crumple','gc-JPN','Japão','TEAM','F',2,null,null,'JPN',null,null),
('GCJPN3','wc2026-golden-crumple','gc-JPN','Japão','TEAM','F',3,null,null,'JPN',null,null),
('GCJPN4','wc2026-golden-crumple','gc-JPN','Japão','TEAM','F',4,null,null,'JPN',null,null),
('GCJPN5','wc2026-golden-crumple','gc-JPN','Japão','TEAM','F',5,null,null,'JPN',null,null),
('GCJPN6','wc2026-golden-crumple','gc-JPN','Japão','TEAM','F',6,null,null,'JPN',null,null),
('GCJPN7','wc2026-golden-crumple','gc-JPN','Japão','TEAM','F',7,null,null,'JPN',null,null),
('GCJPN8','wc2026-golden-crumple','gc-JPN','Japão','TEAM','F',8,null,null,'JPN',null,null),
('GCJPN9','wc2026-golden-crumple','gc-JPN','Japão','TEAM','F',9,null,null,'JPN',null,null),
('GCJPN10','wc2026-golden-crumple','gc-JPN','Japão','TEAM','F',10,null,null,'JPN',null,null),
('GCJPN11','wc2026-golden-crumple','gc-JPN','Japão','TEAM','F',11,null,null,'JPN',null,null),
('GCJPN12','wc2026-golden-crumple','gc-JPN','Japão','TEAM','F',12,null,null,'JPN',null,null),
('GCJPN13','wc2026-golden-crumple','gc-JPN','Japão','TEAM','F',13,null,null,'JPN',null,null),
('GCJPN14','wc2026-golden-crumple','gc-JPN','Japão','TEAM','F',14,null,null,'JPN',null,null),
('GCJPN15','wc2026-golden-crumple','gc-JPN','Japão','TEAM','F',15,null,null,'JPN',null,null),
('GCJPN16','wc2026-golden-crumple','gc-JPN','Japão','TEAM','F',16,null,null,'JPN',null,null),
('GCJPN17','wc2026-golden-crumple','gc-JPN','Japão','TEAM','F',17,null,null,'JPN',null,null),
('GCJPN18','wc2026-golden-crumple','gc-JPN','Japão','TEAM','F',18,null,null,'JPN',null,null),
('GCJPN19','wc2026-golden-crumple','gc-JPN','Japão','TEAM','F',19,null,null,'JPN',null,null),
('GCJPN20','wc2026-golden-crumple','gc-JPN','Japão','TEAM','F',20,null,null,'JPN',null,null),
('GCSWE1','wc2026-golden-crumple','gc-SWE','Suécia','TEAM','F',1,null,null,'SWE',null,null),
('GCSWE2','wc2026-golden-crumple','gc-SWE','Suécia','TEAM','F',2,null,null,'SWE',null,null),
('GCSWE3','wc2026-golden-crumple','gc-SWE','Suécia','TEAM','F',3,null,null,'SWE',null,null),
('GCSWE4','wc2026-golden-crumple','gc-SWE','Suécia','TEAM','F',4,null,null,'SWE',null,null),
('GCSWE5','wc2026-golden-crumple','gc-SWE','Suécia','TEAM','F',5,null,null,'SWE',null,null),
('GCSWE6','wc2026-golden-crumple','gc-SWE','Suécia','TEAM','F',6,null,null,'SWE',null,null),
('GCSWE7','wc2026-golden-crumple','gc-SWE','Suécia','TEAM','F',7,null,null,'SWE',null,null),
('GCSWE8','wc2026-golden-crumple','gc-SWE','Suécia','TEAM','F',8,null,null,'SWE',null,null),
('GCSWE9','wc2026-golden-crumple','gc-SWE','Suécia','TEAM','F',9,null,null,'SWE',null,null),
('GCSWE10','wc2026-golden-crumple','gc-SWE','Suécia','TEAM','F',10,null,null,'SWE',null,null),
('GCSWE11','wc2026-golden-crumple','gc-SWE','Suécia','TEAM','F',11,null,null,'SWE',null,null),
('GCSWE12','wc2026-golden-crumple','gc-SWE','Suécia','TEAM','F',12,null,null,'SWE',null,null),
('GCSWE13','wc2026-golden-crumple','gc-SWE','Suécia','TEAM','F',13,null,null,'SWE',null,null),
('GCSWE14','wc2026-golden-crumple','gc-SWE','Suécia','TEAM','F',14,null,null,'SWE',null,null),
('GCSWE15','wc2026-golden-crumple','gc-SWE','Suécia','TEAM','F',15,null,null,'SWE',null,null),
('GCSWE16','wc2026-golden-crumple','gc-SWE','Suécia','TEAM','F',16,null,null,'SWE',null,null),
('GCSWE17','wc2026-golden-crumple','gc-SWE','Suécia','TEAM','F',17,null,null,'SWE',null,null),
('GCSWE18','wc2026-golden-crumple','gc-SWE','Suécia','TEAM','F',18,null,null,'SWE',null,null),
('GCSWE19','wc2026-golden-crumple','gc-SWE','Suécia','TEAM','F',19,null,null,'SWE',null,null),
('GCSWE20','wc2026-golden-crumple','gc-SWE','Suécia','TEAM','F',20,null,null,'SWE',null,null),
('GCTUN1','wc2026-golden-crumple','gc-TUN','Tunísia','TEAM','F',1,null,null,'TUN',null,null),
('GCTUN2','wc2026-golden-crumple','gc-TUN','Tunísia','TEAM','F',2,null,null,'TUN',null,null),
('GCTUN3','wc2026-golden-crumple','gc-TUN','Tunísia','TEAM','F',3,null,null,'TUN',null,null),
('GCTUN4','wc2026-golden-crumple','gc-TUN','Tunísia','TEAM','F',4,null,null,'TUN',null,null),
('GCTUN5','wc2026-golden-crumple','gc-TUN','Tunísia','TEAM','F',5,null,null,'TUN',null,null),
('GCTUN6','wc2026-golden-crumple','gc-TUN','Tunísia','TEAM','F',6,null,null,'TUN',null,null),
('GCTUN7','wc2026-golden-crumple','gc-TUN','Tunísia','TEAM','F',7,null,null,'TUN',null,null),
('GCTUN8','wc2026-golden-crumple','gc-TUN','Tunísia','TEAM','F',8,null,null,'TUN',null,null),
('GCTUN9','wc2026-golden-crumple','gc-TUN','Tunísia','TEAM','F',9,null,null,'TUN',null,null),
('GCTUN10','wc2026-golden-crumple','gc-TUN','Tunísia','TEAM','F',10,null,null,'TUN',null,null),
('GCTUN11','wc2026-golden-crumple','gc-TUN','Tunísia','TEAM','F',11,null,null,'TUN',null,null),
('GCTUN12','wc2026-golden-crumple','gc-TUN','Tunísia','TEAM','F',12,null,null,'TUN',null,null),
('GCTUN13','wc2026-golden-crumple','gc-TUN','Tunísia','TEAM','F',13,null,null,'TUN',null,null),
('GCTUN14','wc2026-golden-crumple','gc-TUN','Tunísia','TEAM','F',14,null,null,'TUN',null,null),
('GCTUN15','wc2026-golden-crumple','gc-TUN','Tunísia','TEAM','F',15,null,null,'TUN',null,null),
('GCTUN16','wc2026-golden-crumple','gc-TUN','Tunísia','TEAM','F',16,null,null,'TUN',null,null),
('GCTUN17','wc2026-golden-crumple','gc-TUN','Tunísia','TEAM','F',17,null,null,'TUN',null,null),
('GCTUN18','wc2026-golden-crumple','gc-TUN','Tunísia','TEAM','F',18,null,null,'TUN',null,null),
('GCTUN19','wc2026-golden-crumple','gc-TUN','Tunísia','TEAM','F',19,null,null,'TUN',null,null),
('GCTUN20','wc2026-golden-crumple','gc-TUN','Tunísia','TEAM','F',20,null,null,'TUN',null,null),
('GCBEL1','wc2026-golden-crumple','gc-BEL','Bélgica','TEAM','G',1,null,null,'BEL',null,null),
('GCBEL2','wc2026-golden-crumple','gc-BEL','Bélgica','TEAM','G',2,null,null,'BEL',null,null),
('GCBEL3','wc2026-golden-crumple','gc-BEL','Bélgica','TEAM','G',3,null,null,'BEL',null,null),
('GCBEL4','wc2026-golden-crumple','gc-BEL','Bélgica','TEAM','G',4,null,null,'BEL',null,null),
('GCBEL5','wc2026-golden-crumple','gc-BEL','Bélgica','TEAM','G',5,null,null,'BEL',null,null),
('GCBEL6','wc2026-golden-crumple','gc-BEL','Bélgica','TEAM','G',6,null,null,'BEL',null,null),
('GCBEL7','wc2026-golden-crumple','gc-BEL','Bélgica','TEAM','G',7,null,null,'BEL',null,null),
('GCBEL8','wc2026-golden-crumple','gc-BEL','Bélgica','TEAM','G',8,null,null,'BEL',null,null),
('GCBEL9','wc2026-golden-crumple','gc-BEL','Bélgica','TEAM','G',9,null,null,'BEL',null,null),
('GCBEL10','wc2026-golden-crumple','gc-BEL','Bélgica','TEAM','G',10,null,null,'BEL',null,null),
('GCBEL11','wc2026-golden-crumple','gc-BEL','Bélgica','TEAM','G',11,null,null,'BEL',null,null),
('GCBEL12','wc2026-golden-crumple','gc-BEL','Bélgica','TEAM','G',12,null,null,'BEL',null,null),
('GCBEL13','wc2026-golden-crumple','gc-BEL','Bélgica','TEAM','G',13,null,null,'BEL',null,null),
('GCBEL14','wc2026-golden-crumple','gc-BEL','Bélgica','TEAM','G',14,null,null,'BEL',null,null),
('GCBEL15','wc2026-golden-crumple','gc-BEL','Bélgica','TEAM','G',15,null,null,'BEL',null,null),
('GCBEL16','wc2026-golden-crumple','gc-BEL','Bélgica','TEAM','G',16,null,null,'BEL',null,null),
('GCBEL17','wc2026-golden-crumple','gc-BEL','Bélgica','TEAM','G',17,null,null,'BEL',null,null),
('GCBEL18','wc2026-golden-crumple','gc-BEL','Bélgica','TEAM','G',18,null,null,'BEL',null,null),
('GCBEL19','wc2026-golden-crumple','gc-BEL','Bélgica','TEAM','G',19,null,null,'BEL',null,null),
('GCBEL20','wc2026-golden-crumple','gc-BEL','Bélgica','TEAM','G',20,null,null,'BEL',null,null),
('GCEGY1','wc2026-golden-crumple','gc-EGY','Egito','TEAM','G',1,null,null,'EGY',null,null),
('GCEGY2','wc2026-golden-crumple','gc-EGY','Egito','TEAM','G',2,null,null,'EGY',null,null),
('GCEGY3','wc2026-golden-crumple','gc-EGY','Egito','TEAM','G',3,null,null,'EGY',null,null),
('GCEGY4','wc2026-golden-crumple','gc-EGY','Egito','TEAM','G',4,null,null,'EGY',null,null),
('GCEGY5','wc2026-golden-crumple','gc-EGY','Egito','TEAM','G',5,null,null,'EGY',null,null),
('GCEGY6','wc2026-golden-crumple','gc-EGY','Egito','TEAM','G',6,null,null,'EGY',null,null),
('GCEGY7','wc2026-golden-crumple','gc-EGY','Egito','TEAM','G',7,null,null,'EGY',null,null),
('GCEGY8','wc2026-golden-crumple','gc-EGY','Egito','TEAM','G',8,null,null,'EGY',null,null),
('GCEGY9','wc2026-golden-crumple','gc-EGY','Egito','TEAM','G',9,null,null,'EGY',null,null),
('GCEGY10','wc2026-golden-crumple','gc-EGY','Egito','TEAM','G',10,null,null,'EGY',null,null),
('GCEGY11','wc2026-golden-crumple','gc-EGY','Egito','TEAM','G',11,null,null,'EGY',null,null),
('GCEGY12','wc2026-golden-crumple','gc-EGY','Egito','TEAM','G',12,null,null,'EGY',null,null),
('GCEGY13','wc2026-golden-crumple','gc-EGY','Egito','TEAM','G',13,null,null,'EGY',null,null),
('GCEGY14','wc2026-golden-crumple','gc-EGY','Egito','TEAM','G',14,null,null,'EGY',null,null),
('GCEGY15','wc2026-golden-crumple','gc-EGY','Egito','TEAM','G',15,null,null,'EGY',null,null),
('GCEGY16','wc2026-golden-crumple','gc-EGY','Egito','TEAM','G',16,null,null,'EGY',null,null),
('GCEGY17','wc2026-golden-crumple','gc-EGY','Egito','TEAM','G',17,null,null,'EGY',null,null),
('GCEGY18','wc2026-golden-crumple','gc-EGY','Egito','TEAM','G',18,null,null,'EGY',null,null),
('GCEGY19','wc2026-golden-crumple','gc-EGY','Egito','TEAM','G',19,null,null,'EGY',null,null),
('GCEGY20','wc2026-golden-crumple','gc-EGY','Egito','TEAM','G',20,null,null,'EGY',null,null),
('GCIRN1','wc2026-golden-crumple','gc-IRN','Irã','TEAM','G',1,null,null,'IRN',null,null),
('GCIRN2','wc2026-golden-crumple','gc-IRN','Irã','TEAM','G',2,null,null,'IRN',null,null),
('GCIRN3','wc2026-golden-crumple','gc-IRN','Irã','TEAM','G',3,null,null,'IRN',null,null),
('GCIRN4','wc2026-golden-crumple','gc-IRN','Irã','TEAM','G',4,null,null,'IRN',null,null),
('GCIRN5','wc2026-golden-crumple','gc-IRN','Irã','TEAM','G',5,null,null,'IRN',null,null),
('GCIRN6','wc2026-golden-crumple','gc-IRN','Irã','TEAM','G',6,null,null,'IRN',null,null),
('GCIRN7','wc2026-golden-crumple','gc-IRN','Irã','TEAM','G',7,null,null,'IRN',null,null),
('GCIRN8','wc2026-golden-crumple','gc-IRN','Irã','TEAM','G',8,null,null,'IRN',null,null),
('GCIRN9','wc2026-golden-crumple','gc-IRN','Irã','TEAM','G',9,null,null,'IRN',null,null),
('GCIRN10','wc2026-golden-crumple','gc-IRN','Irã','TEAM','G',10,null,null,'IRN',null,null),
('GCIRN11','wc2026-golden-crumple','gc-IRN','Irã','TEAM','G',11,null,null,'IRN',null,null),
('GCIRN12','wc2026-golden-crumple','gc-IRN','Irã','TEAM','G',12,null,null,'IRN',null,null),
('GCIRN13','wc2026-golden-crumple','gc-IRN','Irã','TEAM','G',13,null,null,'IRN',null,null),
('GCIRN14','wc2026-golden-crumple','gc-IRN','Irã','TEAM','G',14,null,null,'IRN',null,null),
('GCIRN15','wc2026-golden-crumple','gc-IRN','Irã','TEAM','G',15,null,null,'IRN',null,null),
('GCIRN16','wc2026-golden-crumple','gc-IRN','Irã','TEAM','G',16,null,null,'IRN',null,null),
('GCIRN17','wc2026-golden-crumple','gc-IRN','Irã','TEAM','G',17,null,null,'IRN',null,null),
('GCIRN18','wc2026-golden-crumple','gc-IRN','Irã','TEAM','G',18,null,null,'IRN',null,null),
('GCIRN19','wc2026-golden-crumple','gc-IRN','Irã','TEAM','G',19,null,null,'IRN',null,null),
('GCIRN20','wc2026-golden-crumple','gc-IRN','Irã','TEAM','G',20,null,null,'IRN',null,null),
('GCNZL1','wc2026-golden-crumple','gc-NZL','Nova Zelândia','TEAM','G',1,null,null,'NZL',null,null),
('GCNZL2','wc2026-golden-crumple','gc-NZL','Nova Zelândia','TEAM','G',2,null,null,'NZL',null,null),
('GCNZL3','wc2026-golden-crumple','gc-NZL','Nova Zelândia','TEAM','G',3,null,null,'NZL',null,null),
('GCNZL4','wc2026-golden-crumple','gc-NZL','Nova Zelândia','TEAM','G',4,null,null,'NZL',null,null),
('GCNZL5','wc2026-golden-crumple','gc-NZL','Nova Zelândia','TEAM','G',5,null,null,'NZL',null,null),
('GCNZL6','wc2026-golden-crumple','gc-NZL','Nova Zelândia','TEAM','G',6,null,null,'NZL',null,null),
('GCNZL7','wc2026-golden-crumple','gc-NZL','Nova Zelândia','TEAM','G',7,null,null,'NZL',null,null),
('GCNZL8','wc2026-golden-crumple','gc-NZL','Nova Zelândia','TEAM','G',8,null,null,'NZL',null,null),
('GCNZL9','wc2026-golden-crumple','gc-NZL','Nova Zelândia','TEAM','G',9,null,null,'NZL',null,null),
('GCNZL10','wc2026-golden-crumple','gc-NZL','Nova Zelândia','TEAM','G',10,null,null,'NZL',null,null),
('GCNZL11','wc2026-golden-crumple','gc-NZL','Nova Zelândia','TEAM','G',11,null,null,'NZL',null,null),
('GCNZL12','wc2026-golden-crumple','gc-NZL','Nova Zelândia','TEAM','G',12,null,null,'NZL',null,null),
('GCNZL13','wc2026-golden-crumple','gc-NZL','Nova Zelândia','TEAM','G',13,null,null,'NZL',null,null),
('GCNZL14','wc2026-golden-crumple','gc-NZL','Nova Zelândia','TEAM','G',14,null,null,'NZL',null,null),
('GCNZL15','wc2026-golden-crumple','gc-NZL','Nova Zelândia','TEAM','G',15,null,null,'NZL',null,null),
('GCNZL16','wc2026-golden-crumple','gc-NZL','Nova Zelândia','TEAM','G',16,null,null,'NZL',null,null),
('GCNZL17','wc2026-golden-crumple','gc-NZL','Nova Zelândia','TEAM','G',17,null,null,'NZL',null,null),
('GCNZL18','wc2026-golden-crumple','gc-NZL','Nova Zelândia','TEAM','G',18,null,null,'NZL',null,null),
('GCNZL19','wc2026-golden-crumple','gc-NZL','Nova Zelândia','TEAM','G',19,null,null,'NZL',null,null),
('GCNZL20','wc2026-golden-crumple','gc-NZL','Nova Zelândia','TEAM','G',20,null,null,'NZL',null,null),
('GCESP1','wc2026-golden-crumple','gc-ESP','Espanha','TEAM','H',1,null,null,'ESP',null,null),
('GCESP2','wc2026-golden-crumple','gc-ESP','Espanha','TEAM','H',2,null,null,'ESP',null,null),
('GCESP3','wc2026-golden-crumple','gc-ESP','Espanha','TEAM','H',3,null,null,'ESP',null,null),
('GCESP4','wc2026-golden-crumple','gc-ESP','Espanha','TEAM','H',4,null,null,'ESP',null,null),
('GCESP5','wc2026-golden-crumple','gc-ESP','Espanha','TEAM','H',5,null,null,'ESP',null,null),
('GCESP6','wc2026-golden-crumple','gc-ESP','Espanha','TEAM','H',6,null,null,'ESP',null,null),
('GCESP7','wc2026-golden-crumple','gc-ESP','Espanha','TEAM','H',7,null,null,'ESP',null,null),
('GCESP8','wc2026-golden-crumple','gc-ESP','Espanha','TEAM','H',8,null,null,'ESP',null,null),
('GCESP9','wc2026-golden-crumple','gc-ESP','Espanha','TEAM','H',9,null,null,'ESP',null,null),
('GCESP10','wc2026-golden-crumple','gc-ESP','Espanha','TEAM','H',10,null,null,'ESP',null,null),
('GCESP11','wc2026-golden-crumple','gc-ESP','Espanha','TEAM','H',11,null,null,'ESP',null,null),
('GCESP12','wc2026-golden-crumple','gc-ESP','Espanha','TEAM','H',12,null,null,'ESP',null,null),
('GCESP13','wc2026-golden-crumple','gc-ESP','Espanha','TEAM','H',13,null,null,'ESP',null,null),
('GCESP14','wc2026-golden-crumple','gc-ESP','Espanha','TEAM','H',14,null,null,'ESP',null,null),
('GCESP15','wc2026-golden-crumple','gc-ESP','Espanha','TEAM','H',15,null,null,'ESP',null,null),
('GCESP16','wc2026-golden-crumple','gc-ESP','Espanha','TEAM','H',16,null,null,'ESP',null,null),
('GCESP17','wc2026-golden-crumple','gc-ESP','Espanha','TEAM','H',17,null,null,'ESP',null,null),
('GCESP18','wc2026-golden-crumple','gc-ESP','Espanha','TEAM','H',18,null,null,'ESP',null,null),
('GCESP19','wc2026-golden-crumple','gc-ESP','Espanha','TEAM','H',19,null,null,'ESP',null,null),
('GCESP20','wc2026-golden-crumple','gc-ESP','Espanha','TEAM','H',20,null,null,'ESP',null,null),
('GCCPV1','wc2026-golden-crumple','gc-CPV','Cabo Verde','TEAM','H',1,null,null,'CPV',null,null),
('GCCPV2','wc2026-golden-crumple','gc-CPV','Cabo Verde','TEAM','H',2,null,null,'CPV',null,null),
('GCCPV3','wc2026-golden-crumple','gc-CPV','Cabo Verde','TEAM','H',3,null,null,'CPV',null,null),
('GCCPV4','wc2026-golden-crumple','gc-CPV','Cabo Verde','TEAM','H',4,null,null,'CPV',null,null),
('GCCPV5','wc2026-golden-crumple','gc-CPV','Cabo Verde','TEAM','H',5,null,null,'CPV',null,null),
('GCCPV6','wc2026-golden-crumple','gc-CPV','Cabo Verde','TEAM','H',6,null,null,'CPV',null,null),
('GCCPV7','wc2026-golden-crumple','gc-CPV','Cabo Verde','TEAM','H',7,null,null,'CPV',null,null),
('GCCPV8','wc2026-golden-crumple','gc-CPV','Cabo Verde','TEAM','H',8,null,null,'CPV',null,null),
('GCCPV9','wc2026-golden-crumple','gc-CPV','Cabo Verde','TEAM','H',9,null,null,'CPV',null,null),
('GCCPV10','wc2026-golden-crumple','gc-CPV','Cabo Verde','TEAM','H',10,null,null,'CPV',null,null),
('GCCPV11','wc2026-golden-crumple','gc-CPV','Cabo Verde','TEAM','H',11,null,null,'CPV',null,null),
('GCCPV12','wc2026-golden-crumple','gc-CPV','Cabo Verde','TEAM','H',12,null,null,'CPV',null,null),
('GCCPV13','wc2026-golden-crumple','gc-CPV','Cabo Verde','TEAM','H',13,null,null,'CPV',null,null),
('GCCPV14','wc2026-golden-crumple','gc-CPV','Cabo Verde','TEAM','H',14,null,null,'CPV',null,null),
('GCCPV15','wc2026-golden-crumple','gc-CPV','Cabo Verde','TEAM','H',15,null,null,'CPV',null,null),
('GCCPV16','wc2026-golden-crumple','gc-CPV','Cabo Verde','TEAM','H',16,null,null,'CPV',null,null),
('GCCPV17','wc2026-golden-crumple','gc-CPV','Cabo Verde','TEAM','H',17,null,null,'CPV',null,null),
('GCCPV18','wc2026-golden-crumple','gc-CPV','Cabo Verde','TEAM','H',18,null,null,'CPV',null,null),
('GCCPV19','wc2026-golden-crumple','gc-CPV','Cabo Verde','TEAM','H',19,null,null,'CPV',null,null),
('GCCPV20','wc2026-golden-crumple','gc-CPV','Cabo Verde','TEAM','H',20,null,null,'CPV',null,null),
('GCKSA1','wc2026-golden-crumple','gc-KSA','Arábia Saudita','TEAM','H',1,null,null,'KSA',null,null),
('GCKSA2','wc2026-golden-crumple','gc-KSA','Arábia Saudita','TEAM','H',2,null,null,'KSA',null,null),
('GCKSA3','wc2026-golden-crumple','gc-KSA','Arábia Saudita','TEAM','H',3,null,null,'KSA',null,null),
('GCKSA4','wc2026-golden-crumple','gc-KSA','Arábia Saudita','TEAM','H',4,null,null,'KSA',null,null),
('GCKSA5','wc2026-golden-crumple','gc-KSA','Arábia Saudita','TEAM','H',5,null,null,'KSA',null,null),
('GCKSA6','wc2026-golden-crumple','gc-KSA','Arábia Saudita','TEAM','H',6,null,null,'KSA',null,null),
('GCKSA7','wc2026-golden-crumple','gc-KSA','Arábia Saudita','TEAM','H',7,null,null,'KSA',null,null),
('GCKSA8','wc2026-golden-crumple','gc-KSA','Arábia Saudita','TEAM','H',8,null,null,'KSA',null,null),
('GCKSA9','wc2026-golden-crumple','gc-KSA','Arábia Saudita','TEAM','H',9,null,null,'KSA',null,null),
('GCKSA10','wc2026-golden-crumple','gc-KSA','Arábia Saudita','TEAM','H',10,null,null,'KSA',null,null),
('GCKSA11','wc2026-golden-crumple','gc-KSA','Arábia Saudita','TEAM','H',11,null,null,'KSA',null,null),
('GCKSA12','wc2026-golden-crumple','gc-KSA','Arábia Saudita','TEAM','H',12,null,null,'KSA',null,null),
('GCKSA13','wc2026-golden-crumple','gc-KSA','Arábia Saudita','TEAM','H',13,null,null,'KSA',null,null),
('GCKSA14','wc2026-golden-crumple','gc-KSA','Arábia Saudita','TEAM','H',14,null,null,'KSA',null,null),
('GCKSA15','wc2026-golden-crumple','gc-KSA','Arábia Saudita','TEAM','H',15,null,null,'KSA',null,null),
('GCKSA16','wc2026-golden-crumple','gc-KSA','Arábia Saudita','TEAM','H',16,null,null,'KSA',null,null),
('GCKSA17','wc2026-golden-crumple','gc-KSA','Arábia Saudita','TEAM','H',17,null,null,'KSA',null,null),
('GCKSA18','wc2026-golden-crumple','gc-KSA','Arábia Saudita','TEAM','H',18,null,null,'KSA',null,null),
('GCKSA19','wc2026-golden-crumple','gc-KSA','Arábia Saudita','TEAM','H',19,null,null,'KSA',null,null),
('GCKSA20','wc2026-golden-crumple','gc-KSA','Arábia Saudita','TEAM','H',20,null,null,'KSA',null,null),
('GCURU1','wc2026-golden-crumple','gc-URU','Uruguai','TEAM','H',1,null,null,'URU',null,null),
('GCURU2','wc2026-golden-crumple','gc-URU','Uruguai','TEAM','H',2,null,null,'URU',null,null),
('GCURU3','wc2026-golden-crumple','gc-URU','Uruguai','TEAM','H',3,null,null,'URU',null,null),
('GCURU4','wc2026-golden-crumple','gc-URU','Uruguai','TEAM','H',4,null,null,'URU',null,null),
('GCURU5','wc2026-golden-crumple','gc-URU','Uruguai','TEAM','H',5,null,null,'URU',null,null),
('GCURU6','wc2026-golden-crumple','gc-URU','Uruguai','TEAM','H',6,null,null,'URU',null,null),
('GCURU7','wc2026-golden-crumple','gc-URU','Uruguai','TEAM','H',7,null,null,'URU',null,null),
('GCURU8','wc2026-golden-crumple','gc-URU','Uruguai','TEAM','H',8,null,null,'URU',null,null),
('GCURU9','wc2026-golden-crumple','gc-URU','Uruguai','TEAM','H',9,null,null,'URU',null,null),
('GCURU10','wc2026-golden-crumple','gc-URU','Uruguai','TEAM','H',10,null,null,'URU',null,null),
('GCURU11','wc2026-golden-crumple','gc-URU','Uruguai','TEAM','H',11,null,null,'URU',null,null),
('GCURU12','wc2026-golden-crumple','gc-URU','Uruguai','TEAM','H',12,null,null,'URU',null,null),
('GCURU13','wc2026-golden-crumple','gc-URU','Uruguai','TEAM','H',13,null,null,'URU',null,null),
('GCURU14','wc2026-golden-crumple','gc-URU','Uruguai','TEAM','H',14,null,null,'URU',null,null),
('GCURU15','wc2026-golden-crumple','gc-URU','Uruguai','TEAM','H',15,null,null,'URU',null,null),
('GCURU16','wc2026-golden-crumple','gc-URU','Uruguai','TEAM','H',16,null,null,'URU',null,null),
('GCURU17','wc2026-golden-crumple','gc-URU','Uruguai','TEAM','H',17,null,null,'URU',null,null),
('GCURU18','wc2026-golden-crumple','gc-URU','Uruguai','TEAM','H',18,null,null,'URU',null,null),
('GCURU19','wc2026-golden-crumple','gc-URU','Uruguai','TEAM','H',19,null,null,'URU',null,null),
('GCURU20','wc2026-golden-crumple','gc-URU','Uruguai','TEAM','H',20,null,null,'URU',null,null),
('GCFRA1','wc2026-golden-crumple','gc-FRA','França','TEAM','I',1,null,null,'FRA',null,null),
('GCFRA2','wc2026-golden-crumple','gc-FRA','França','TEAM','I',2,null,null,'FRA',null,null),
('GCFRA3','wc2026-golden-crumple','gc-FRA','França','TEAM','I',3,null,null,'FRA',null,null),
('GCFRA4','wc2026-golden-crumple','gc-FRA','França','TEAM','I',4,null,null,'FRA',null,null),
('GCFRA5','wc2026-golden-crumple','gc-FRA','França','TEAM','I',5,null,null,'FRA',null,null),
('GCFRA6','wc2026-golden-crumple','gc-FRA','França','TEAM','I',6,null,null,'FRA',null,null),
('GCFRA7','wc2026-golden-crumple','gc-FRA','França','TEAM','I',7,null,null,'FRA',null,null),
('GCFRA8','wc2026-golden-crumple','gc-FRA','França','TEAM','I',8,null,null,'FRA',null,null),
('GCFRA9','wc2026-golden-crumple','gc-FRA','França','TEAM','I',9,null,null,'FRA',null,null),
('GCFRA10','wc2026-golden-crumple','gc-FRA','França','TEAM','I',10,null,null,'FRA',null,null),
('GCFRA11','wc2026-golden-crumple','gc-FRA','França','TEAM','I',11,null,null,'FRA',null,null),
('GCFRA12','wc2026-golden-crumple','gc-FRA','França','TEAM','I',12,null,null,'FRA',null,null),
('GCFRA13','wc2026-golden-crumple','gc-FRA','França','TEAM','I',13,null,null,'FRA',null,null),
('GCFRA14','wc2026-golden-crumple','gc-FRA','França','TEAM','I',14,null,null,'FRA',null,null),
('GCFRA15','wc2026-golden-crumple','gc-FRA','França','TEAM','I',15,null,null,'FRA',null,null),
('GCFRA16','wc2026-golden-crumple','gc-FRA','França','TEAM','I',16,null,null,'FRA',null,null),
('GCFRA17','wc2026-golden-crumple','gc-FRA','França','TEAM','I',17,null,null,'FRA',null,null),
('GCFRA18','wc2026-golden-crumple','gc-FRA','França','TEAM','I',18,null,null,'FRA',null,null),
('GCFRA19','wc2026-golden-crumple','gc-FRA','França','TEAM','I',19,null,null,'FRA',null,null),
('GCFRA20','wc2026-golden-crumple','gc-FRA','França','TEAM','I',20,null,null,'FRA',null,null),
('GCSEN1','wc2026-golden-crumple','gc-SEN','Senegal','TEAM','I',1,null,null,'SEN',null,null),
('GCSEN2','wc2026-golden-crumple','gc-SEN','Senegal','TEAM','I',2,null,null,'SEN',null,null),
('GCSEN3','wc2026-golden-crumple','gc-SEN','Senegal','TEAM','I',3,null,null,'SEN',null,null),
('GCSEN4','wc2026-golden-crumple','gc-SEN','Senegal','TEAM','I',4,null,null,'SEN',null,null),
('GCSEN5','wc2026-golden-crumple','gc-SEN','Senegal','TEAM','I',5,null,null,'SEN',null,null),
('GCSEN6','wc2026-golden-crumple','gc-SEN','Senegal','TEAM','I',6,null,null,'SEN',null,null),
('GCSEN7','wc2026-golden-crumple','gc-SEN','Senegal','TEAM','I',7,null,null,'SEN',null,null),
('GCSEN8','wc2026-golden-crumple','gc-SEN','Senegal','TEAM','I',8,null,null,'SEN',null,null),
('GCSEN9','wc2026-golden-crumple','gc-SEN','Senegal','TEAM','I',9,null,null,'SEN',null,null),
('GCSEN10','wc2026-golden-crumple','gc-SEN','Senegal','TEAM','I',10,null,null,'SEN',null,null),
('GCSEN11','wc2026-golden-crumple','gc-SEN','Senegal','TEAM','I',11,null,null,'SEN',null,null),
('GCSEN12','wc2026-golden-crumple','gc-SEN','Senegal','TEAM','I',12,null,null,'SEN',null,null),
('GCSEN13','wc2026-golden-crumple','gc-SEN','Senegal','TEAM','I',13,null,null,'SEN',null,null),
('GCSEN14','wc2026-golden-crumple','gc-SEN','Senegal','TEAM','I',14,null,null,'SEN',null,null),
('GCSEN15','wc2026-golden-crumple','gc-SEN','Senegal','TEAM','I',15,null,null,'SEN',null,null),
('GCSEN16','wc2026-golden-crumple','gc-SEN','Senegal','TEAM','I',16,null,null,'SEN',null,null),
('GCSEN17','wc2026-golden-crumple','gc-SEN','Senegal','TEAM','I',17,null,null,'SEN',null,null),
('GCSEN18','wc2026-golden-crumple','gc-SEN','Senegal','TEAM','I',18,null,null,'SEN',null,null),
('GCSEN19','wc2026-golden-crumple','gc-SEN','Senegal','TEAM','I',19,null,null,'SEN',null,null),
('GCSEN20','wc2026-golden-crumple','gc-SEN','Senegal','TEAM','I',20,null,null,'SEN',null,null),
('GCIRQ1','wc2026-golden-crumple','gc-IRQ','Iraque','TEAM','I',1,null,null,'IRQ',null,null),
('GCIRQ2','wc2026-golden-crumple','gc-IRQ','Iraque','TEAM','I',2,null,null,'IRQ',null,null),
('GCIRQ3','wc2026-golden-crumple','gc-IRQ','Iraque','TEAM','I',3,null,null,'IRQ',null,null),
('GCIRQ4','wc2026-golden-crumple','gc-IRQ','Iraque','TEAM','I',4,null,null,'IRQ',null,null),
('GCIRQ5','wc2026-golden-crumple','gc-IRQ','Iraque','TEAM','I',5,null,null,'IRQ',null,null),
('GCIRQ6','wc2026-golden-crumple','gc-IRQ','Iraque','TEAM','I',6,null,null,'IRQ',null,null),
('GCIRQ7','wc2026-golden-crumple','gc-IRQ','Iraque','TEAM','I',7,null,null,'IRQ',null,null),
('GCIRQ8','wc2026-golden-crumple','gc-IRQ','Iraque','TEAM','I',8,null,null,'IRQ',null,null),
('GCIRQ9','wc2026-golden-crumple','gc-IRQ','Iraque','TEAM','I',9,null,null,'IRQ',null,null),
('GCIRQ10','wc2026-golden-crumple','gc-IRQ','Iraque','TEAM','I',10,null,null,'IRQ',null,null),
('GCIRQ11','wc2026-golden-crumple','gc-IRQ','Iraque','TEAM','I',11,null,null,'IRQ',null,null),
('GCIRQ12','wc2026-golden-crumple','gc-IRQ','Iraque','TEAM','I',12,null,null,'IRQ',null,null),
('GCIRQ13','wc2026-golden-crumple','gc-IRQ','Iraque','TEAM','I',13,null,null,'IRQ',null,null),
('GCIRQ14','wc2026-golden-crumple','gc-IRQ','Iraque','TEAM','I',14,null,null,'IRQ',null,null),
('GCIRQ15','wc2026-golden-crumple','gc-IRQ','Iraque','TEAM','I',15,null,null,'IRQ',null,null),
('GCIRQ16','wc2026-golden-crumple','gc-IRQ','Iraque','TEAM','I',16,null,null,'IRQ',null,null),
('GCIRQ17','wc2026-golden-crumple','gc-IRQ','Iraque','TEAM','I',17,null,null,'IRQ',null,null),
('GCIRQ18','wc2026-golden-crumple','gc-IRQ','Iraque','TEAM','I',18,null,null,'IRQ',null,null),
('GCIRQ19','wc2026-golden-crumple','gc-IRQ','Iraque','TEAM','I',19,null,null,'IRQ',null,null),
('GCIRQ20','wc2026-golden-crumple','gc-IRQ','Iraque','TEAM','I',20,null,null,'IRQ',null,null),
('GCNOR1','wc2026-golden-crumple','gc-NOR','Noruega','TEAM','I',1,null,null,'NOR',null,null),
('GCNOR2','wc2026-golden-crumple','gc-NOR','Noruega','TEAM','I',2,null,null,'NOR',null,null),
('GCNOR3','wc2026-golden-crumple','gc-NOR','Noruega','TEAM','I',3,null,null,'NOR',null,null),
('GCNOR4','wc2026-golden-crumple','gc-NOR','Noruega','TEAM','I',4,null,null,'NOR',null,null),
('GCNOR5','wc2026-golden-crumple','gc-NOR','Noruega','TEAM','I',5,null,null,'NOR',null,null),
('GCNOR6','wc2026-golden-crumple','gc-NOR','Noruega','TEAM','I',6,null,null,'NOR',null,null),
('GCNOR7','wc2026-golden-crumple','gc-NOR','Noruega','TEAM','I',7,null,null,'NOR',null,null),
('GCNOR8','wc2026-golden-crumple','gc-NOR','Noruega','TEAM','I',8,null,null,'NOR',null,null),
('GCNOR9','wc2026-golden-crumple','gc-NOR','Noruega','TEAM','I',9,null,null,'NOR',null,null),
('GCNOR10','wc2026-golden-crumple','gc-NOR','Noruega','TEAM','I',10,null,null,'NOR',null,null),
('GCNOR11','wc2026-golden-crumple','gc-NOR','Noruega','TEAM','I',11,null,null,'NOR',null,null),
('GCNOR12','wc2026-golden-crumple','gc-NOR','Noruega','TEAM','I',12,null,null,'NOR',null,null),
('GCNOR13','wc2026-golden-crumple','gc-NOR','Noruega','TEAM','I',13,null,null,'NOR',null,null),
('GCNOR14','wc2026-golden-crumple','gc-NOR','Noruega','TEAM','I',14,null,null,'NOR',null,null),
('GCNOR15','wc2026-golden-crumple','gc-NOR','Noruega','TEAM','I',15,null,null,'NOR',null,null),
('GCNOR16','wc2026-golden-crumple','gc-NOR','Noruega','TEAM','I',16,null,null,'NOR',null,null),
('GCNOR17','wc2026-golden-crumple','gc-NOR','Noruega','TEAM','I',17,null,null,'NOR',null,null),
('GCNOR18','wc2026-golden-crumple','gc-NOR','Noruega','TEAM','I',18,null,null,'NOR',null,null),
('GCNOR19','wc2026-golden-crumple','gc-NOR','Noruega','TEAM','I',19,null,null,'NOR',null,null),
('GCNOR20','wc2026-golden-crumple','gc-NOR','Noruega','TEAM','I',20,null,null,'NOR',null,null),
('GCARG1','wc2026-golden-crumple','gc-ARG','Argentina','TEAM','J',1,null,null,'ARG',null,null),
('GCARG2','wc2026-golden-crumple','gc-ARG','Argentina','TEAM','J',2,null,null,'ARG',null,null),
('GCARG3','wc2026-golden-crumple','gc-ARG','Argentina','TEAM','J',3,null,null,'ARG',null,null),
('GCARG4','wc2026-golden-crumple','gc-ARG','Argentina','TEAM','J',4,null,null,'ARG',null,null),
('GCARG5','wc2026-golden-crumple','gc-ARG','Argentina','TEAM','J',5,null,null,'ARG',null,null),
('GCARG6','wc2026-golden-crumple','gc-ARG','Argentina','TEAM','J',6,null,null,'ARG',null,null),
('GCARG7','wc2026-golden-crumple','gc-ARG','Argentina','TEAM','J',7,null,null,'ARG',null,null),
('GCARG8','wc2026-golden-crumple','gc-ARG','Argentina','TEAM','J',8,null,null,'ARG',null,null),
('GCARG9','wc2026-golden-crumple','gc-ARG','Argentina','TEAM','J',9,null,null,'ARG',null,null),
('GCARG10','wc2026-golden-crumple','gc-ARG','Argentina','TEAM','J',10,null,null,'ARG',null,null),
('GCARG11','wc2026-golden-crumple','gc-ARG','Argentina','TEAM','J',11,null,null,'ARG',null,null),
('GCARG12','wc2026-golden-crumple','gc-ARG','Argentina','TEAM','J',12,null,null,'ARG',null,null),
('GCARG13','wc2026-golden-crumple','gc-ARG','Argentina','TEAM','J',13,null,null,'ARG',null,null),
('GCARG14','wc2026-golden-crumple','gc-ARG','Argentina','TEAM','J',14,null,null,'ARG',null,null),
('GCARG15','wc2026-golden-crumple','gc-ARG','Argentina','TEAM','J',15,null,null,'ARG',null,null),
('GCARG16','wc2026-golden-crumple','gc-ARG','Argentina','TEAM','J',16,null,null,'ARG',null,null),
('GCARG17','wc2026-golden-crumple','gc-ARG','Argentina','TEAM','J',17,null,null,'ARG',null,null),
('GCARG18','wc2026-golden-crumple','gc-ARG','Argentina','TEAM','J',18,null,null,'ARG',null,null),
('GCARG19','wc2026-golden-crumple','gc-ARG','Argentina','TEAM','J',19,null,null,'ARG',null,null),
('GCARG20','wc2026-golden-crumple','gc-ARG','Argentina','TEAM','J',20,null,null,'ARG',null,null),
('GCALG1','wc2026-golden-crumple','gc-ALG','Argélia','TEAM','J',1,null,null,'ALG',null,null),
('GCALG2','wc2026-golden-crumple','gc-ALG','Argélia','TEAM','J',2,null,null,'ALG',null,null),
('GCALG3','wc2026-golden-crumple','gc-ALG','Argélia','TEAM','J',3,null,null,'ALG',null,null),
('GCALG4','wc2026-golden-crumple','gc-ALG','Argélia','TEAM','J',4,null,null,'ALG',null,null),
('GCALG5','wc2026-golden-crumple','gc-ALG','Argélia','TEAM','J',5,null,null,'ALG',null,null),
('GCALG6','wc2026-golden-crumple','gc-ALG','Argélia','TEAM','J',6,null,null,'ALG',null,null),
('GCALG7','wc2026-golden-crumple','gc-ALG','Argélia','TEAM','J',7,null,null,'ALG',null,null),
('GCALG8','wc2026-golden-crumple','gc-ALG','Argélia','TEAM','J',8,null,null,'ALG',null,null),
('GCALG9','wc2026-golden-crumple','gc-ALG','Argélia','TEAM','J',9,null,null,'ALG',null,null),
('GCALG10','wc2026-golden-crumple','gc-ALG','Argélia','TEAM','J',10,null,null,'ALG',null,null),
('GCALG11','wc2026-golden-crumple','gc-ALG','Argélia','TEAM','J',11,null,null,'ALG',null,null),
('GCALG12','wc2026-golden-crumple','gc-ALG','Argélia','TEAM','J',12,null,null,'ALG',null,null),
('GCALG13','wc2026-golden-crumple','gc-ALG','Argélia','TEAM','J',13,null,null,'ALG',null,null),
('GCALG14','wc2026-golden-crumple','gc-ALG','Argélia','TEAM','J',14,null,null,'ALG',null,null),
('GCALG15','wc2026-golden-crumple','gc-ALG','Argélia','TEAM','J',15,null,null,'ALG',null,null),
('GCALG16','wc2026-golden-crumple','gc-ALG','Argélia','TEAM','J',16,null,null,'ALG',null,null),
('GCALG17','wc2026-golden-crumple','gc-ALG','Argélia','TEAM','J',17,null,null,'ALG',null,null),
('GCALG18','wc2026-golden-crumple','gc-ALG','Argélia','TEAM','J',18,null,null,'ALG',null,null),
('GCALG19','wc2026-golden-crumple','gc-ALG','Argélia','TEAM','J',19,null,null,'ALG',null,null),
('GCALG20','wc2026-golden-crumple','gc-ALG','Argélia','TEAM','J',20,null,null,'ALG',null,null),
('GCAUT1','wc2026-golden-crumple','gc-AUT','Áustria','TEAM','J',1,null,null,'AUT',null,null),
('GCAUT2','wc2026-golden-crumple','gc-AUT','Áustria','TEAM','J',2,null,null,'AUT',null,null),
('GCAUT3','wc2026-golden-crumple','gc-AUT','Áustria','TEAM','J',3,null,null,'AUT',null,null),
('GCAUT4','wc2026-golden-crumple','gc-AUT','Áustria','TEAM','J',4,null,null,'AUT',null,null),
('GCAUT5','wc2026-golden-crumple','gc-AUT','Áustria','TEAM','J',5,null,null,'AUT',null,null),
('GCAUT6','wc2026-golden-crumple','gc-AUT','Áustria','TEAM','J',6,null,null,'AUT',null,null),
('GCAUT7','wc2026-golden-crumple','gc-AUT','Áustria','TEAM','J',7,null,null,'AUT',null,null),
('GCAUT8','wc2026-golden-crumple','gc-AUT','Áustria','TEAM','J',8,null,null,'AUT',null,null),
('GCAUT9','wc2026-golden-crumple','gc-AUT','Áustria','TEAM','J',9,null,null,'AUT',null,null),
('GCAUT10','wc2026-golden-crumple','gc-AUT','Áustria','TEAM','J',10,null,null,'AUT',null,null),
('GCAUT11','wc2026-golden-crumple','gc-AUT','Áustria','TEAM','J',11,null,null,'AUT',null,null),
('GCAUT12','wc2026-golden-crumple','gc-AUT','Áustria','TEAM','J',12,null,null,'AUT',null,null),
('GCAUT13','wc2026-golden-crumple','gc-AUT','Áustria','TEAM','J',13,null,null,'AUT',null,null),
('GCAUT14','wc2026-golden-crumple','gc-AUT','Áustria','TEAM','J',14,null,null,'AUT',null,null),
('GCAUT15','wc2026-golden-crumple','gc-AUT','Áustria','TEAM','J',15,null,null,'AUT',null,null),
('GCAUT16','wc2026-golden-crumple','gc-AUT','Áustria','TEAM','J',16,null,null,'AUT',null,null),
('GCAUT17','wc2026-golden-crumple','gc-AUT','Áustria','TEAM','J',17,null,null,'AUT',null,null),
('GCAUT18','wc2026-golden-crumple','gc-AUT','Áustria','TEAM','J',18,null,null,'AUT',null,null),
('GCAUT19','wc2026-golden-crumple','gc-AUT','Áustria','TEAM','J',19,null,null,'AUT',null,null),
('GCAUT20','wc2026-golden-crumple','gc-AUT','Áustria','TEAM','J',20,null,null,'AUT',null,null),
('GCJOR1','wc2026-golden-crumple','gc-JOR','Jordânia','TEAM','J',1,null,null,'JOR',null,null),
('GCJOR2','wc2026-golden-crumple','gc-JOR','Jordânia','TEAM','J',2,null,null,'JOR',null,null),
('GCJOR3','wc2026-golden-crumple','gc-JOR','Jordânia','TEAM','J',3,null,null,'JOR',null,null),
('GCJOR4','wc2026-golden-crumple','gc-JOR','Jordânia','TEAM','J',4,null,null,'JOR',null,null),
('GCJOR5','wc2026-golden-crumple','gc-JOR','Jordânia','TEAM','J',5,null,null,'JOR',null,null),
('GCJOR6','wc2026-golden-crumple','gc-JOR','Jordânia','TEAM','J',6,null,null,'JOR',null,null),
('GCJOR7','wc2026-golden-crumple','gc-JOR','Jordânia','TEAM','J',7,null,null,'JOR',null,null),
('GCJOR8','wc2026-golden-crumple','gc-JOR','Jordânia','TEAM','J',8,null,null,'JOR',null,null),
('GCJOR9','wc2026-golden-crumple','gc-JOR','Jordânia','TEAM','J',9,null,null,'JOR',null,null),
('GCJOR10','wc2026-golden-crumple','gc-JOR','Jordânia','TEAM','J',10,null,null,'JOR',null,null),
('GCJOR11','wc2026-golden-crumple','gc-JOR','Jordânia','TEAM','J',11,null,null,'JOR',null,null),
('GCJOR12','wc2026-golden-crumple','gc-JOR','Jordânia','TEAM','J',12,null,null,'JOR',null,null),
('GCJOR13','wc2026-golden-crumple','gc-JOR','Jordânia','TEAM','J',13,null,null,'JOR',null,null),
('GCJOR14','wc2026-golden-crumple','gc-JOR','Jordânia','TEAM','J',14,null,null,'JOR',null,null),
('GCJOR15','wc2026-golden-crumple','gc-JOR','Jordânia','TEAM','J',15,null,null,'JOR',null,null),
('GCJOR16','wc2026-golden-crumple','gc-JOR','Jordânia','TEAM','J',16,null,null,'JOR',null,null),
('GCJOR17','wc2026-golden-crumple','gc-JOR','Jordânia','TEAM','J',17,null,null,'JOR',null,null),
('GCJOR18','wc2026-golden-crumple','gc-JOR','Jordânia','TEAM','J',18,null,null,'JOR',null,null),
('GCJOR19','wc2026-golden-crumple','gc-JOR','Jordânia','TEAM','J',19,null,null,'JOR',null,null),
('GCJOR20','wc2026-golden-crumple','gc-JOR','Jordânia','TEAM','J',20,null,null,'JOR',null,null),
('GCPOR1','wc2026-golden-crumple','gc-POR','Portugal','TEAM','K',1,null,null,'POR',null,null),
('GCPOR2','wc2026-golden-crumple','gc-POR','Portugal','TEAM','K',2,null,null,'POR',null,null),
('GCPOR3','wc2026-golden-crumple','gc-POR','Portugal','TEAM','K',3,null,null,'POR',null,null),
('GCPOR4','wc2026-golden-crumple','gc-POR','Portugal','TEAM','K',4,null,null,'POR',null,null),
('GCPOR5','wc2026-golden-crumple','gc-POR','Portugal','TEAM','K',5,null,null,'POR',null,null),
('GCPOR6','wc2026-golden-crumple','gc-POR','Portugal','TEAM','K',6,null,null,'POR',null,null),
('GCPOR7','wc2026-golden-crumple','gc-POR','Portugal','TEAM','K',7,null,null,'POR',null,null),
('GCPOR8','wc2026-golden-crumple','gc-POR','Portugal','TEAM','K',8,null,null,'POR',null,null),
('GCPOR9','wc2026-golden-crumple','gc-POR','Portugal','TEAM','K',9,null,null,'POR',null,null),
('GCPOR10','wc2026-golden-crumple','gc-POR','Portugal','TEAM','K',10,null,null,'POR',null,null),
('GCPOR11','wc2026-golden-crumple','gc-POR','Portugal','TEAM','K',11,null,null,'POR',null,null),
('GCPOR12','wc2026-golden-crumple','gc-POR','Portugal','TEAM','K',12,null,null,'POR',null,null),
('GCPOR13','wc2026-golden-crumple','gc-POR','Portugal','TEAM','K',13,null,null,'POR',null,null),
('GCPOR14','wc2026-golden-crumple','gc-POR','Portugal','TEAM','K',14,null,null,'POR',null,null),
('GCPOR15','wc2026-golden-crumple','gc-POR','Portugal','TEAM','K',15,null,null,'POR',null,null),
('GCPOR16','wc2026-golden-crumple','gc-POR','Portugal','TEAM','K',16,null,null,'POR',null,null),
('GCPOR17','wc2026-golden-crumple','gc-POR','Portugal','TEAM','K',17,null,null,'POR',null,null),
('GCPOR18','wc2026-golden-crumple','gc-POR','Portugal','TEAM','K',18,null,null,'POR',null,null),
('GCPOR19','wc2026-golden-crumple','gc-POR','Portugal','TEAM','K',19,null,null,'POR',null,null),
('GCPOR20','wc2026-golden-crumple','gc-POR','Portugal','TEAM','K',20,null,null,'POR',null,null),
('GCCOD1','wc2026-golden-crumple','gc-COD','Congo','TEAM','K',1,null,null,'COD',null,null),
('GCCOD2','wc2026-golden-crumple','gc-COD','Congo','TEAM','K',2,null,null,'COD',null,null),
('GCCOD3','wc2026-golden-crumple','gc-COD','Congo','TEAM','K',3,null,null,'COD',null,null),
('GCCOD4','wc2026-golden-crumple','gc-COD','Congo','TEAM','K',4,null,null,'COD',null,null),
('GCCOD5','wc2026-golden-crumple','gc-COD','Congo','TEAM','K',5,null,null,'COD',null,null),
('GCCOD6','wc2026-golden-crumple','gc-COD','Congo','TEAM','K',6,null,null,'COD',null,null),
('GCCOD7','wc2026-golden-crumple','gc-COD','Congo','TEAM','K',7,null,null,'COD',null,null),
('GCCOD8','wc2026-golden-crumple','gc-COD','Congo','TEAM','K',8,null,null,'COD',null,null),
('GCCOD9','wc2026-golden-crumple','gc-COD','Congo','TEAM','K',9,null,null,'COD',null,null),
('GCCOD10','wc2026-golden-crumple','gc-COD','Congo','TEAM','K',10,null,null,'COD',null,null),
('GCCOD11','wc2026-golden-crumple','gc-COD','Congo','TEAM','K',11,null,null,'COD',null,null),
('GCCOD12','wc2026-golden-crumple','gc-COD','Congo','TEAM','K',12,null,null,'COD',null,null),
('GCCOD13','wc2026-golden-crumple','gc-COD','Congo','TEAM','K',13,null,null,'COD',null,null),
('GCCOD14','wc2026-golden-crumple','gc-COD','Congo','TEAM','K',14,null,null,'COD',null,null),
('GCCOD15','wc2026-golden-crumple','gc-COD','Congo','TEAM','K',15,null,null,'COD',null,null),
('GCCOD16','wc2026-golden-crumple','gc-COD','Congo','TEAM','K',16,null,null,'COD',null,null),
('GCCOD17','wc2026-golden-crumple','gc-COD','Congo','TEAM','K',17,null,null,'COD',null,null),
('GCCOD18','wc2026-golden-crumple','gc-COD','Congo','TEAM','K',18,null,null,'COD',null,null),
('GCCOD19','wc2026-golden-crumple','gc-COD','Congo','TEAM','K',19,null,null,'COD',null,null),
('GCCOD20','wc2026-golden-crumple','gc-COD','Congo','TEAM','K',20,null,null,'COD',null,null),
('GCUZB1','wc2026-golden-crumple','gc-UZB','Uzbequistão','TEAM','K',1,null,null,'UZB',null,null),
('GCUZB2','wc2026-golden-crumple','gc-UZB','Uzbequistão','TEAM','K',2,null,null,'UZB',null,null),
('GCUZB3','wc2026-golden-crumple','gc-UZB','Uzbequistão','TEAM','K',3,null,null,'UZB',null,null),
('GCUZB4','wc2026-golden-crumple','gc-UZB','Uzbequistão','TEAM','K',4,null,null,'UZB',null,null),
('GCUZB5','wc2026-golden-crumple','gc-UZB','Uzbequistão','TEAM','K',5,null,null,'UZB',null,null),
('GCUZB6','wc2026-golden-crumple','gc-UZB','Uzbequistão','TEAM','K',6,null,null,'UZB',null,null),
('GCUZB7','wc2026-golden-crumple','gc-UZB','Uzbequistão','TEAM','K',7,null,null,'UZB',null,null),
('GCUZB8','wc2026-golden-crumple','gc-UZB','Uzbequistão','TEAM','K',8,null,null,'UZB',null,null),
('GCUZB9','wc2026-golden-crumple','gc-UZB','Uzbequistão','TEAM','K',9,null,null,'UZB',null,null),
('GCUZB10','wc2026-golden-crumple','gc-UZB','Uzbequistão','TEAM','K',10,null,null,'UZB',null,null),
('GCUZB11','wc2026-golden-crumple','gc-UZB','Uzbequistão','TEAM','K',11,null,null,'UZB',null,null),
('GCUZB12','wc2026-golden-crumple','gc-UZB','Uzbequistão','TEAM','K',12,null,null,'UZB',null,null),
('GCUZB13','wc2026-golden-crumple','gc-UZB','Uzbequistão','TEAM','K',13,null,null,'UZB',null,null),
('GCUZB14','wc2026-golden-crumple','gc-UZB','Uzbequistão','TEAM','K',14,null,null,'UZB',null,null),
('GCUZB15','wc2026-golden-crumple','gc-UZB','Uzbequistão','TEAM','K',15,null,null,'UZB',null,null),
('GCUZB16','wc2026-golden-crumple','gc-UZB','Uzbequistão','TEAM','K',16,null,null,'UZB',null,null),
('GCUZB17','wc2026-golden-crumple','gc-UZB','Uzbequistão','TEAM','K',17,null,null,'UZB',null,null),
('GCUZB18','wc2026-golden-crumple','gc-UZB','Uzbequistão','TEAM','K',18,null,null,'UZB',null,null),
('GCUZB19','wc2026-golden-crumple','gc-UZB','Uzbequistão','TEAM','K',19,null,null,'UZB',null,null),
('GCUZB20','wc2026-golden-crumple','gc-UZB','Uzbequistão','TEAM','K',20,null,null,'UZB',null,null),
('GCCOL1','wc2026-golden-crumple','gc-COL','Colômbia','TEAM','K',1,null,null,'COL',null,null),
('GCCOL2','wc2026-golden-crumple','gc-COL','Colômbia','TEAM','K',2,null,null,'COL',null,null),
('GCCOL3','wc2026-golden-crumple','gc-COL','Colômbia','TEAM','K',3,null,null,'COL',null,null),
('GCCOL4','wc2026-golden-crumple','gc-COL','Colômbia','TEAM','K',4,null,null,'COL',null,null),
('GCCOL5','wc2026-golden-crumple','gc-COL','Colômbia','TEAM','K',5,null,null,'COL',null,null),
('GCCOL6','wc2026-golden-crumple','gc-COL','Colômbia','TEAM','K',6,null,null,'COL',null,null),
('GCCOL7','wc2026-golden-crumple','gc-COL','Colômbia','TEAM','K',7,null,null,'COL',null,null),
('GCCOL8','wc2026-golden-crumple','gc-COL','Colômbia','TEAM','K',8,null,null,'COL',null,null),
('GCCOL9','wc2026-golden-crumple','gc-COL','Colômbia','TEAM','K',9,null,null,'COL',null,null),
('GCCOL10','wc2026-golden-crumple','gc-COL','Colômbia','TEAM','K',10,null,null,'COL',null,null),
('GCCOL11','wc2026-golden-crumple','gc-COL','Colômbia','TEAM','K',11,null,null,'COL',null,null),
('GCCOL12','wc2026-golden-crumple','gc-COL','Colômbia','TEAM','K',12,null,null,'COL',null,null),
('GCCOL13','wc2026-golden-crumple','gc-COL','Colômbia','TEAM','K',13,null,null,'COL',null,null),
('GCCOL14','wc2026-golden-crumple','gc-COL','Colômbia','TEAM','K',14,null,null,'COL',null,null),
('GCCOL15','wc2026-golden-crumple','gc-COL','Colômbia','TEAM','K',15,null,null,'COL',null,null),
('GCCOL16','wc2026-golden-crumple','gc-COL','Colômbia','TEAM','K',16,null,null,'COL',null,null),
('GCCOL17','wc2026-golden-crumple','gc-COL','Colômbia','TEAM','K',17,null,null,'COL',null,null),
('GCCOL18','wc2026-golden-crumple','gc-COL','Colômbia','TEAM','K',18,null,null,'COL',null,null),
('GCCOL19','wc2026-golden-crumple','gc-COL','Colômbia','TEAM','K',19,null,null,'COL',null,null),
('GCCOL20','wc2026-golden-crumple','gc-COL','Colômbia','TEAM','K',20,null,null,'COL',null,null),
('GCENG1','wc2026-golden-crumple','gc-ENG','Inglaterra','TEAM','L',1,null,null,'ENG',null,null),
('GCENG2','wc2026-golden-crumple','gc-ENG','Inglaterra','TEAM','L',2,null,null,'ENG',null,null),
('GCENG3','wc2026-golden-crumple','gc-ENG','Inglaterra','TEAM','L',3,null,null,'ENG',null,null),
('GCENG4','wc2026-golden-crumple','gc-ENG','Inglaterra','TEAM','L',4,null,null,'ENG',null,null),
('GCENG5','wc2026-golden-crumple','gc-ENG','Inglaterra','TEAM','L',5,null,null,'ENG',null,null),
('GCENG6','wc2026-golden-crumple','gc-ENG','Inglaterra','TEAM','L',6,null,null,'ENG',null,null),
('GCENG7','wc2026-golden-crumple','gc-ENG','Inglaterra','TEAM','L',7,null,null,'ENG',null,null),
('GCENG8','wc2026-golden-crumple','gc-ENG','Inglaterra','TEAM','L',8,null,null,'ENG',null,null),
('GCENG9','wc2026-golden-crumple','gc-ENG','Inglaterra','TEAM','L',9,null,null,'ENG',null,null),
('GCENG10','wc2026-golden-crumple','gc-ENG','Inglaterra','TEAM','L',10,null,null,'ENG',null,null),
('GCENG11','wc2026-golden-crumple','gc-ENG','Inglaterra','TEAM','L',11,null,null,'ENG',null,null),
('GCENG12','wc2026-golden-crumple','gc-ENG','Inglaterra','TEAM','L',12,null,null,'ENG',null,null),
('GCENG13','wc2026-golden-crumple','gc-ENG','Inglaterra','TEAM','L',13,null,null,'ENG',null,null),
('GCENG14','wc2026-golden-crumple','gc-ENG','Inglaterra','TEAM','L',14,null,null,'ENG',null,null),
('GCENG15','wc2026-golden-crumple','gc-ENG','Inglaterra','TEAM','L',15,null,null,'ENG',null,null),
('GCENG16','wc2026-golden-crumple','gc-ENG','Inglaterra','TEAM','L',16,null,null,'ENG',null,null),
('GCENG17','wc2026-golden-crumple','gc-ENG','Inglaterra','TEAM','L',17,null,null,'ENG',null,null),
('GCENG18','wc2026-golden-crumple','gc-ENG','Inglaterra','TEAM','L',18,null,null,'ENG',null,null),
('GCENG19','wc2026-golden-crumple','gc-ENG','Inglaterra','TEAM','L',19,null,null,'ENG',null,null),
('GCENG20','wc2026-golden-crumple','gc-ENG','Inglaterra','TEAM','L',20,null,null,'ENG',null,null),
('GCCRO1','wc2026-golden-crumple','gc-CRO','Croácia','TEAM','L',1,null,null,'CRO',null,null),
('GCCRO2','wc2026-golden-crumple','gc-CRO','Croácia','TEAM','L',2,null,null,'CRO',null,null),
('GCCRO3','wc2026-golden-crumple','gc-CRO','Croácia','TEAM','L',3,null,null,'CRO',null,null),
('GCCRO4','wc2026-golden-crumple','gc-CRO','Croácia','TEAM','L',4,null,null,'CRO',null,null),
('GCCRO5','wc2026-golden-crumple','gc-CRO','Croácia','TEAM','L',5,null,null,'CRO',null,null),
('GCCRO6','wc2026-golden-crumple','gc-CRO','Croácia','TEAM','L',6,null,null,'CRO',null,null),
('GCCRO7','wc2026-golden-crumple','gc-CRO','Croácia','TEAM','L',7,null,null,'CRO',null,null),
('GCCRO8','wc2026-golden-crumple','gc-CRO','Croácia','TEAM','L',8,null,null,'CRO',null,null),
('GCCRO9','wc2026-golden-crumple','gc-CRO','Croácia','TEAM','L',9,null,null,'CRO',null,null),
('GCCRO10','wc2026-golden-crumple','gc-CRO','Croácia','TEAM','L',10,null,null,'CRO',null,null),
('GCCRO11','wc2026-golden-crumple','gc-CRO','Croácia','TEAM','L',11,null,null,'CRO',null,null),
('GCCRO12','wc2026-golden-crumple','gc-CRO','Croácia','TEAM','L',12,null,null,'CRO',null,null),
('GCCRO13','wc2026-golden-crumple','gc-CRO','Croácia','TEAM','L',13,null,null,'CRO',null,null),
('GCCRO14','wc2026-golden-crumple','gc-CRO','Croácia','TEAM','L',14,null,null,'CRO',null,null),
('GCCRO15','wc2026-golden-crumple','gc-CRO','Croácia','TEAM','L',15,null,null,'CRO',null,null),
('GCCRO16','wc2026-golden-crumple','gc-CRO','Croácia','TEAM','L',16,null,null,'CRO',null,null),
('GCCRO17','wc2026-golden-crumple','gc-CRO','Croácia','TEAM','L',17,null,null,'CRO',null,null),
('GCCRO18','wc2026-golden-crumple','gc-CRO','Croácia','TEAM','L',18,null,null,'CRO',null,null),
('GCCRO19','wc2026-golden-crumple','gc-CRO','Croácia','TEAM','L',19,null,null,'CRO',null,null),
('GCCRO20','wc2026-golden-crumple','gc-CRO','Croácia','TEAM','L',20,null,null,'CRO',null,null),
('GCGHA1','wc2026-golden-crumple','gc-GHA','Gana','TEAM','L',1,null,null,'GHA',null,null),
('GCGHA2','wc2026-golden-crumple','gc-GHA','Gana','TEAM','L',2,null,null,'GHA',null,null),
('GCGHA3','wc2026-golden-crumple','gc-GHA','Gana','TEAM','L',3,null,null,'GHA',null,null),
('GCGHA4','wc2026-golden-crumple','gc-GHA','Gana','TEAM','L',4,null,null,'GHA',null,null),
('GCGHA5','wc2026-golden-crumple','gc-GHA','Gana','TEAM','L',5,null,null,'GHA',null,null),
('GCGHA6','wc2026-golden-crumple','gc-GHA','Gana','TEAM','L',6,null,null,'GHA',null,null),
('GCGHA7','wc2026-golden-crumple','gc-GHA','Gana','TEAM','L',7,null,null,'GHA',null,null),
('GCGHA8','wc2026-golden-crumple','gc-GHA','Gana','TEAM','L',8,null,null,'GHA',null,null),
('GCGHA9','wc2026-golden-crumple','gc-GHA','Gana','TEAM','L',9,null,null,'GHA',null,null),
('GCGHA10','wc2026-golden-crumple','gc-GHA','Gana','TEAM','L',10,null,null,'GHA',null,null),
('GCGHA11','wc2026-golden-crumple','gc-GHA','Gana','TEAM','L',11,null,null,'GHA',null,null),
('GCGHA12','wc2026-golden-crumple','gc-GHA','Gana','TEAM','L',12,null,null,'GHA',null,null),
('GCGHA13','wc2026-golden-crumple','gc-GHA','Gana','TEAM','L',13,null,null,'GHA',null,null),
('GCGHA14','wc2026-golden-crumple','gc-GHA','Gana','TEAM','L',14,null,null,'GHA',null,null),
('GCGHA15','wc2026-golden-crumple','gc-GHA','Gana','TEAM','L',15,null,null,'GHA',null,null),
('GCGHA16','wc2026-golden-crumple','gc-GHA','Gana','TEAM','L',16,null,null,'GHA',null,null),
('GCGHA17','wc2026-golden-crumple','gc-GHA','Gana','TEAM','L',17,null,null,'GHA',null,null),
('GCGHA18','wc2026-golden-crumple','gc-GHA','Gana','TEAM','L',18,null,null,'GHA',null,null),
('GCGHA19','wc2026-golden-crumple','gc-GHA','Gana','TEAM','L',19,null,null,'GHA',null,null),
('GCGHA20','wc2026-golden-crumple','gc-GHA','Gana','TEAM','L',20,null,null,'GHA',null,null),
('GCPAN1','wc2026-golden-crumple','gc-PAN','Panamá','TEAM','L',1,null,null,'PAN',null,null),
('GCPAN2','wc2026-golden-crumple','gc-PAN','Panamá','TEAM','L',2,null,null,'PAN',null,null),
('GCPAN3','wc2026-golden-crumple','gc-PAN','Panamá','TEAM','L',3,null,null,'PAN',null,null),
('GCPAN4','wc2026-golden-crumple','gc-PAN','Panamá','TEAM','L',4,null,null,'PAN',null,null),
('GCPAN5','wc2026-golden-crumple','gc-PAN','Panamá','TEAM','L',5,null,null,'PAN',null,null),
('GCPAN6','wc2026-golden-crumple','gc-PAN','Panamá','TEAM','L',6,null,null,'PAN',null,null),
('GCPAN7','wc2026-golden-crumple','gc-PAN','Panamá','TEAM','L',7,null,null,'PAN',null,null),
('GCPAN8','wc2026-golden-crumple','gc-PAN','Panamá','TEAM','L',8,null,null,'PAN',null,null),
('GCPAN9','wc2026-golden-crumple','gc-PAN','Panamá','TEAM','L',9,null,null,'PAN',null,null),
('GCPAN10','wc2026-golden-crumple','gc-PAN','Panamá','TEAM','L',10,null,null,'PAN',null,null),
('GCPAN11','wc2026-golden-crumple','gc-PAN','Panamá','TEAM','L',11,null,null,'PAN',null,null),
('GCPAN12','wc2026-golden-crumple','gc-PAN','Panamá','TEAM','L',12,null,null,'PAN',null,null),
('GCPAN13','wc2026-golden-crumple','gc-PAN','Panamá','TEAM','L',13,null,null,'PAN',null,null),
('GCPAN14','wc2026-golden-crumple','gc-PAN','Panamá','TEAM','L',14,null,null,'PAN',null,null),
('GCPAN15','wc2026-golden-crumple','gc-PAN','Panamá','TEAM','L',15,null,null,'PAN',null,null),
('GCPAN16','wc2026-golden-crumple','gc-PAN','Panamá','TEAM','L',16,null,null,'PAN',null,null),
('GCPAN17','wc2026-golden-crumple','gc-PAN','Panamá','TEAM','L',17,null,null,'PAN',null,null),
('GCPAN18','wc2026-golden-crumple','gc-PAN','Panamá','TEAM','L',18,null,null,'PAN',null,null),
('GCPAN19','wc2026-golden-crumple','gc-PAN','Panamá','TEAM','L',19,null,null,'PAN',null,null),
('GCPAN20','wc2026-golden-crumple','gc-PAN','Panamá','TEAM','L',20,null,null,'PAN',null,null)
on conflict (code) do update
  set album_id = excluded.album_id, block_id = excluded.block_id, block_name = excluded.block_name,
      block_type = excluded.block_type, group_key = excluded.group_key, position = excluded.position,
      number = excluded.number, name = excluded.name, team_code = excluded.team_code,
      card_type = excluded.card_type, player_position = excluded.player_position;
