-- Supabase schema + seed — Álbum Copa 2026 (994 figurinhas)

create table if not exists public.stickers (
  code        text primary key,
  block_id    text not null,
  block_name  text not null,
  block_type  text not null check (block_type in ('TEAM','FWC','CC')),
  group_key   text not null,
  position    int  not null
);

create table if not exists public.collection (
  user_id    uuid not null references auth.users(id) on delete cascade,
  code       text not null references public.stickers(code) on delete cascade,
  qty        int  not null default 0 check (qty >= 0 and qty <= 99),
  updated_at timestamptz not null default now(),
  primary key (user_id, code)
);

create index if not exists collection_user_idx on public.collection(user_id);

alter table public.stickers  enable row level security;
alter table public.collection enable row level security;

create policy "stickers are readable by authenticated users"
  on public.stickers for select to authenticated using (true);

create policy "users read own collection"
  on public.collection for select to authenticated using (auth.uid() = user_id);
create policy "users write own collection"
  on public.collection for insert to authenticated with check (auth.uid() = user_id);
create policy "users update own collection"
  on public.collection for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "users delete own collection"
  on public.collection for delete to authenticated using (auth.uid() = user_id);

-- Totais por bloco (usado nos cabeçalhos de seleção)
create or replace view public.collection_totals as
select c.user_id,
       s.block_id,
       s.block_name,
       s.block_type,
       s.group_key,
       count(*) filter (where c.qty >= 1)              as coladas,
       coalesce(sum(greatest(c.qty - 1, 0)), 0)::int   as repetidas
from public.stickers s
left join public.collection c on c.code = s.code
group by c.user_id, s.block_id, s.block_name, s.block_type, s.group_key;

-- Seed das 994 figurinhas
insert into public.stickers (code, block_id, block_name, block_type, group_key, position) values
('00','fwc','FIFA World Cup History','FWC','FWC',1),
('FWC1','fwc','FIFA World Cup History','FWC','FWC',2),
('FWC2','fwc','FIFA World Cup History','FWC','FWC',3),
('FWC3','fwc','FIFA World Cup History','FWC','FWC',4),
('FWC4','fwc','FIFA World Cup History','FWC','FWC',5),
('FWC5','fwc','FIFA World Cup History','FWC','FWC',6),
('FWC6','fwc','FIFA World Cup History','FWC','FWC',7),
('FWC7','fwc','FIFA World Cup History','FWC','FWC',8),
('FWC8','fwc','FIFA World Cup History','FWC','FWC',9),
('FWC9','fwc','FIFA World Cup History','FWC','FWC',10),
('FWC10','fwc','FIFA World Cup History','FWC','FWC',11),
('FWC11','fwc','FIFA World Cup History','FWC','FWC',12),
('FWC12','fwc','FIFA World Cup History','FWC','FWC',13),
('FWC13','fwc','FIFA World Cup History','FWC','FWC',14),
('FWC14','fwc','FIFA World Cup History','FWC','FWC',15),
('FWC15','fwc','FIFA World Cup History','FWC','FWC',16),
('FWC16','fwc','FIFA World Cup History','FWC','FWC',17),
('FWC17','fwc','FIFA World Cup History','FWC','FWC',18),
('FWC18','fwc','FIFA World Cup History','FWC','FWC',19),
('FWC19','fwc','FIFA World Cup History','FWC','FWC',20),
('MEX1','MEX','México','TEAM','A',1),
('MEX2','MEX','México','TEAM','A',2),
('MEX3','MEX','México','TEAM','A',3),
('MEX4','MEX','México','TEAM','A',4),
('MEX5','MEX','México','TEAM','A',5),
('MEX6','MEX','México','TEAM','A',6),
('MEX7','MEX','México','TEAM','A',7),
('MEX8','MEX','México','TEAM','A',8),
('MEX9','MEX','México','TEAM','A',9),
('MEX10','MEX','México','TEAM','A',10),
('MEX11','MEX','México','TEAM','A',11),
('MEX12','MEX','México','TEAM','A',12),
('MEX13','MEX','México','TEAM','A',13),
('MEX14','MEX','México','TEAM','A',14),
('MEX15','MEX','México','TEAM','A',15),
('MEX16','MEX','México','TEAM','A',16),
('MEX17','MEX','México','TEAM','A',17),
('MEX18','MEX','México','TEAM','A',18),
('MEX19','MEX','México','TEAM','A',19),
('MEX20','MEX','México','TEAM','A',20),
('RSA1','RSA','África do Sul','TEAM','A',1),
('RSA2','RSA','África do Sul','TEAM','A',2),
('RSA3','RSA','África do Sul','TEAM','A',3),
('RSA4','RSA','África do Sul','TEAM','A',4),
('RSA5','RSA','África do Sul','TEAM','A',5),
('RSA6','RSA','África do Sul','TEAM','A',6),
('RSA7','RSA','África do Sul','TEAM','A',7),
('RSA8','RSA','África do Sul','TEAM','A',8),
('RSA9','RSA','África do Sul','TEAM','A',9),
('RSA10','RSA','África do Sul','TEAM','A',10),
('RSA11','RSA','África do Sul','TEAM','A',11),
('RSA12','RSA','África do Sul','TEAM','A',12),
('RSA13','RSA','África do Sul','TEAM','A',13),
('RSA14','RSA','África do Sul','TEAM','A',14),
('RSA15','RSA','África do Sul','TEAM','A',15),
('RSA16','RSA','África do Sul','TEAM','A',16),
('RSA17','RSA','África do Sul','TEAM','A',17),
('RSA18','RSA','África do Sul','TEAM','A',18),
('RSA19','RSA','África do Sul','TEAM','A',19),
('RSA20','RSA','África do Sul','TEAM','A',20),
('KOR1','KOR','Coreia do Sul','TEAM','A',1),
('KOR2','KOR','Coreia do Sul','TEAM','A',2),
('KOR3','KOR','Coreia do Sul','TEAM','A',3),
('KOR4','KOR','Coreia do Sul','TEAM','A',4),
('KOR5','KOR','Coreia do Sul','TEAM','A',5),
('KOR6','KOR','Coreia do Sul','TEAM','A',6),
('KOR7','KOR','Coreia do Sul','TEAM','A',7),
('KOR8','KOR','Coreia do Sul','TEAM','A',8),
('KOR9','KOR','Coreia do Sul','TEAM','A',9),
('KOR10','KOR','Coreia do Sul','TEAM','A',10),
('KOR11','KOR','Coreia do Sul','TEAM','A',11),
('KOR12','KOR','Coreia do Sul','TEAM','A',12),
('KOR13','KOR','Coreia do Sul','TEAM','A',13),
('KOR14','KOR','Coreia do Sul','TEAM','A',14),
('KOR15','KOR','Coreia do Sul','TEAM','A',15),
('KOR16','KOR','Coreia do Sul','TEAM','A',16),
('KOR17','KOR','Coreia do Sul','TEAM','A',17),
('KOR18','KOR','Coreia do Sul','TEAM','A',18),
('KOR19','KOR','Coreia do Sul','TEAM','A',19),
('KOR20','KOR','Coreia do Sul','TEAM','A',20),
('CZE1','CZE','Rep. Tcheca','TEAM','A',1),
('CZE2','CZE','Rep. Tcheca','TEAM','A',2),
('CZE3','CZE','Rep. Tcheca','TEAM','A',3),
('CZE4','CZE','Rep. Tcheca','TEAM','A',4),
('CZE5','CZE','Rep. Tcheca','TEAM','A',5),
('CZE6','CZE','Rep. Tcheca','TEAM','A',6),
('CZE7','CZE','Rep. Tcheca','TEAM','A',7),
('CZE8','CZE','Rep. Tcheca','TEAM','A',8),
('CZE9','CZE','Rep. Tcheca','TEAM','A',9),
('CZE10','CZE','Rep. Tcheca','TEAM','A',10),
('CZE11','CZE','Rep. Tcheca','TEAM','A',11),
('CZE12','CZE','Rep. Tcheca','TEAM','A',12),
('CZE13','CZE','Rep. Tcheca','TEAM','A',13),
('CZE14','CZE','Rep. Tcheca','TEAM','A',14),
('CZE15','CZE','Rep. Tcheca','TEAM','A',15),
('CZE16','CZE','Rep. Tcheca','TEAM','A',16),
('CZE17','CZE','Rep. Tcheca','TEAM','A',17),
('CZE18','CZE','Rep. Tcheca','TEAM','A',18),
('CZE19','CZE','Rep. Tcheca','TEAM','A',19),
('CZE20','CZE','Rep. Tcheca','TEAM','A',20),
('CAN1','CAN','Canadá','TEAM','B',1),
('CAN2','CAN','Canadá','TEAM','B',2),
('CAN3','CAN','Canadá','TEAM','B',3),
('CAN4','CAN','Canadá','TEAM','B',4),
('CAN5','CAN','Canadá','TEAM','B',5),
('CAN6','CAN','Canadá','TEAM','B',6),
('CAN7','CAN','Canadá','TEAM','B',7),
('CAN8','CAN','Canadá','TEAM','B',8),
('CAN9','CAN','Canadá','TEAM','B',9),
('CAN10','CAN','Canadá','TEAM','B',10),
('CAN11','CAN','Canadá','TEAM','B',11),
('CAN12','CAN','Canadá','TEAM','B',12),
('CAN13','CAN','Canadá','TEAM','B',13),
('CAN14','CAN','Canadá','TEAM','B',14),
('CAN15','CAN','Canadá','TEAM','B',15),
('CAN16','CAN','Canadá','TEAM','B',16),
('CAN17','CAN','Canadá','TEAM','B',17),
('CAN18','CAN','Canadá','TEAM','B',18),
('CAN19','CAN','Canadá','TEAM','B',19),
('CAN20','CAN','Canadá','TEAM','B',20),
('BIH1','BIH','Bósnia','TEAM','B',1),
('BIH2','BIH','Bósnia','TEAM','B',2),
('BIH3','BIH','Bósnia','TEAM','B',3),
('BIH4','BIH','Bósnia','TEAM','B',4),
('BIH5','BIH','Bósnia','TEAM','B',5),
('BIH6','BIH','Bósnia','TEAM','B',6),
('BIH7','BIH','Bósnia','TEAM','B',7),
('BIH8','BIH','Bósnia','TEAM','B',8),
('BIH9','BIH','Bósnia','TEAM','B',9),
('BIH10','BIH','Bósnia','TEAM','B',10),
('BIH11','BIH','Bósnia','TEAM','B',11),
('BIH12','BIH','Bósnia','TEAM','B',12),
('BIH13','BIH','Bósnia','TEAM','B',13),
('BIH14','BIH','Bósnia','TEAM','B',14),
('BIH15','BIH','Bósnia','TEAM','B',15),
('BIH16','BIH','Bósnia','TEAM','B',16),
('BIH17','BIH','Bósnia','TEAM','B',17),
('BIH18','BIH','Bósnia','TEAM','B',18),
('BIH19','BIH','Bósnia','TEAM','B',19),
('BIH20','BIH','Bósnia','TEAM','B',20),
('QAT1','QAT','Catar','TEAM','B',1),
('QAT2','QAT','Catar','TEAM','B',2),
('QAT3','QAT','Catar','TEAM','B',3),
('QAT4','QAT','Catar','TEAM','B',4),
('QAT5','QAT','Catar','TEAM','B',5),
('QAT6','QAT','Catar','TEAM','B',6),
('QAT7','QAT','Catar','TEAM','B',7),
('QAT8','QAT','Catar','TEAM','B',8),
('QAT9','QAT','Catar','TEAM','B',9),
('QAT10','QAT','Catar','TEAM','B',10),
('QAT11','QAT','Catar','TEAM','B',11),
('QAT12','QAT','Catar','TEAM','B',12),
('QAT13','QAT','Catar','TEAM','B',13),
('QAT14','QAT','Catar','TEAM','B',14),
('QAT15','QAT','Catar','TEAM','B',15),
('QAT16','QAT','Catar','TEAM','B',16),
('QAT17','QAT','Catar','TEAM','B',17),
('QAT18','QAT','Catar','TEAM','B',18),
('QAT19','QAT','Catar','TEAM','B',19),
('QAT20','QAT','Catar','TEAM','B',20),
('SUI1','SUI','Suíça','TEAM','B',1),
('SUI2','SUI','Suíça','TEAM','B',2),
('SUI3','SUI','Suíça','TEAM','B',3),
('SUI4','SUI','Suíça','TEAM','B',4),
('SUI5','SUI','Suíça','TEAM','B',5),
('SUI6','SUI','Suíça','TEAM','B',6),
('SUI7','SUI','Suíça','TEAM','B',7),
('SUI8','SUI','Suíça','TEAM','B',8),
('SUI9','SUI','Suíça','TEAM','B',9),
('SUI10','SUI','Suíça','TEAM','B',10),
('SUI11','SUI','Suíça','TEAM','B',11),
('SUI12','SUI','Suíça','TEAM','B',12),
('SUI13','SUI','Suíça','TEAM','B',13),
('SUI14','SUI','Suíça','TEAM','B',14),
('SUI15','SUI','Suíça','TEAM','B',15),
('SUI16','SUI','Suíça','TEAM','B',16),
('SUI17','SUI','Suíça','TEAM','B',17),
('SUI18','SUI','Suíça','TEAM','B',18),
('SUI19','SUI','Suíça','TEAM','B',19),
('SUI20','SUI','Suíça','TEAM','B',20),
('BRA1','BRA','Brasil','TEAM','C',1),
('BRA2','BRA','Brasil','TEAM','C',2),
('BRA3','BRA','Brasil','TEAM','C',3),
('BRA4','BRA','Brasil','TEAM','C',4),
('BRA5','BRA','Brasil','TEAM','C',5),
('BRA6','BRA','Brasil','TEAM','C',6),
('BRA7','BRA','Brasil','TEAM','C',7),
('BRA8','BRA','Brasil','TEAM','C',8),
('BRA9','BRA','Brasil','TEAM','C',9),
('BRA10','BRA','Brasil','TEAM','C',10),
('BRA11','BRA','Brasil','TEAM','C',11),
('BRA12','BRA','Brasil','TEAM','C',12),
('BRA13','BRA','Brasil','TEAM','C',13),
('BRA14','BRA','Brasil','TEAM','C',14),
('BRA15','BRA','Brasil','TEAM','C',15),
('BRA16','BRA','Brasil','TEAM','C',16),
('BRA17','BRA','Brasil','TEAM','C',17),
('BRA18','BRA','Brasil','TEAM','C',18),
('BRA19','BRA','Brasil','TEAM','C',19),
('BRA20','BRA','Brasil','TEAM','C',20),
('MAR1','MAR','Marrocos','TEAM','C',1),
('MAR2','MAR','Marrocos','TEAM','C',2),
('MAR3','MAR','Marrocos','TEAM','C',3),
('MAR4','MAR','Marrocos','TEAM','C',4),
('MAR5','MAR','Marrocos','TEAM','C',5),
('MAR6','MAR','Marrocos','TEAM','C',6),
('MAR7','MAR','Marrocos','TEAM','C',7),
('MAR8','MAR','Marrocos','TEAM','C',8),
('MAR9','MAR','Marrocos','TEAM','C',9),
('MAR10','MAR','Marrocos','TEAM','C',10),
('MAR11','MAR','Marrocos','TEAM','C',11),
('MAR12','MAR','Marrocos','TEAM','C',12),
('MAR13','MAR','Marrocos','TEAM','C',13),
('MAR14','MAR','Marrocos','TEAM','C',14),
('MAR15','MAR','Marrocos','TEAM','C',15),
('MAR16','MAR','Marrocos','TEAM','C',16),
('MAR17','MAR','Marrocos','TEAM','C',17),
('MAR18','MAR','Marrocos','TEAM','C',18),
('MAR19','MAR','Marrocos','TEAM','C',19),
('MAR20','MAR','Marrocos','TEAM','C',20),
('HAI1','HAI','Haiti','TEAM','C',1),
('HAI2','HAI','Haiti','TEAM','C',2),
('HAI3','HAI','Haiti','TEAM','C',3),
('HAI4','HAI','Haiti','TEAM','C',4),
('HAI5','HAI','Haiti','TEAM','C',5),
('HAI6','HAI','Haiti','TEAM','C',6),
('HAI7','HAI','Haiti','TEAM','C',7),
('HAI8','HAI','Haiti','TEAM','C',8),
('HAI9','HAI','Haiti','TEAM','C',9),
('HAI10','HAI','Haiti','TEAM','C',10),
('HAI11','HAI','Haiti','TEAM','C',11),
('HAI12','HAI','Haiti','TEAM','C',12),
('HAI13','HAI','Haiti','TEAM','C',13),
('HAI14','HAI','Haiti','TEAM','C',14),
('HAI15','HAI','Haiti','TEAM','C',15),
('HAI16','HAI','Haiti','TEAM','C',16),
('HAI17','HAI','Haiti','TEAM','C',17),
('HAI18','HAI','Haiti','TEAM','C',18),
('HAI19','HAI','Haiti','TEAM','C',19),
('HAI20','HAI','Haiti','TEAM','C',20),
('SCO1','SCO','Escócia','TEAM','C',1),
('SCO2','SCO','Escócia','TEAM','C',2),
('SCO3','SCO','Escócia','TEAM','C',3),
('SCO4','SCO','Escócia','TEAM','C',4),
('SCO5','SCO','Escócia','TEAM','C',5),
('SCO6','SCO','Escócia','TEAM','C',6),
('SCO7','SCO','Escócia','TEAM','C',7),
('SCO8','SCO','Escócia','TEAM','C',8),
('SCO9','SCO','Escócia','TEAM','C',9),
('SCO10','SCO','Escócia','TEAM','C',10),
('SCO11','SCO','Escócia','TEAM','C',11),
('SCO12','SCO','Escócia','TEAM','C',12),
('SCO13','SCO','Escócia','TEAM','C',13),
('SCO14','SCO','Escócia','TEAM','C',14),
('SCO15','SCO','Escócia','TEAM','C',15),
('SCO16','SCO','Escócia','TEAM','C',16),
('SCO17','SCO','Escócia','TEAM','C',17),
('SCO18','SCO','Escócia','TEAM','C',18),
('SCO19','SCO','Escócia','TEAM','C',19),
('SCO20','SCO','Escócia','TEAM','C',20),
('USA1','USA','Estados Unidos','TEAM','D',1),
('USA2','USA','Estados Unidos','TEAM','D',2),
('USA3','USA','Estados Unidos','TEAM','D',3),
('USA4','USA','Estados Unidos','TEAM','D',4),
('USA5','USA','Estados Unidos','TEAM','D',5),
('USA6','USA','Estados Unidos','TEAM','D',6),
('USA7','USA','Estados Unidos','TEAM','D',7),
('USA8','USA','Estados Unidos','TEAM','D',8),
('USA9','USA','Estados Unidos','TEAM','D',9),
('USA10','USA','Estados Unidos','TEAM','D',10),
('USA11','USA','Estados Unidos','TEAM','D',11),
('USA12','USA','Estados Unidos','TEAM','D',12),
('USA13','USA','Estados Unidos','TEAM','D',13),
('USA14','USA','Estados Unidos','TEAM','D',14),
('USA15','USA','Estados Unidos','TEAM','D',15),
('USA16','USA','Estados Unidos','TEAM','D',16),
('USA17','USA','Estados Unidos','TEAM','D',17),
('USA18','USA','Estados Unidos','TEAM','D',18),
('USA19','USA','Estados Unidos','TEAM','D',19),
('USA20','USA','Estados Unidos','TEAM','D',20),
('PAR1','PAR','Paraguai','TEAM','D',1),
('PAR2','PAR','Paraguai','TEAM','D',2),
('PAR3','PAR','Paraguai','TEAM','D',3),
('PAR4','PAR','Paraguai','TEAM','D',4),
('PAR5','PAR','Paraguai','TEAM','D',5),
('PAR6','PAR','Paraguai','TEAM','D',6),
('PAR7','PAR','Paraguai','TEAM','D',7),
('PAR8','PAR','Paraguai','TEAM','D',8),
('PAR9','PAR','Paraguai','TEAM','D',9),
('PAR10','PAR','Paraguai','TEAM','D',10),
('PAR11','PAR','Paraguai','TEAM','D',11),
('PAR12','PAR','Paraguai','TEAM','D',12),
('PAR13','PAR','Paraguai','TEAM','D',13),
('PAR14','PAR','Paraguai','TEAM','D',14),
('PAR15','PAR','Paraguai','TEAM','D',15),
('PAR16','PAR','Paraguai','TEAM','D',16),
('PAR17','PAR','Paraguai','TEAM','D',17),
('PAR18','PAR','Paraguai','TEAM','D',18),
('PAR19','PAR','Paraguai','TEAM','D',19),
('PAR20','PAR','Paraguai','TEAM','D',20),
('AUS1','AUS','Austrália','TEAM','D',1),
('AUS2','AUS','Austrália','TEAM','D',2),
('AUS3','AUS','Austrália','TEAM','D',3),
('AUS4','AUS','Austrália','TEAM','D',4),
('AUS5','AUS','Austrália','TEAM','D',5),
('AUS6','AUS','Austrália','TEAM','D',6),
('AUS7','AUS','Austrália','TEAM','D',7),
('AUS8','AUS','Austrália','TEAM','D',8),
('AUS9','AUS','Austrália','TEAM','D',9),
('AUS10','AUS','Austrália','TEAM','D',10),
('AUS11','AUS','Austrália','TEAM','D',11),
('AUS12','AUS','Austrália','TEAM','D',12),
('AUS13','AUS','Austrália','TEAM','D',13),
('AUS14','AUS','Austrália','TEAM','D',14),
('AUS15','AUS','Austrália','TEAM','D',15),
('AUS16','AUS','Austrália','TEAM','D',16),
('AUS17','AUS','Austrália','TEAM','D',17),
('AUS18','AUS','Austrália','TEAM','D',18),
('AUS19','AUS','Austrália','TEAM','D',19),
('AUS20','AUS','Austrália','TEAM','D',20),
('TUR1','TUR','Turquia','TEAM','D',1),
('TUR2','TUR','Turquia','TEAM','D',2),
('TUR3','TUR','Turquia','TEAM','D',3),
('TUR4','TUR','Turquia','TEAM','D',4),
('TUR5','TUR','Turquia','TEAM','D',5),
('TUR6','TUR','Turquia','TEAM','D',6),
('TUR7','TUR','Turquia','TEAM','D',7),
('TUR8','TUR','Turquia','TEAM','D',8),
('TUR9','TUR','Turquia','TEAM','D',9),
('TUR10','TUR','Turquia','TEAM','D',10),
('TUR11','TUR','Turquia','TEAM','D',11),
('TUR12','TUR','Turquia','TEAM','D',12),
('TUR13','TUR','Turquia','TEAM','D',13),
('TUR14','TUR','Turquia','TEAM','D',14),
('TUR15','TUR','Turquia','TEAM','D',15),
('TUR16','TUR','Turquia','TEAM','D',16),
('TUR17','TUR','Turquia','TEAM','D',17),
('TUR18','TUR','Turquia','TEAM','D',18),
('TUR19','TUR','Turquia','TEAM','D',19),
('TUR20','TUR','Turquia','TEAM','D',20),
('GER1','GER','Alemanha','TEAM','E',1),
('GER2','GER','Alemanha','TEAM','E',2),
('GER3','GER','Alemanha','TEAM','E',3),
('GER4','GER','Alemanha','TEAM','E',4),
('GER5','GER','Alemanha','TEAM','E',5),
('GER6','GER','Alemanha','TEAM','E',6),
('GER7','GER','Alemanha','TEAM','E',7),
('GER8','GER','Alemanha','TEAM','E',8),
('GER9','GER','Alemanha','TEAM','E',9),
('GER10','GER','Alemanha','TEAM','E',10),
('GER11','GER','Alemanha','TEAM','E',11),
('GER12','GER','Alemanha','TEAM','E',12),
('GER13','GER','Alemanha','TEAM','E',13),
('GER14','GER','Alemanha','TEAM','E',14),
('GER15','GER','Alemanha','TEAM','E',15),
('GER16','GER','Alemanha','TEAM','E',16),
('GER17','GER','Alemanha','TEAM','E',17),
('GER18','GER','Alemanha','TEAM','E',18),
('GER19','GER','Alemanha','TEAM','E',19),
('GER20','GER','Alemanha','TEAM','E',20),
('CUW1','CUW','Curaçao','TEAM','E',1),
('CUW2','CUW','Curaçao','TEAM','E',2),
('CUW3','CUW','Curaçao','TEAM','E',3),
('CUW4','CUW','Curaçao','TEAM','E',4),
('CUW5','CUW','Curaçao','TEAM','E',5),
('CUW6','CUW','Curaçao','TEAM','E',6),
('CUW7','CUW','Curaçao','TEAM','E',7),
('CUW8','CUW','Curaçao','TEAM','E',8),
('CUW9','CUW','Curaçao','TEAM','E',9),
('CUW10','CUW','Curaçao','TEAM','E',10),
('CUW11','CUW','Curaçao','TEAM','E',11),
('CUW12','CUW','Curaçao','TEAM','E',12),
('CUW13','CUW','Curaçao','TEAM','E',13),
('CUW14','CUW','Curaçao','TEAM','E',14),
('CUW15','CUW','Curaçao','TEAM','E',15),
('CUW16','CUW','Curaçao','TEAM','E',16),
('CUW17','CUW','Curaçao','TEAM','E',17),
('CUW18','CUW','Curaçao','TEAM','E',18),
('CUW19','CUW','Curaçao','TEAM','E',19),
('CUW20','CUW','Curaçao','TEAM','E',20),
('CIV1','CIV','Costa do Marfim','TEAM','E',1),
('CIV2','CIV','Costa do Marfim','TEAM','E',2),
('CIV3','CIV','Costa do Marfim','TEAM','E',3),
('CIV4','CIV','Costa do Marfim','TEAM','E',4),
('CIV5','CIV','Costa do Marfim','TEAM','E',5),
('CIV6','CIV','Costa do Marfim','TEAM','E',6),
('CIV7','CIV','Costa do Marfim','TEAM','E',7),
('CIV8','CIV','Costa do Marfim','TEAM','E',8),
('CIV9','CIV','Costa do Marfim','TEAM','E',9),
('CIV10','CIV','Costa do Marfim','TEAM','E',10),
('CIV11','CIV','Costa do Marfim','TEAM','E',11),
('CIV12','CIV','Costa do Marfim','TEAM','E',12),
('CIV13','CIV','Costa do Marfim','TEAM','E',13),
('CIV14','CIV','Costa do Marfim','TEAM','E',14),
('CIV15','CIV','Costa do Marfim','TEAM','E',15),
('CIV16','CIV','Costa do Marfim','TEAM','E',16),
('CIV17','CIV','Costa do Marfim','TEAM','E',17),
('CIV18','CIV','Costa do Marfim','TEAM','E',18),
('CIV19','CIV','Costa do Marfim','TEAM','E',19),
('CIV20','CIV','Costa do Marfim','TEAM','E',20),
('ECU1','ECU','Equador','TEAM','E',1),
('ECU2','ECU','Equador','TEAM','E',2),
('ECU3','ECU','Equador','TEAM','E',3),
('ECU4','ECU','Equador','TEAM','E',4),
('ECU5','ECU','Equador','TEAM','E',5),
('ECU6','ECU','Equador','TEAM','E',6),
('ECU7','ECU','Equador','TEAM','E',7),
('ECU8','ECU','Equador','TEAM','E',8),
('ECU9','ECU','Equador','TEAM','E',9),
('ECU10','ECU','Equador','TEAM','E',10),
('ECU11','ECU','Equador','TEAM','E',11),
('ECU12','ECU','Equador','TEAM','E',12),
('ECU13','ECU','Equador','TEAM','E',13),
('ECU14','ECU','Equador','TEAM','E',14),
('ECU15','ECU','Equador','TEAM','E',15),
('ECU16','ECU','Equador','TEAM','E',16),
('ECU17','ECU','Equador','TEAM','E',17),
('ECU18','ECU','Equador','TEAM','E',18),
('ECU19','ECU','Equador','TEAM','E',19),
('ECU20','ECU','Equador','TEAM','E',20),
('NED1','NED','Holanda','TEAM','F',1),
('NED2','NED','Holanda','TEAM','F',2),
('NED3','NED','Holanda','TEAM','F',3),
('NED4','NED','Holanda','TEAM','F',4),
('NED5','NED','Holanda','TEAM','F',5),
('NED6','NED','Holanda','TEAM','F',6),
('NED7','NED','Holanda','TEAM','F',7),
('NED8','NED','Holanda','TEAM','F',8),
('NED9','NED','Holanda','TEAM','F',9),
('NED10','NED','Holanda','TEAM','F',10),
('NED11','NED','Holanda','TEAM','F',11),
('NED12','NED','Holanda','TEAM','F',12),
('NED13','NED','Holanda','TEAM','F',13),
('NED14','NED','Holanda','TEAM','F',14),
('NED15','NED','Holanda','TEAM','F',15),
('NED16','NED','Holanda','TEAM','F',16),
('NED17','NED','Holanda','TEAM','F',17),
('NED18','NED','Holanda','TEAM','F',18),
('NED19','NED','Holanda','TEAM','F',19),
('NED20','NED','Holanda','TEAM','F',20),
('JPN1','JPN','Japão','TEAM','F',1),
('JPN2','JPN','Japão','TEAM','F',2),
('JPN3','JPN','Japão','TEAM','F',3),
('JPN4','JPN','Japão','TEAM','F',4),
('JPN5','JPN','Japão','TEAM','F',5),
('JPN6','JPN','Japão','TEAM','F',6),
('JPN7','JPN','Japão','TEAM','F',7),
('JPN8','JPN','Japão','TEAM','F',8),
('JPN9','JPN','Japão','TEAM','F',9),
('JPN10','JPN','Japão','TEAM','F',10),
('JPN11','JPN','Japão','TEAM','F',11),
('JPN12','JPN','Japão','TEAM','F',12),
('JPN13','JPN','Japão','TEAM','F',13),
('JPN14','JPN','Japão','TEAM','F',14),
('JPN15','JPN','Japão','TEAM','F',15),
('JPN16','JPN','Japão','TEAM','F',16),
('JPN17','JPN','Japão','TEAM','F',17),
('JPN18','JPN','Japão','TEAM','F',18),
('JPN19','JPN','Japão','TEAM','F',19),
('JPN20','JPN','Japão','TEAM','F',20),
('SWE1','SWE','Suécia','TEAM','F',1),
('SWE2','SWE','Suécia','TEAM','F',2),
('SWE3','SWE','Suécia','TEAM','F',3),
('SWE4','SWE','Suécia','TEAM','F',4),
('SWE5','SWE','Suécia','TEAM','F',5),
('SWE6','SWE','Suécia','TEAM','F',6),
('SWE7','SWE','Suécia','TEAM','F',7),
('SWE8','SWE','Suécia','TEAM','F',8),
('SWE9','SWE','Suécia','TEAM','F',9),
('SWE10','SWE','Suécia','TEAM','F',10),
('SWE11','SWE','Suécia','TEAM','F',11),
('SWE12','SWE','Suécia','TEAM','F',12),
('SWE13','SWE','Suécia','TEAM','F',13),
('SWE14','SWE','Suécia','TEAM','F',14),
('SWE15','SWE','Suécia','TEAM','F',15),
('SWE16','SWE','Suécia','TEAM','F',16),
('SWE17','SWE','Suécia','TEAM','F',17),
('SWE18','SWE','Suécia','TEAM','F',18),
('SWE19','SWE','Suécia','TEAM','F',19),
('SWE20','SWE','Suécia','TEAM','F',20),
('TUN1','TUN','Tunísia','TEAM','F',1),
('TUN2','TUN','Tunísia','TEAM','F',2),
('TUN3','TUN','Tunísia','TEAM','F',3),
('TUN4','TUN','Tunísia','TEAM','F',4),
('TUN5','TUN','Tunísia','TEAM','F',5),
('TUN6','TUN','Tunísia','TEAM','F',6),
('TUN7','TUN','Tunísia','TEAM','F',7),
('TUN8','TUN','Tunísia','TEAM','F',8),
('TUN9','TUN','Tunísia','TEAM','F',9),
('TUN10','TUN','Tunísia','TEAM','F',10),
('TUN11','TUN','Tunísia','TEAM','F',11),
('TUN12','TUN','Tunísia','TEAM','F',12),
('TUN13','TUN','Tunísia','TEAM','F',13),
('TUN14','TUN','Tunísia','TEAM','F',14),
('TUN15','TUN','Tunísia','TEAM','F',15),
('TUN16','TUN','Tunísia','TEAM','F',16),
('TUN17','TUN','Tunísia','TEAM','F',17),
('TUN18','TUN','Tunísia','TEAM','F',18),
('TUN19','TUN','Tunísia','TEAM','F',19),
('TUN20','TUN','Tunísia','TEAM','F',20),
('BEL1','BEL','Bélgica','TEAM','G',1),
('BEL2','BEL','Bélgica','TEAM','G',2),
('BEL3','BEL','Bélgica','TEAM','G',3),
('BEL4','BEL','Bélgica','TEAM','G',4),
('BEL5','BEL','Bélgica','TEAM','G',5),
('BEL6','BEL','Bélgica','TEAM','G',6),
('BEL7','BEL','Bélgica','TEAM','G',7),
('BEL8','BEL','Bélgica','TEAM','G',8),
('BEL9','BEL','Bélgica','TEAM','G',9),
('BEL10','BEL','Bélgica','TEAM','G',10),
('BEL11','BEL','Bélgica','TEAM','G',11),
('BEL12','BEL','Bélgica','TEAM','G',12),
('BEL13','BEL','Bélgica','TEAM','G',13),
('BEL14','BEL','Bélgica','TEAM','G',14),
('BEL15','BEL','Bélgica','TEAM','G',15),
('BEL16','BEL','Bélgica','TEAM','G',16),
('BEL17','BEL','Bélgica','TEAM','G',17),
('BEL18','BEL','Bélgica','TEAM','G',18),
('BEL19','BEL','Bélgica','TEAM','G',19),
('BEL20','BEL','Bélgica','TEAM','G',20),
('EGY1','EGY','Egito','TEAM','G',1),
('EGY2','EGY','Egito','TEAM','G',2),
('EGY3','EGY','Egito','TEAM','G',3),
('EGY4','EGY','Egito','TEAM','G',4),
('EGY5','EGY','Egito','TEAM','G',5),
('EGY6','EGY','Egito','TEAM','G',6),
('EGY7','EGY','Egito','TEAM','G',7),
('EGY8','EGY','Egito','TEAM','G',8),
('EGY9','EGY','Egito','TEAM','G',9),
('EGY10','EGY','Egito','TEAM','G',10),
('EGY11','EGY','Egito','TEAM','G',11),
('EGY12','EGY','Egito','TEAM','G',12),
('EGY13','EGY','Egito','TEAM','G',13),
('EGY14','EGY','Egito','TEAM','G',14),
('EGY15','EGY','Egito','TEAM','G',15),
('EGY16','EGY','Egito','TEAM','G',16),
('EGY17','EGY','Egito','TEAM','G',17),
('EGY18','EGY','Egito','TEAM','G',18),
('EGY19','EGY','Egito','TEAM','G',19),
('EGY20','EGY','Egito','TEAM','G',20),
('IRN1','IRN','Irã','TEAM','G',1),
('IRN2','IRN','Irã','TEAM','G',2),
('IRN3','IRN','Irã','TEAM','G',3),
('IRN4','IRN','Irã','TEAM','G',4),
('IRN5','IRN','Irã','TEAM','G',5),
('IRN6','IRN','Irã','TEAM','G',6),
('IRN7','IRN','Irã','TEAM','G',7),
('IRN8','IRN','Irã','TEAM','G',8),
('IRN9','IRN','Irã','TEAM','G',9),
('IRN10','IRN','Irã','TEAM','G',10),
('IRN11','IRN','Irã','TEAM','G',11),
('IRN12','IRN','Irã','TEAM','G',12),
('IRN13','IRN','Irã','TEAM','G',13),
('IRN14','IRN','Irã','TEAM','G',14),
('IRN15','IRN','Irã','TEAM','G',15),
('IRN16','IRN','Irã','TEAM','G',16),
('IRN17','IRN','Irã','TEAM','G',17),
('IRN18','IRN','Irã','TEAM','G',18),
('IRN19','IRN','Irã','TEAM','G',19),
('IRN20','IRN','Irã','TEAM','G',20),
('NZL1','NZL','Nova Zelândia','TEAM','G',1),
('NZL2','NZL','Nova Zelândia','TEAM','G',2),
('NZL3','NZL','Nova Zelândia','TEAM','G',3),
('NZL4','NZL','Nova Zelândia','TEAM','G',4),
('NZL5','NZL','Nova Zelândia','TEAM','G',5),
('NZL6','NZL','Nova Zelândia','TEAM','G',6),
('NZL7','NZL','Nova Zelândia','TEAM','G',7),
('NZL8','NZL','Nova Zelândia','TEAM','G',8),
('NZL9','NZL','Nova Zelândia','TEAM','G',9),
('NZL10','NZL','Nova Zelândia','TEAM','G',10),
('NZL11','NZL','Nova Zelândia','TEAM','G',11),
('NZL12','NZL','Nova Zelândia','TEAM','G',12),
('NZL13','NZL','Nova Zelândia','TEAM','G',13),
('NZL14','NZL','Nova Zelândia','TEAM','G',14),
('NZL15','NZL','Nova Zelândia','TEAM','G',15),
('NZL16','NZL','Nova Zelândia','TEAM','G',16),
('NZL17','NZL','Nova Zelândia','TEAM','G',17),
('NZL18','NZL','Nova Zelândia','TEAM','G',18),
('NZL19','NZL','Nova Zelândia','TEAM','G',19),
('NZL20','NZL','Nova Zelândia','TEAM','G',20),
('ESP1','ESP','Espanha','TEAM','H',1),
('ESP2','ESP','Espanha','TEAM','H',2),
('ESP3','ESP','Espanha','TEAM','H',3),
('ESP4','ESP','Espanha','TEAM','H',4),
('ESP5','ESP','Espanha','TEAM','H',5),
('ESP6','ESP','Espanha','TEAM','H',6),
('ESP7','ESP','Espanha','TEAM','H',7),
('ESP8','ESP','Espanha','TEAM','H',8),
('ESP9','ESP','Espanha','TEAM','H',9),
('ESP10','ESP','Espanha','TEAM','H',10),
('ESP11','ESP','Espanha','TEAM','H',11),
('ESP12','ESP','Espanha','TEAM','H',12),
('ESP13','ESP','Espanha','TEAM','H',13),
('ESP14','ESP','Espanha','TEAM','H',14),
('ESP15','ESP','Espanha','TEAM','H',15),
('ESP16','ESP','Espanha','TEAM','H',16),
('ESP17','ESP','Espanha','TEAM','H',17),
('ESP18','ESP','Espanha','TEAM','H',18),
('ESP19','ESP','Espanha','TEAM','H',19),
('ESP20','ESP','Espanha','TEAM','H',20),
('CPV1','CPV','Cabo Verde','TEAM','H',1),
('CPV2','CPV','Cabo Verde','TEAM','H',2),
('CPV3','CPV','Cabo Verde','TEAM','H',3),
('CPV4','CPV','Cabo Verde','TEAM','H',4),
('CPV5','CPV','Cabo Verde','TEAM','H',5),
('CPV6','CPV','Cabo Verde','TEAM','H',6),
('CPV7','CPV','Cabo Verde','TEAM','H',7),
('CPV8','CPV','Cabo Verde','TEAM','H',8),
('CPV9','CPV','Cabo Verde','TEAM','H',9),
('CPV10','CPV','Cabo Verde','TEAM','H',10),
('CPV11','CPV','Cabo Verde','TEAM','H',11),
('CPV12','CPV','Cabo Verde','TEAM','H',12),
('CPV13','CPV','Cabo Verde','TEAM','H',13),
('CPV14','CPV','Cabo Verde','TEAM','H',14),
('CPV15','CPV','Cabo Verde','TEAM','H',15),
('CPV16','CPV','Cabo Verde','TEAM','H',16),
('CPV17','CPV','Cabo Verde','TEAM','H',17),
('CPV18','CPV','Cabo Verde','TEAM','H',18),
('CPV19','CPV','Cabo Verde','TEAM','H',19),
('CPV20','CPV','Cabo Verde','TEAM','H',20),
('KSA1','KSA','Arábia Saudita','TEAM','H',1),
('KSA2','KSA','Arábia Saudita','TEAM','H',2),
('KSA3','KSA','Arábia Saudita','TEAM','H',3),
('KSA4','KSA','Arábia Saudita','TEAM','H',4),
('KSA5','KSA','Arábia Saudita','TEAM','H',5),
('KSA6','KSA','Arábia Saudita','TEAM','H',6),
('KSA7','KSA','Arábia Saudita','TEAM','H',7),
('KSA8','KSA','Arábia Saudita','TEAM','H',8),
('KSA9','KSA','Arábia Saudita','TEAM','H',9),
('KSA10','KSA','Arábia Saudita','TEAM','H',10),
('KSA11','KSA','Arábia Saudita','TEAM','H',11),
('KSA12','KSA','Arábia Saudita','TEAM','H',12),
('KSA13','KSA','Arábia Saudita','TEAM','H',13),
('KSA14','KSA','Arábia Saudita','TEAM','H',14),
('KSA15','KSA','Arábia Saudita','TEAM','H',15),
('KSA16','KSA','Arábia Saudita','TEAM','H',16),
('KSA17','KSA','Arábia Saudita','TEAM','H',17),
('KSA18','KSA','Arábia Saudita','TEAM','H',18),
('KSA19','KSA','Arábia Saudita','TEAM','H',19),
('KSA20','KSA','Arábia Saudita','TEAM','H',20),
('URU1','URU','Uruguai','TEAM','H',1),
('URU2','URU','Uruguai','TEAM','H',2),
('URU3','URU','Uruguai','TEAM','H',3),
('URU4','URU','Uruguai','TEAM','H',4),
('URU5','URU','Uruguai','TEAM','H',5),
('URU6','URU','Uruguai','TEAM','H',6),
('URU7','URU','Uruguai','TEAM','H',7),
('URU8','URU','Uruguai','TEAM','H',8),
('URU9','URU','Uruguai','TEAM','H',9),
('URU10','URU','Uruguai','TEAM','H',10),
('URU11','URU','Uruguai','TEAM','H',11),
('URU12','URU','Uruguai','TEAM','H',12),
('URU13','URU','Uruguai','TEAM','H',13),
('URU14','URU','Uruguai','TEAM','H',14),
('URU15','URU','Uruguai','TEAM','H',15),
('URU16','URU','Uruguai','TEAM','H',16),
('URU17','URU','Uruguai','TEAM','H',17),
('URU18','URU','Uruguai','TEAM','H',18),
('URU19','URU','Uruguai','TEAM','H',19),
('URU20','URU','Uruguai','TEAM','H',20),
('FRA1','FRA','França','TEAM','I',1),
('FRA2','FRA','França','TEAM','I',2),
('FRA3','FRA','França','TEAM','I',3),
('FRA4','FRA','França','TEAM','I',4),
('FRA5','FRA','França','TEAM','I',5),
('FRA6','FRA','França','TEAM','I',6),
('FRA7','FRA','França','TEAM','I',7),
('FRA8','FRA','França','TEAM','I',8),
('FRA9','FRA','França','TEAM','I',9),
('FRA10','FRA','França','TEAM','I',10),
('FRA11','FRA','França','TEAM','I',11),
('FRA12','FRA','França','TEAM','I',12),
('FRA13','FRA','França','TEAM','I',13),
('FRA14','FRA','França','TEAM','I',14),
('FRA15','FRA','França','TEAM','I',15),
('FRA16','FRA','França','TEAM','I',16),
('FRA17','FRA','França','TEAM','I',17),
('FRA18','FRA','França','TEAM','I',18),
('FRA19','FRA','França','TEAM','I',19),
('FRA20','FRA','França','TEAM','I',20),
('SEN1','SEN','Senegal','TEAM','I',1),
('SEN2','SEN','Senegal','TEAM','I',2),
('SEN3','SEN','Senegal','TEAM','I',3),
('SEN4','SEN','Senegal','TEAM','I',4),
('SEN5','SEN','Senegal','TEAM','I',5),
('SEN6','SEN','Senegal','TEAM','I',6),
('SEN7','SEN','Senegal','TEAM','I',7),
('SEN8','SEN','Senegal','TEAM','I',8),
('SEN9','SEN','Senegal','TEAM','I',9),
('SEN10','SEN','Senegal','TEAM','I',10),
('SEN11','SEN','Senegal','TEAM','I',11),
('SEN12','SEN','Senegal','TEAM','I',12),
('SEN13','SEN','Senegal','TEAM','I',13),
('SEN14','SEN','Senegal','TEAM','I',14),
('SEN15','SEN','Senegal','TEAM','I',15),
('SEN16','SEN','Senegal','TEAM','I',16),
('SEN17','SEN','Senegal','TEAM','I',17),
('SEN18','SEN','Senegal','TEAM','I',18),
('SEN19','SEN','Senegal','TEAM','I',19),
('SEN20','SEN','Senegal','TEAM','I',20),
('IRQ1','IRQ','Iraque','TEAM','I',1),
('IRQ2','IRQ','Iraque','TEAM','I',2),
('IRQ3','IRQ','Iraque','TEAM','I',3),
('IRQ4','IRQ','Iraque','TEAM','I',4),
('IRQ5','IRQ','Iraque','TEAM','I',5),
('IRQ6','IRQ','Iraque','TEAM','I',6),
('IRQ7','IRQ','Iraque','TEAM','I',7),
('IRQ8','IRQ','Iraque','TEAM','I',8),
('IRQ9','IRQ','Iraque','TEAM','I',9),
('IRQ10','IRQ','Iraque','TEAM','I',10),
('IRQ11','IRQ','Iraque','TEAM','I',11),
('IRQ12','IRQ','Iraque','TEAM','I',12),
('IRQ13','IRQ','Iraque','TEAM','I',13),
('IRQ14','IRQ','Iraque','TEAM','I',14),
('IRQ15','IRQ','Iraque','TEAM','I',15),
('IRQ16','IRQ','Iraque','TEAM','I',16),
('IRQ17','IRQ','Iraque','TEAM','I',17),
('IRQ18','IRQ','Iraque','TEAM','I',18),
('IRQ19','IRQ','Iraque','TEAM','I',19),
('IRQ20','IRQ','Iraque','TEAM','I',20),
('NOR1','NOR','Noruega','TEAM','I',1),
('NOR2','NOR','Noruega','TEAM','I',2),
('NOR3','NOR','Noruega','TEAM','I',3),
('NOR4','NOR','Noruega','TEAM','I',4),
('NOR5','NOR','Noruega','TEAM','I',5),
('NOR6','NOR','Noruega','TEAM','I',6),
('NOR7','NOR','Noruega','TEAM','I',7),
('NOR8','NOR','Noruega','TEAM','I',8),
('NOR9','NOR','Noruega','TEAM','I',9),
('NOR10','NOR','Noruega','TEAM','I',10),
('NOR11','NOR','Noruega','TEAM','I',11),
('NOR12','NOR','Noruega','TEAM','I',12),
('NOR13','NOR','Noruega','TEAM','I',13),
('NOR14','NOR','Noruega','TEAM','I',14),
('NOR15','NOR','Noruega','TEAM','I',15),
('NOR16','NOR','Noruega','TEAM','I',16),
('NOR17','NOR','Noruega','TEAM','I',17),
('NOR18','NOR','Noruega','TEAM','I',18),
('NOR19','NOR','Noruega','TEAM','I',19),
('NOR20','NOR','Noruega','TEAM','I',20),
('ARG1','ARG','Argentina','TEAM','J',1),
('ARG2','ARG','Argentina','TEAM','J',2),
('ARG3','ARG','Argentina','TEAM','J',3),
('ARG4','ARG','Argentina','TEAM','J',4),
('ARG5','ARG','Argentina','TEAM','J',5),
('ARG6','ARG','Argentina','TEAM','J',6),
('ARG7','ARG','Argentina','TEAM','J',7),
('ARG8','ARG','Argentina','TEAM','J',8),
('ARG9','ARG','Argentina','TEAM','J',9),
('ARG10','ARG','Argentina','TEAM','J',10),
('ARG11','ARG','Argentina','TEAM','J',11),
('ARG12','ARG','Argentina','TEAM','J',12),
('ARG13','ARG','Argentina','TEAM','J',13),
('ARG14','ARG','Argentina','TEAM','J',14),
('ARG15','ARG','Argentina','TEAM','J',15),
('ARG16','ARG','Argentina','TEAM','J',16),
('ARG17','ARG','Argentina','TEAM','J',17),
('ARG18','ARG','Argentina','TEAM','J',18),
('ARG19','ARG','Argentina','TEAM','J',19),
('ARG20','ARG','Argentina','TEAM','J',20),
('ALG1','ALG','Argélia','TEAM','J',1),
('ALG2','ALG','Argélia','TEAM','J',2),
('ALG3','ALG','Argélia','TEAM','J',3),
('ALG4','ALG','Argélia','TEAM','J',4),
('ALG5','ALG','Argélia','TEAM','J',5),
('ALG6','ALG','Argélia','TEAM','J',6),
('ALG7','ALG','Argélia','TEAM','J',7),
('ALG8','ALG','Argélia','TEAM','J',8),
('ALG9','ALG','Argélia','TEAM','J',9),
('ALG10','ALG','Argélia','TEAM','J',10),
('ALG11','ALG','Argélia','TEAM','J',11),
('ALG12','ALG','Argélia','TEAM','J',12),
('ALG13','ALG','Argélia','TEAM','J',13),
('ALG14','ALG','Argélia','TEAM','J',14),
('ALG15','ALG','Argélia','TEAM','J',15),
('ALG16','ALG','Argélia','TEAM','J',16),
('ALG17','ALG','Argélia','TEAM','J',17),
('ALG18','ALG','Argélia','TEAM','J',18),
('ALG19','ALG','Argélia','TEAM','J',19),
('ALG20','ALG','Argélia','TEAM','J',20),
('AUT1','AUT','Áustria','TEAM','J',1),
('AUT2','AUT','Áustria','TEAM','J',2),
('AUT3','AUT','Áustria','TEAM','J',3),
('AUT4','AUT','Áustria','TEAM','J',4),
('AUT5','AUT','Áustria','TEAM','J',5),
('AUT6','AUT','Áustria','TEAM','J',6),
('AUT7','AUT','Áustria','TEAM','J',7),
('AUT8','AUT','Áustria','TEAM','J',8),
('AUT9','AUT','Áustria','TEAM','J',9),
('AUT10','AUT','Áustria','TEAM','J',10),
('AUT11','AUT','Áustria','TEAM','J',11),
('AUT12','AUT','Áustria','TEAM','J',12),
('AUT13','AUT','Áustria','TEAM','J',13),
('AUT14','AUT','Áustria','TEAM','J',14),
('AUT15','AUT','Áustria','TEAM','J',15),
('AUT16','AUT','Áustria','TEAM','J',16),
('AUT17','AUT','Áustria','TEAM','J',17),
('AUT18','AUT','Áustria','TEAM','J',18),
('AUT19','AUT','Áustria','TEAM','J',19),
('AUT20','AUT','Áustria','TEAM','J',20),
('JOR1','JOR','Jordânia','TEAM','J',1),
('JOR2','JOR','Jordânia','TEAM','J',2),
('JOR3','JOR','Jordânia','TEAM','J',3),
('JOR4','JOR','Jordânia','TEAM','J',4),
('JOR5','JOR','Jordânia','TEAM','J',5),
('JOR6','JOR','Jordânia','TEAM','J',6),
('JOR7','JOR','Jordânia','TEAM','J',7),
('JOR8','JOR','Jordânia','TEAM','J',8),
('JOR9','JOR','Jordânia','TEAM','J',9),
('JOR10','JOR','Jordânia','TEAM','J',10),
('JOR11','JOR','Jordânia','TEAM','J',11),
('JOR12','JOR','Jordânia','TEAM','J',12),
('JOR13','JOR','Jordânia','TEAM','J',13),
('JOR14','JOR','Jordânia','TEAM','J',14),
('JOR15','JOR','Jordânia','TEAM','J',15),
('JOR16','JOR','Jordânia','TEAM','J',16),
('JOR17','JOR','Jordânia','TEAM','J',17),
('JOR18','JOR','Jordânia','TEAM','J',18),
('JOR19','JOR','Jordânia','TEAM','J',19),
('JOR20','JOR','Jordânia','TEAM','J',20),
('POR1','POR','Portugal','TEAM','K',1),
('POR2','POR','Portugal','TEAM','K',2),
('POR3','POR','Portugal','TEAM','K',3),
('POR4','POR','Portugal','TEAM','K',4),
('POR5','POR','Portugal','TEAM','K',5),
('POR6','POR','Portugal','TEAM','K',6),
('POR7','POR','Portugal','TEAM','K',7),
('POR8','POR','Portugal','TEAM','K',8),
('POR9','POR','Portugal','TEAM','K',9),
('POR10','POR','Portugal','TEAM','K',10),
('POR11','POR','Portugal','TEAM','K',11),
('POR12','POR','Portugal','TEAM','K',12),
('POR13','POR','Portugal','TEAM','K',13),
('POR14','POR','Portugal','TEAM','K',14),
('POR15','POR','Portugal','TEAM','K',15),
('POR16','POR','Portugal','TEAM','K',16),
('POR17','POR','Portugal','TEAM','K',17),
('POR18','POR','Portugal','TEAM','K',18),
('POR19','POR','Portugal','TEAM','K',19),
('POR20','POR','Portugal','TEAM','K',20),
('COD1','COD','Congo','TEAM','K',1),
('COD2','COD','Congo','TEAM','K',2),
('COD3','COD','Congo','TEAM','K',3),
('COD4','COD','Congo','TEAM','K',4),
('COD5','COD','Congo','TEAM','K',5),
('COD6','COD','Congo','TEAM','K',6),
('COD7','COD','Congo','TEAM','K',7),
('COD8','COD','Congo','TEAM','K',8),
('COD9','COD','Congo','TEAM','K',9),
('COD10','COD','Congo','TEAM','K',10),
('COD11','COD','Congo','TEAM','K',11),
('COD12','COD','Congo','TEAM','K',12),
('COD13','COD','Congo','TEAM','K',13),
('COD14','COD','Congo','TEAM','K',14),
('COD15','COD','Congo','TEAM','K',15),
('COD16','COD','Congo','TEAM','K',16),
('COD17','COD','Congo','TEAM','K',17),
('COD18','COD','Congo','TEAM','K',18),
('COD19','COD','Congo','TEAM','K',19),
('COD20','COD','Congo','TEAM','K',20),
('UZB1','UZB','Uzbequistão','TEAM','K',1),
('UZB2','UZB','Uzbequistão','TEAM','K',2),
('UZB3','UZB','Uzbequistão','TEAM','K',3),
('UZB4','UZB','Uzbequistão','TEAM','K',4),
('UZB5','UZB','Uzbequistão','TEAM','K',5),
('UZB6','UZB','Uzbequistão','TEAM','K',6),
('UZB7','UZB','Uzbequistão','TEAM','K',7),
('UZB8','UZB','Uzbequistão','TEAM','K',8),
('UZB9','UZB','Uzbequistão','TEAM','K',9),
('UZB10','UZB','Uzbequistão','TEAM','K',10),
('UZB11','UZB','Uzbequistão','TEAM','K',11),
('UZB12','UZB','Uzbequistão','TEAM','K',12),
('UZB13','UZB','Uzbequistão','TEAM','K',13),
('UZB14','UZB','Uzbequistão','TEAM','K',14),
('UZB15','UZB','Uzbequistão','TEAM','K',15),
('UZB16','UZB','Uzbequistão','TEAM','K',16),
('UZB17','UZB','Uzbequistão','TEAM','K',17),
('UZB18','UZB','Uzbequistão','TEAM','K',18),
('UZB19','UZB','Uzbequistão','TEAM','K',19),
('UZB20','UZB','Uzbequistão','TEAM','K',20),
('COL1','COL','Colômbia','TEAM','K',1),
('COL2','COL','Colômbia','TEAM','K',2),
('COL3','COL','Colômbia','TEAM','K',3),
('COL4','COL','Colômbia','TEAM','K',4),
('COL5','COL','Colômbia','TEAM','K',5),
('COL6','COL','Colômbia','TEAM','K',6),
('COL7','COL','Colômbia','TEAM','K',7),
('COL8','COL','Colômbia','TEAM','K',8),
('COL9','COL','Colômbia','TEAM','K',9),
('COL10','COL','Colômbia','TEAM','K',10),
('COL11','COL','Colômbia','TEAM','K',11),
('COL12','COL','Colômbia','TEAM','K',12),
('COL13','COL','Colômbia','TEAM','K',13),
('COL14','COL','Colômbia','TEAM','K',14),
('COL15','COL','Colômbia','TEAM','K',15),
('COL16','COL','Colômbia','TEAM','K',16),
('COL17','COL','Colômbia','TEAM','K',17),
('COL18','COL','Colômbia','TEAM','K',18),
('COL19','COL','Colômbia','TEAM','K',19),
('COL20','COL','Colômbia','TEAM','K',20),
('ENG1','ENG','Inglaterra','TEAM','L',1),
('ENG2','ENG','Inglaterra','TEAM','L',2),
('ENG3','ENG','Inglaterra','TEAM','L',3),
('ENG4','ENG','Inglaterra','TEAM','L',4),
('ENG5','ENG','Inglaterra','TEAM','L',5),
('ENG6','ENG','Inglaterra','TEAM','L',6),
('ENG7','ENG','Inglaterra','TEAM','L',7),
('ENG8','ENG','Inglaterra','TEAM','L',8),
('ENG9','ENG','Inglaterra','TEAM','L',9),
('ENG10','ENG','Inglaterra','TEAM','L',10),
('ENG11','ENG','Inglaterra','TEAM','L',11),
('ENG12','ENG','Inglaterra','TEAM','L',12),
('ENG13','ENG','Inglaterra','TEAM','L',13),
('ENG14','ENG','Inglaterra','TEAM','L',14),
('ENG15','ENG','Inglaterra','TEAM','L',15),
('ENG16','ENG','Inglaterra','TEAM','L',16),
('ENG17','ENG','Inglaterra','TEAM','L',17),
('ENG18','ENG','Inglaterra','TEAM','L',18),
('ENG19','ENG','Inglaterra','TEAM','L',19),
('ENG20','ENG','Inglaterra','TEAM','L',20),
('CRO1','CRO','Croácia','TEAM','L',1),
('CRO2','CRO','Croácia','TEAM','L',2),
('CRO3','CRO','Croácia','TEAM','L',3),
('CRO4','CRO','Croácia','TEAM','L',4),
('CRO5','CRO','Croácia','TEAM','L',5),
('CRO6','CRO','Croácia','TEAM','L',6),
('CRO7','CRO','Croácia','TEAM','L',7),
('CRO8','CRO','Croácia','TEAM','L',8),
('CRO9','CRO','Croácia','TEAM','L',9),
('CRO10','CRO','Croácia','TEAM','L',10),
('CRO11','CRO','Croácia','TEAM','L',11),
('CRO12','CRO','Croácia','TEAM','L',12),
('CRO13','CRO','Croácia','TEAM','L',13),
('CRO14','CRO','Croácia','TEAM','L',14),
('CRO15','CRO','Croácia','TEAM','L',15),
('CRO16','CRO','Croácia','TEAM','L',16),
('CRO17','CRO','Croácia','TEAM','L',17),
('CRO18','CRO','Croácia','TEAM','L',18),
('CRO19','CRO','Croácia','TEAM','L',19),
('CRO20','CRO','Croácia','TEAM','L',20),
('GHA1','GHA','Gana','TEAM','L',1),
('GHA2','GHA','Gana','TEAM','L',2),
('GHA3','GHA','Gana','TEAM','L',3),
('GHA4','GHA','Gana','TEAM','L',4),
('GHA5','GHA','Gana','TEAM','L',5),
('GHA6','GHA','Gana','TEAM','L',6),
('GHA7','GHA','Gana','TEAM','L',7),
('GHA8','GHA','Gana','TEAM','L',8),
('GHA9','GHA','Gana','TEAM','L',9),
('GHA10','GHA','Gana','TEAM','L',10),
('GHA11','GHA','Gana','TEAM','L',11),
('GHA12','GHA','Gana','TEAM','L',12),
('GHA13','GHA','Gana','TEAM','L',13),
('GHA14','GHA','Gana','TEAM','L',14),
('GHA15','GHA','Gana','TEAM','L',15),
('GHA16','GHA','Gana','TEAM','L',16),
('GHA17','GHA','Gana','TEAM','L',17),
('GHA18','GHA','Gana','TEAM','L',18),
('GHA19','GHA','Gana','TEAM','L',19),
('GHA20','GHA','Gana','TEAM','L',20),
('PAN1','PAN','Panamá','TEAM','L',1),
('PAN2','PAN','Panamá','TEAM','L',2),
('PAN3','PAN','Panamá','TEAM','L',3),
('PAN4','PAN','Panamá','TEAM','L',4),
('PAN5','PAN','Panamá','TEAM','L',5),
('PAN6','PAN','Panamá','TEAM','L',6),
('PAN7','PAN','Panamá','TEAM','L',7),
('PAN8','PAN','Panamá','TEAM','L',8),
('PAN9','PAN','Panamá','TEAM','L',9),
('PAN10','PAN','Panamá','TEAM','L',10),
('PAN11','PAN','Panamá','TEAM','L',11),
('PAN12','PAN','Panamá','TEAM','L',12),
('PAN13','PAN','Panamá','TEAM','L',13),
('PAN14','PAN','Panamá','TEAM','L',14),
('PAN15','PAN','Panamá','TEAM','L',15),
('PAN16','PAN','Panamá','TEAM','L',16),
('PAN17','PAN','Panamá','TEAM','L',17),
('PAN18','PAN','Panamá','TEAM','L',18),
('PAN19','PAN','Panamá','TEAM','L',19),
('PAN20','PAN','Panamá','TEAM','L',20),
('CC1','cc','Coca-Cola','CC','CC',1),
('CC2','cc','Coca-Cola','CC','CC',2),
('CC3','cc','Coca-Cola','CC','CC',3),
('CC4','cc','Coca-Cola','CC','CC',4),
('CC5','cc','Coca-Cola','CC','CC',5),
('CC6','cc','Coca-Cola','CC','CC',6),
('CC7','cc','Coca-Cola','CC','CC',7),
('CC8','cc','Coca-Cola','CC','CC',8),
('CC9','cc','Coca-Cola','CC','CC',9),
('CC10','cc','Coca-Cola','CC','CC',10),
('CC11','cc','Coca-Cola','CC','CC',11),
('CC12','cc','Coca-Cola','CC','CC',12),
('CC13','cc','Coca-Cola','CC','CC',13),
('CC14','cc','Coca-Cola','CC','CC',14)
on conflict (code) do nothing;
